### ISSUE TITLE
Bug: WA.onLeaveZone is not triggered when closing WA

### ISSUE THREAD

**Issue by johanvo** [thecodingmachine/workadventure#1008]
### Reproduction
* Make sure your browsers developer tools console persists its messages when navigating to a different domain.
* Create a map with a zone called "thezone" and a scriptfile with the following content 
```
WA.onEnterZone('thezone', () => {
    console.log('Entering');
});
WA.onLeaveZone('thezone', () => {
    console.log('Leaving');
});
```
* Load the map, walk into and out of the zone repeatedly and see the messages appear in your browsers developer tool console.
* Stand inside the zone and type some different url into your browsers navigation bar and press Enter

### Current behavior 
* Nothing is shown in the developer tools console

### Expected behavior
* "Leaving" is shown in the developer tools console

### Notes
* The same is true for going to a different map via an exitUrl layer, but this can be somewhat worked around and is lower priority for me.
* I suspect the above is true as well for outright closing the browser, but have not had the time to verify it.
* Use case for me:  keeping a count of how many people are in a certain area (by doing AJAX calls to a self-build API)

**Comment by jonnytest1** [comment]
for keeping count you cna use the backends /dump API whic hrequired the admin token
aside from that you can try to use the window.onbeforeubload callback to have a callbakc on exit

**Comment by nolway** [comment]
WA.onInit() must be use to wait when the api is ready to be used.
onEnterZone & onLeaveZone has been deprecated, you can use instead onEnterLayer & onLeaveLayer : https://workadventu.re/map-building/api-room.md#detecting-when-the-user-entersleaves-a-layer
