### ISSUE TITLE
Bad performance since last few releases

### ISSUE THREAD

**Issue by max-wittig** [thecodingmachine/workadventure#1019]
I'm not sure what happened, but my notebook really hit's it's limit with the last few versions. Fan spins up to 100%.

Also the audio now has a lot of random background noises. Was noise cancelation disabled?

Everything was really good in version `1.2.3`

Firefox 88.0.1
macOS 11.3.1

**Comment by tabascoeye** [comment]
yes:
https://github.com/thecodingmachine/workadventure/blob/0c279750be14c57864a879c1345e5121775d3a45/front/src/WebRtc/MediaManager.ts#L23

That is my fault, I included it in a PR but I already said it was a bad idea:
https://github.com/thecodingmachine/workadventure/pull/688#pullrequestreview-634919233

**Comment by gparant** [comment]
The previous release of WorkAdventure solves this issue 🚀

Thanks for your feedback 💪 
If you have any requirement don't hesitate to create new issue 😍
