### ISSUE TITLE
An error occurred while loading resource

### ISSUE THREAD

**Issue by ghost** [thecodingmachine/workadventure#1030]
Hi,

I keep getting this error as soon as I use any tileset other than that included in the tutorial map: have tried with creating new maps, have tried just changing one or two tiles in the tutorial map, exporting the tilesets out in every format possible and putting in the github folder as well as always embedding it when importing it in. Have got this error with different tilesets, have also deleted my repository three times and restarted. 

Please advise. 

<img width="789" alt="Screenshot 2021-05-10 at 22 10 17" src="https://user-images.githubusercontent.com/83920675/117718595-95423e00-b1dc-11eb-925d-11616ca3f8b7.png">

**Comment by jonnytest1** [comment]
your tilesets - and their images need to be inside the git repository

an easy test is to move the git repo folder to somewhere else then tiles will ask you for all missing resources

**Comment by gparant** [comment]
Check your tileset imported, must be in the same folder of your map.json file. I close this issue, don't hesitate to create new if you have any other problem 🚀 

Thanks for your feedback 💪 
If you have any requirement don't hesitate to create new issue 😍
