### ISSUE TITLE
When exiting iframe, the joystick is block on is last direction

### ISSUE THREAD

**Issue by GRL78** [thecodingmachine/workadventure#1042]
When you exiting a zone with an iframe using the joystick, the joystick stay block on the last direction that he had before exiting the zone.

**Comment by GRL78** [comment]
The problem come from the size of the screen. 
When an iframe is open, the screen is small enough so that the joystick can be use. But when the iframe close because we leave the zone, the joystick can't be use anymore but it keept his last input.

The joystick should be totally desactivated  and RESET when the screen is no longer the correct size.

**Comment by gparant** [comment]
reference to #2218

Thanks for your feedback 💪 
If you have any other question, don't hesitate to create new issue 😍
