### ISSUE TITLE
rendering only on move? co-website / jitsi triggered breaks view

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1044]
Since a few days/week the develop branch is broken for me.
In Firefox (Linux) I experience a black screen when opening website or Jitsi. Moving character solves this to an zoomed-out view.
![firefox](https://user-images.githubusercontent.com/2760570/118138775-ffd6c200-b406-11eb-8923-601906310462.png)
In Chrome (Linux) I have basically the same issues, but not blacked screen, but distorted view.
![chrome](https://user-images.githubusercontent.com/2760570/118138886-20068100-b407-11eb-9d21-a748dd3f6047.png)
I am not sure what causes this, but it seems that rendering is only done when moving character. (Also noticing with Animations Patch: Animations now are only playing while moving. If character stand still, animation is stopped!)

**Comment by Jacques-Olivier-Farcy** [comment]
Hi @Lurkars ,

Have you got your own server ?
Any messages in the web console ?

**Comment by Lurkars** [comment]
I am just testing on a local machine. But experience for example completely the same issue on: https://play.emote.test.workadventu.re directly on startup TCM:// website opens and I am getting a black left side. Web console does not output much related
![tcm](https://user-images.githubusercontent.com/2760570/118152024-8b0a8480-b414-11eb-96da-99321f3450c8.png)
. Maybe this line is related? ```This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.```

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

What Linux version are you using ?

**Comment by Lurkars** [comment]
Ubuntu 20.04, but I just tested on Firefox Android: same issue with blackscreen, so not directly issues with specific OS.
Also on mobile I have to tilt screen to trigger a re-rendering of Name-Input and Character selection to get it look like it should be. So whatever changed in the last commits, it is about rendering and break things! I am a bit confused, that other's don't have these issues, but as mentioned I get same issues on WA test servers with later versions like https://play.emote.test.workadventu.re

**Comment by tabascoeye** [comment]
Can confirm this on macos with firefox:

https://user-images.githubusercontent.com/111893/118367015-ea959b00-b5a0-11eb-81f4-b87ca0ed7474.mov

**Comment by moufmouf** [comment]
I can confirm the issue. This should be solved by #1056
