### ISSUE TITLE
Does not load map

### ISSUE THREAD

**Issue by knbonn** [thecodingmachine/workadventure#1046]
Have connected my map link with my Workadventure account: the github link loads when testing it, but it does not load when connected. It is permanently stuck on the screen below. 

<img width="826" alt="Screenshot 2021-05-13 at 19 04 25" src="https://user-images.githubusercontent.com/83920675/118162910-9c0dc280-b421-11eb-99cd-d97d11a78410.png">

The link is https://knbonn.github.io/test-infinity/

Please advise.

**Comment by jonnytest1** [comment]
loads fine for me

**Comment by knbonn** [comment]
Hi the link above loads perfectly fine as mentioned: that is the test github link. I would prefer not to paste my workadventure account link here as it is with my company name, but I have also attached it to my personal account and it does not work there either. See here: 
https://play.workadventu.re/@/testkn/testkn/office

**Comment by knbonn** [comment]
<img width="548" alt="Screenshot 2021-05-13 at 20 46 40" src="https://user-images.githubusercontent.com/83920675/118172213-67ebcf00-b42c-11eb-9b9f-83175a72bee3.png">

These are the errors according to Chrome, which I only get when connecting to Workadventure, running the test account does not cause issues.

**Comment by jonnytest1** [comment]
yeah you got the wrong link for that one
and its not returning your json but some html instead

**Comment by knbonn** [comment]
How do I get the right link? I only have the one link that is provided on the website. We have purchased an Event for 65 colleagues for next week Monday, so I would like to get things running in advance. 

I could, of course, just send the test account link to all, but that defeats the point and also there is a window that always appears on the right advertising Work Adventure with the test account.

<img width="1126" alt="Screenshot 2021-05-13 at 20 51 37" src="https://user-images.githubusercontent.com/83920675/118172898-358ea180-b42d-11eb-99f0-1deb7917f3d8.png">

**Comment by jonnytest1** [comment]
oh at map url you need to specifiy a link ending with .json ie direct link to file

**Comment by knbonn** [comment]
Ahh, thank you for the quick reply. Such a simple error :) 

One final question: do I need to create individual rooms in Jitsi and then link them, or can I leave the property empty and the website generates individual instances (not that all Jitsi rooms are the same room)? 

There is a strange error I keep encountering where my Jitsi Rooms do not open up until I first deactivate my video camera even if I have entered them before (which always activates itself). It works once I deactivate my video camera, but I do not understand the error so cannot mitigate it. 

<img width="1435" alt="Screenshot 2021-05-13 at 21 04 21" src="https://user-images.githubusercontent.com/83920675/118174212-d467cd80-b42e-11eb-8d3b-e2d042c9c50c.png">

**Comment by jonnytest1** [comment]
i dont think there is any random jitsi room thing inth ecode - but you cna just specify a room and it will be created when someone walks onto the tile - no need to manually create them

**Comment by knbonn** [comment]
OK, thank you :)

**Comment by tabascoeye** [comment]
@knbonn can this issue be closed?

**Comment by knbonn** [comment]
Yes, please.
