### ISSUE TITLE
Any other simple possibility for hosting other than github?

### ISSUE THREAD

**Issue by knnrw** [thecodingmachine/workadventure#1050]
For whatever reason, github is causing major issues since this afternoon and every single account I create is instantly flagged and blocked (without having taken any action). My previous page, which was working is not working anymore clearly as the repository and account was somehow also deleted. Is there any other simple/quick way to host a map for someone who is not a developer?

**Comment by gparant** [comment]
One option that you could use, is: S3 bucket.

Thanks for your feedback 💪 
If you have any other question, don't hesitate to create new issue 😍
