### ISSUE TITLE
Add line break option in javascript popUp text ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1061]
Hi,

I tried to add a line break in the text in the popUp in a script.
I tried :

` '<br>', '</br>', '\n', '\n\r'`

 
 But none of those worked.

Is there a way to have this feature ?

**Comment by jonnytest1** [comment]
have you tried with <br> ? maybe the sanitization allows that ^^

**Comment by gparant** [comment]
This update was deployed on production server 🚀 

Thanks for your feedback 💪

**Comment by Jacques-Olivier-Farcy** [comment]
"\n" is working fine now
