### ISSUE TITLE
Feature Request: Change object with a script

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1062]
Changing or animation triggered by a script to show a change.

**Comment by jonnytest1** [comment]
clone of https://github.com/thecodingmachine/workadventure/pull/884

**Comment by gparant** [comment]
Today with the scripting API you can animate the environment of the user. Don't hesitate to check our documentation => https://workadventu.re/map-building/scripting.md

We have this issue open for the object => #2303

Thanks for your feedback 💪 
If you have any requirement, don't hesitate to create new issue 😍
