### ISSUE TITLE
Feature Request: Change default selectable avatars

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1063]
Possibility to change the default selectable avatars (not custimization)

**Comment by tabascoeye** [comment]
if you self-host, you can modify them to your hearts desire...

**Comment by gparant** [comment]
You have the possibility to change / import the default avatar with our administrative back office 🚀 
https://workadventu.re/admin

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create new issue 😍
