### ISSUE TITLE
Admin mode in self-hosted?

### ISSUE THREAD

**Issue by max-wittig** [thecodingmachine/workadventure#1079]
Is that possible or is that an enterprise feature?

**Comment by Jacques-Olivier-Farcy** [comment]
Hi @max-wittig ,

what do you mean by admin mode ?

**Comment by tabascoeye** [comment]
The Admin backend (create users, ban users, tag users, global messages,...) is an enterprise feature.
The API is of course there in the opensource version, but you would have to program your own server when self-hosting.

**Comment by max-wittig** [comment]
Okay thanks 👍
