### ISSUE TITLE
popUp won't close after opening a video file

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1097]
Hi,

When i open a popUp with a script which play a video file, if i leave the zone, the popUp won't close.

**Comment by Jacques-Olivier-Farcy** [comment]
https://user-images.githubusercontent.com/19731340/120224971-b11d8a80-c244-11eb-958f-66df8608d528.mp4

**Comment by jonnytest1** [comment]
looks pretty closed to me ? if you wnat to close the video on the side you need to use WA.closeCoWebsite

**Comment by Jacques-Olivier-Farcy** [comment]
Actually my script is :

```
WA.onEnterZone(zone3MovieName, () => {
   currentPopup =  WA.openPopup("popUp3Movie","Film 3 : Test teaser cadeaux",[
 	{
		label: "VOIR",
            className: "popUpElement",
            callback: (popup => {
				WA.openCoWebSite(urlMovie3);
                closePopUp();
            })
        }]);
})
WA.onLeaveZone(zone3MovieName, closePopUp)
```

**Comment by Jacques-Olivier-Farcy** [comment]
It works, i have added at the end:
WA.onLeaveZone(zone3MovieName, WA.closeCoWebSite)

Thanks!

**Comment by Jacques-Olivier-Farcy** [comment]
Solved
