### ISSUE TITLE
Microphone and camera off

### ISSUE THREAD

**Issue by jduulie** [thecodingmachine/workadventure#1110]
I turned off my mic and camera on a map (fun & learn), then reactivated it on another map (tcm - ground floor) but it continues to be both off when I go to another map (wa map then tcm 1st floor). 
I also had the case : buttons off but camera still on on the screen (when I go back to tcm - ground floor)

**Comment by moufmouf** [comment]
Seems to be fixed with the new version.
Feel free to reopen if you are still facing the problem.
