### ISSUE TITLE
Mobile touch controls trigger zoom all the time

### ISSUE THREAD

**Issue by sils** [thecodingmachine/workadventure#1114]
Steps to reproduce:

1. Open workadventure latest release as of today on a phone (in my case Google pixel 4a)
2. Enter the workadventure map, confirm camera settings
3. Push one finger in the middle of the screen, drag down (or in any direction)
4. Character will move correctly here
5. Lift finger
6. Repeat step 3

Instead of moving the character the UI will zoom in and out.

CC @yuki_is_bored

**Comment by moufmouf** [comment]
Hey @sils,

Are you testing from the "develop" branch, or are you testing online on "play.workadventu.re"?

**Comment by yukiisbored** [comment]
We switched from the `master` image to `develop` and everything seems to be working fine for now.
