### ISSUE TITLE
CV cannot be easily closed on mobile

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1123]
CV is too wide.

![image](https://user-images.githubusercontent.com/1290952/120831502-e20d0080-c55f-11eb-8c6c-cbeacd4948b1.png)

**Comment by tabascoeye** [comment]
I would love to have this feature "surrounded" by the ADMIN_API_URL variable.
So for self-hosters, it simply doesn't exist at all. It does not make sense to have a window pop up which will literally never have content.

**Comment by tabascoeye** [comment]
so kind of like an `#ifdef` in C

**Comment by Kharhamel** [comment]
This would have to be disabled client side. Something like a variable DISABLE_VISIT_CARD in the front

**Comment by tabascoeye** [comment]
Yes that's what I'm asking for

**Comment by Kharhamel** [comment]
Oh by the way this issue is already  solved on develop

**Comment by jonnytest1** [comment]
why not just add additional environment variables ? they already end up in the frontend anyways (like in iFrameListener process.env)
