### ISSUE TITLE
Cameras LED always on

### ISSUE THREAD

**Issue by kidager** [thecodingmachine/workadventure#1138]
The LED on the all the cameras connected to my computer are always on, even though I disabled my camera (c.f. screenshot)

![Screenshot 1](https://user-images.githubusercontent.com/3314980/121151505-b8482800-c844-11eb-882b-e06c411d836d.png)

**Comment by moufmouf** [comment]
Hey @kidager,

Are you seeing this on play.workadventu.re ?
Pretty sure this issue is solved in the develop branch that will be released in prod next week.

**Comment by kidager** [comment]
Yes, it's on [play.workadventu.re](https://play.workadventu.re)
