### ISSUE TITLE
[BUG] workadventure ignore port for relative exit url

### ISSUE THREAD

**Issue by Lukas1818** [thecodingmachine/workadventure#1156]
I did use the relative exit url `map.json#start` in my map. I did test the map local at `https://workadventure.example.com/_/global/localhost:8080/map.json` and use the exit. I get forwarded to `https://workadventure.example.com/_/global/localhost/map.json#start` instead to `https://workadventure.example.com/_/global/localhost:8080/map.json#start`
I think workadventure should keep the port.

**Comment by jonnytest1** [comment]
> I did use the relative exit url `map.json#start` in my map. I did test the map local at `https://workadventure.example.com/_/global/localhost:8080/map.json` and use the exit. I get forwarded to `https://workadventure.example.com/_/global/localhost/map.json#start` instead to `https://workadventure.example.com/_/global/localhost:8080/map.json#start`
> I think workadventure should keep the port.

not sure this is a useful fix - productive delpoyment should always use the standard https port 443

so this fix would be only really useful for local development so just running a local file server on port 80 might be easier (personally i have an nginx reverse proxy on my local machine serving all the static files)

**Comment by Lukas1818** [comment]
duplicate  https://github.com/thecodingmachine/workadventure-map-starter-kit/issues/7
