### ISSUE TITLE
Bug in staging environment

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1167]
Big black screen instead of Phaser today in staging environment

![image](https://user-images.githubusercontent.com/1290952/121711880-5bb26a80-cadb-11eb-9ee7-f461a50e3c69.png)

**Comment by jonnytest1** [comment]
https://github.com/thecodingmachine/workadventure/commit/1264b286b242d188a2be986a979beefa72e2aa8b

**Comment by moufmouf** [comment]
Indeed. I really don't understand how the "scene" in a sprite can suddenly go the "null". I guess the loading of the sprite textures ends after the sprite is destroyed?

**Comment by jonnytest1** [comment]
> Indeed. I really don't understand how the "scene" in a sprite can suddenly go the "null". I guess the loading of the sprite textures ends after the sprite is destroyed?

GameObject.js#destroy
...
this.scene = undefined;
