### ISSUE TITLE
qestion: how can I disabel the start I frame

### ISSUE THREAD

**Issue by Lukas1818** [thecodingmachine/workadventure#1168]
Everytime I join my server I get this start iframe:
![image](https://user-images.githubusercontent.com/44570204/121741745-39324880-caff-11eb-8ac2-01da3578d3dc.png)
How can I disable it?

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

You should edit the json file of you map with Tiled map editor and watch for a layer with openWebsite property.

**Comment by Lukas1818** [comment]
I have already check this and have done it again now. But there is now Layer wit the openWebsite property.
I have also open the map in a normal text editor and search for `open` and have found nothing.

https://github.com/Lukas1818/workadventure-map-RWTH-mentoring-keller

**Comment by jonnytest1** [comment]
https://github.com/Lukas1818/workadventure-map-RWTH-mentoring-keller/blob/gh-pages/script.js here remove the openCoWebSite also make sure its the correct branch (gh-pages is the one being deployed)

**Comment by Lukas1818** [comment]
Thanks I did not check this branch.
So that does means that I should had done my map changes on gh-pages branch and not at master?

**Comment by jonnytest1** [comment]
> Thanks I did not check this branch.
> So that does means that I should had done my map changes on gh-pages branch and not at master?
> What does happen if I did create a `script.js` at master?

nothing really it will just sit there only the gh-pages branch is reachable via the pages link

**Comment by Lukas1818** [comment]
> nothing really it will just sit there only the gh-pages branch is reachable via the pages link

But the master will be deployed to gh-pages by git-actions. So that mean the git-action will overwrite the `script.js` of the master?

**Comment by jonnytest1** [comment]
> > nothing really it will just sit there only the gh-pages branch is reachable via the pages link
> 
> But the master will be deployed to gh-pages by git-actions. So that mean the git-action will overwrite the `script.js` from the master?

no gh-pages is deployed unless you actively changed it in the settings

**Comment by Lukas1818** [comment]
I did simple remove the script property from the map now.
But I am still confused about with part of master will be deployed to the gh-pages branch.

**Comment by jonnytest1** [comment]
> I did simple remove the script property from the map now.
> But I am still confused about with part of master will be deployed to the gh-pages branch.

master and gh-pages are completely independent branches now - there will be no deployement of  master to gh-pages unless you manually merge them

**Comment by Lukas1818** [comment]
But if I push to master, the github actions does also change the gh-pages branch:
https://github.com/Lukas1818/workadventure-map-RWTH-mentoring-keller/commit/a204f55176de83099657328dda89a2b815a8097a
I have never push or merge the branch manual.

**Comment by jonnytest1** [comment]
> But if I push to master, the github actions does also change the gh-pages branch:
> [Lukas1818/workadventure-map-RWTH-mentoring-keller@a204f55](https://github.com/Lukas1818/workadventure-map-RWTH-mentoring-keller/commit/a204f55176de83099657328dda89a2b815a8097a)
> I have never push or merge the branch manual.

oh then ignore my posts ^^
