### ISSUE TITLE
qestion:How can I open the chat?

### ISSUE THREAD

**Issue by Lukas1818** [thecodingmachine/workadventure#1169]
The npc in the [demo](https://play.staging.workadventu.re/@/tcm/workadventure/demo) tell me that I can use a chat.
![image](https://user-images.githubusercontent.com/44570204/121742285-ea38e300-caff-11eb-8651-a2e394432d3f.png)
But I was not able to open the chat by myself. I think I have now press every key on my keyboard multiple times.

**Comment by jonnytest1** [comment]
if you dont hae other players nearby the only thing you can do is hope for a script to open it 
when the reigster menu command api gets merge you can also register a menu item to open chat by sending a message

**Comment by Lukas1818** [comment]
Thanks if I move to a nearby player a button, which can open the chat, deos appear in the corner.
![image](https://user-images.githubusercontent.com/44570204/121773523-c1a2fe80-cb7c-11eb-8c34-adba4f46861d.png)

But who is Moi? Their only the tow test users on this server.
![image](https://user-images.githubusercontent.com/44570204/121773641-776e4d00-cb7d-11eb-8d40-12a2cd02b27f.png)

**Comment by jonnytest1** [comment]
moi is i think frenbch for "Me" so thats you ^^

**Comment by Lukas1818** [comment]
May "me" should be used instead, because not french speaking users does not understand the meaning of this.

**Comment by jonnytest1** [comment]
i think @Kharhamel  was currently rebuilding the chat anyways https://github.com/thecodingmachine/workadventure/pull/1111

**Comment by Kharhamel** [comment]
that's funny, I never noticed that the text of this thumbnail was in french.
Right now, in order to open the chat  window, you need to be in a discussion (an icon will appear at the bottom left of the screen)

But I am planning to make it always accessible and persistent between discussions.
