### ISSUE TITLE
Downgrade video quality

### ISSUE THREAD

**Issue by gulien** [thecodingmachine/workadventure#117]
I wonder if it is possible to downgrade the video quality; for instance use a 360p sort of definition so that it will reduce the bandwidth requirement for all peers.

**Comment by moufmouf** [comment]
I think the codecs used are supposed to be adaptative and basically stream what they can and automatically adapt video quality based on available bandwidth.

So there should be no need to do this manually as it is built in the browser (that probably will do this better than we ever can). See https://stackoverflow.com/questions/24227705/change-the-quality-webrtc
