### ISSUE TITLE
Click zone of emotes is offset when cowebsite opens in "vertical" mode

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1184]
Put your browser in vertical mode (width < height)
Click on your woka to open the Emotes pane
Walk towards a cowesite. The cowebsite opens (and the zoom level changes)

Now, try clicking or hovering over an emote.
You'll see the click zone is not centered over the emote sprites.

**Comment by nolway** [comment]
Fixed on the latest version.
