### ISSUE TITLE
Is PlayerControl Working ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1191]
Hi,

I am using this js script :
WA.onEnterZone(zone0WelcomeName, () => {
   WA.disablePlayerControls();	
   currentPopup =  WA.openPopup("popUp0Welcome","Bienvenue à l'escape game en ligne panique dans la station spatiale. Veuillez vous installer autour de la piscine et attendre les instructions du commandant de la station.",[
        {
            label: "OK",
            className: "popUpElement",
            callback: (popup => {
                // WA.openCoWebSite(urlTeleport);
                // isCoWebSiteOpened = true;
				WA.restorePlayerControls();
                closePopUp();
            })
        }]);
})
WA.onLeaveZone(zone0WelcomeName, closePopUp)

I have this error:

Uncaught TypeError: WA.disablePlayerControls is not a function

Do i miss something?

**Comment by jonnytest1** [comment]
```
WA.onEnterZone(zone0WelcomeName, () => {
    WA.disablePlayerControls();
    currentPopup = WA.openPopup("popUp0Welcome", "Bienvenue à l'escape game en ligne panique dans la station spatiale. Veuillez vous installer autour de la piscine et attendre les instructions du commandant de la station.", [
        {
            label: "OK",
            className: "popUpElement",
            callback: (popup => {
                // WA.openCoWebSite(urlTeleport);
                // isCoWebSiteOpened = true;
                WA.restorePlayerControls();
                closePopUp();
            })
        }]);
})
WA.onLeaveZone(zone0WelcomeName, closePopUp)
```

**Comment by Jacques-Olivier-Farcy** [comment]
The entire script is:

```
// Message for the console
console.log("SCRIPT IS COMING!");

// Variables of zones
var zone0WelcomeName = "popUp0Welcome";

// Other variables
var currentPopup = undefined;
var isCoWebSiteOpened =  false;

// popUp Welcome
WA.onEnterZone(zone0WelcomeName, () => {
   // WA.disablePlayerControls();	
   currentPopup =  WA.openPopup("popUp0Welcome","Bienvenue à l'escape game en ligne panique dans la station spatiale. Veuillez vous installer autour de la piscine et attendre les instructions du commandant de la station.",[
        {
            label: "OK",
            className: "popUpElement",
            callback: (popup => {
                // WA.openCoWebSite(urlTeleport);
                // isCoWebSiteOpened = true;
				// WA.restorePlayerControls();
                closePopUp();
            })
        }]);
})
WA.onLeaveZone(zone0WelcomeName, closePopUp)

function closePopUp(){
    if (currentPopup !== undefined) {
        currentPopup.close();
        currentPopup = undefined;
    }
}
```

**Comment by moufmouf** [comment]
There is one breaking change between the staging environment and the prod environment:

WA.disablePlayerControl was renamed to WA.disablePlayerControls
and WA.enablePlayerControl was renamed to WA.enablePlayerControls

Sorry for the issue!

**Comment by moufmouf** [comment]
@Jacques-Olivier-Farcy we are releasing staging in prod tonight, so this should work tomorrow morning!

**Comment by Jacques-Olivier-Farcy** [comment]
I will wait 😄
