### ISSUE TITLE
On landscape mode on mobile we can see the empty cowebsite 

### ISSUE THREAD

**Issue by GRL78** [thecodingmachine/workadventure#1196]
![Pasted Image_ Jun 15, 2021 - 10_39_14am](https://user-images.githubusercontent.com/80678534/122199254-2a9ab700-ce9a-11eb-8650-481b339f6bf3.png)

**Comment by jonnytest1** [comment]
oh on that map you're stuck by the way ^^

**Comment by nolway** [comment]
Fixed on latest version.
