### ISSUE TITLE
Change Workadventure Map with HTML link

### ISSUE THREAD

**Issue by Razielruss** [thecodingmachine/workadventure#1231]
Hallo,

I create a cage in my Workadventure map. In this cage u can open my html site with a question. If you solve it than u come out and spawn in a new map. Oher way u stay in the cage till you solve it.

The problem is that I change the map only in the sidewindow. It is possible to change the map in my main window??

**Comment by jonnytest1** [comment]
you need to give your second coWEbsite the apiPermissions and then call WA.loadRoom("room url")

**Comment by moufmouf** [comment]
`WA.nav.goToRoom` will be part of the next release (in 2 weeks!) 

In the meantime, you could try something like described here: https://stackoverflow.com/questions/1037839/how-to-force-link-from-iframe-to-be-opened-in-the-parent-window

**Comment by Razielruss** [comment]
Thank you for help. I sovled it with the function window.parent.location.href="URL". It works.
