### ISSUE TITLE
Can hear background music

### ISSUE THREAD

**Issue by Razielruss** [thecodingmachine/workadventure#1234]
Hello

In my tiled Layer I have set the property playAudio with the URL: ../../music/song.mp3, audioLoop: true and audioVolumen:1 but in my map I cant heard my music. When I open the console I get the the warning: "AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page"

How can I resume it in tiled that I can use my song in workadventure ?

**Comment by jonnytest1** [comment]
🤔 assuming a default project setup like over here : https://github.com/Razielruss/Presi/tree/master/music
its much more likely you need to use a path like ./music/music.mp3

**Comment by Razielruss** [comment]
Okay maybe u are right. Workadventure descripe that I have to use a URL not a path. I will try it out.

By the way I use chrome and I have tried it with other browsers like firefox and edge no one works

**Comment by Razielruss** [comment]
Okay I solve it. My Server see only the html folder and the stuff in this folder. All other datas like, music, images are not seen. So I have to push all Datas in my html folder to use it in my map. 

Anyway Thank you for help :)
