### ISSUE TITLE
Buttons on customizing WOKA don't work

### ISSUE THREAD

**Issue by sils** [thecodingmachine/workadventure#1238]
**Steps to reproduce:**

1. Open workadventure in private mode (we're using a self hosted instance from the develop branch, last updated about 2 weeks ago)
2. Enter any name
3. Press continue
4. Click 'Customize your WOKA'
5. Click e.g. the right arrow

**Expected results:**

I can configure the WOKA :)

**Actual results:**

Nothing happens. The following error appears on the console:
```
Uncaught TypeError: n.moveCursorHorizontally is not a function
    at HTMLButtonElement.<anonymous> (CustomCharacterScene.svelte:15)
    at HTMLButtonElement.<anonymous> (index.mjs:245)
```

**Comment by sils** [comment]
(The instance was set up on June 3rd)

**Comment by jonnytest1** [comment]
probably best to merge in at least the next release tag

**Comment by sils** [comment]
@yukiisbored can you do that please?

**Comment by sils** [comment]
Yes, works after update!
