### ISSUE TITLE
Missing warning if Iframe API is not authorized in Iframe

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1241]
If iFrame API is not allowed for a cowebsite (because we are lacking the `openWebsiteAllowApi`), and if the iFrame tries to speak to WA, it would be a good idea to display a warning in the console (to let the developer know something is probably missing.

**Comment by jonnytest1** [comment]
im not sure its a good idea to inject scripts (no matter how little) into a site even without explicit permission
also we cant really inject a script anyways :D  at least not if its cross origin
