### ISSUE TITLE
'bash\r': No such file or directory, front docker image is failing

### ISSUE THREAD

**Issue by Yasamato** [thecodingmachine/workadventure#1253]
Having taken a look at the Dockerfile in [front/Dockerfile](https://github.com/thecodingmachine/workadventure/blob/develop/front/Dockerfile) calling [templater.sh](https://github.com/thecodingmachine/workadventure/blob/develop/front/templater.sh), my bet was that there is a windows newline at L#1:
`#!/bin/env bash`

Having adjust newlines from CRLF to LF and rebuild the front image the docker container is now starting.

Could be related to #1209

**Comment by nolway** [comment]
Fixed.
