### ISSUE TITLE
Second layer object is not using opacity

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1256]
Hi,

I tried to use a second object layer, to add some information on my different zone.

![image](https://user-images.githubusercontent.com/19731340/124257315-8ae15800-db2c-11eb-9cd1-642c781493b6.png)

In tiled, i export the map as an image, so i can share this informational picture to the people that are using this map.

I tried to use opacity to 0 in this specific layer, so it should not be shown on the map.
But the opacity seems to not working as the texts are still shown.

![image](https://user-images.githubusercontent.com/19731340/124257730-ef9cb280-db2c-11eb-8700-d2268a912c02.png)

Do you think you could do something for this bug ?

Having the ability to make a "map of the map" to help people is really usefull for me.

**Comment by jonnytest1** [comment]
have you tried the eye icon to the right of the layer to hide it ?

**Comment by Jacques-Olivier-Farcy** [comment]
Yes i already tried that Jonny
