### ISSUE TITLE
Thumbnails are empty

### ISSUE THREAD

**Issue by fueledbysushis** [thecodingmachine/workadventure#1280]
For some reasons, thumbnails aren't working anymore and don't display anything.
![screencapture-play-staging-workadventu-re-tcm-workadventure-floor0-2021-07-13-11_01_45](https://user-images.githubusercontent.com/11734433/125424170-aaa43adf-bfcb-4a28-9f41-120d7aed5fb4.png)

**Comment by gparant** [comment]
Thanks for you feedback @fueledbysushis. This issue was fixed in our last major version 1.6. Don't hesitate to contact us if this issue persists. 💪
