### ISSUE TITLE
Set a different default Iframe size / specific size to iframes

### ISSUE THREAD

**Issue by LancelotBompard** [thecodingmachine/workadventure#1293]
Hello,

I'm trying to set a default size of 70-80% of the screen width (instead of the default 50 %) for an iframe when using the "openWebsite" property. Or to specify to each Iframe a specific size (e.g: One Iframe would have a default size of 70% screen width and a different Iframe would take only 50%).

Does anyone have an idea on how I could achieve either one of those things ?

**Comment by jonnytest1** [comment]
are you self hosting ?

**Comment by LancelotBompard** [comment]
I believe I do.

**Comment by patlachance** [comment]
> are you self hosting ?

yes we are. any idea how to achieve this?

**Comment by jonnytest1** [comment]
https://github.com/jonnytest1/workadventure/commit/0a0b927aee394547728d0e819e1b33584ec4ceeb#diff-6ddbde0623f3e0b1aba0da34035cc4cdcd91a0c15896bee2063858ffa0ee5603 you cna take a look here for some ideas on the matter
