### ISSUE TITLE
Compute proximity of players to trigger chats

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#13]
Every second, on the backend, we should compute the distance separating players.

If players are close enough (a give number of pixels stored in conf?), then the server should send a message to one of the player to initiate a WebRTC chat.
(beware, the message must not be sent to both players, only to one of them)

Note: a maximum of 3 people only can be contacted.

When someone moves out of range, the server must send a message to both players to close the connection.

This task is only about triggering the message from the server side, not about handing the WebRTC connection.

**Comment by dmaechler** [comment]
Chaud pour cette tâche !

**Comment by moufmouf** [comment]
Closed by #63 
Thanks @dmaechler and @gparant !
