### ISSUE TITLE
website - Integrated websites page -> 500

### ISSUE THREAD

**Issue by bebraw** [thecodingmachine/workadventure#1335]
1. Go to https://workadventu.re/map-building
2. Click "Integrated websites" at the sidebar (url: https://workadventu.re/map-building/website-in-map.md)
3. 500, server error

I would expect to see the documentation instead of the server error.

**Comment by nazimboudeffa** [comment]
It's working actually maybe it was at a time of maintainance

![image](https://user-images.githubusercontent.com/1375686/128753010-bf696a21-bf19-41dc-b5fa-49f32182dbfc.png)

**Comment by bebraw** [comment]
This has been fixed.
