### ISSUE TITLE
Proximity Chats not working (Cannot find user with Id x)

### ISSUE THREAD

**Issue by awesome-michael** [thecodingmachine/workadventure#1351]
I run a workadventure server for testing which is working so far. I can enter the map, walk around, join jitsi rooms etc.
But when I get close to another user where the proximity chat should start I see the circle, hear the sound, sometimes I got the window in the right upper corner with a spinning circle but then nothing happens.
In the console on the one user there is this error message:

```
pushVideoToRemoteUser => 2 Error: While adding media, cannot find user with ID 2
    at SimplePeer.pushVideoToRemoteUser (SimplePeer.ts:390)
    at SimplePeer.sendLocalVideoStream (SimplePeer.ts:431)
    at Array.<anonymous> (SimplePeer.ts:55)
    at set (index.mjs:35)
    at MediaStore.ts:309
```

the other user gets

```
pushVideoToRemoteUser => 2 TypeError: Cannot read properties of undefined (reading 'addTrack')
    at VideoPeer.addTrack (index.js:304)
    at SimplePeer.pushVideoToRemoteUser (SimplePeer.ts:410)
    at SimplePeer.sendLocalVideoStream (SimplePeer.ts:431)
    at Array.<anonymous> (SimplePeer.ts:55)
    at set (index.mjs:35)
    at MediaStore.ts:417
```

Is this a bug or did I misconfigure something?

**Comment by nazimboudeffa** [comment]
Hi, I am new in the project but for the first error message when you look at it in `SimplePeer.ts` it points to a getter that doesn't find your user's userId

```
const PeerConnection = this.PeerConnectionArray.get(userId);
  if (!PeerConnection) {
      throw new Error("While adding media, cannot find user with ID " + userId);
  }
```

Can we try a test together if your server is online or is it in testing mode (self hosting) on `http://play.workadventure.localhost` ?

**Comment by awesome-michael** [comment]
Thanks for the offer to test, unfortunately the instance is currently not available from the public.

I also looked a bit into the code and wondered if the PeerConnectionArray may not get populated. I'm a bit confused because there are no errors logged at the server so I have no clue where to start searching.

**Comment by awesome-michael** [comment]
It was a configuration problem. I used `docker-compose.single-domain.yaml` as template to build my docker-compose file. In this file the TURN_STATIC_AUTH_SECRET environment variable is missing for the back-Container. I added it and now the proximity chats work fine.
The TURN configuration should be fixed in the single-domain example.
