### ISSUE TITLE
Script + Variables Ideas

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1364]
Scripts:
- it would be nice, if one can include multiple scripts in one map (like you could do in an IFrame). The purpose is to have some scripts that apply to multiple maps and then map specific scripts.
- for better fulfilling of above the loading of scripts as modules for a map would also be nice, so we can profit more from TS.
Variables:
- an endpoint to set the variable from an external service via some kind of authentication (Token) would be nice. So one could set a variable to "external managed" and then can interact with external services to set variables on the map without allowing a user to change it.

**Comment by jonnytest1** [comment]
include this script like this:

`https://github.com/jonnytest1/workadventuremap/blob/master/scripts/index.js?url=./yourmodulescript.js`

**Comment by jonnytest1** [comment]
you cna interact with external services by creating a  websocket connection 
alterantively 

create and endpoint like this :

```
    @GET('message/:data/message.html')
    async onmessage(req: HttpRequest, res: HttpResponse) {
        const data = JSON.parse(base64url.decode(req.params.data));
        console.log(data.type);
        const responseJson = await messageHandlers[data.type]({ ...data.data }, req);
        const jsonStr = JSON.stringify(responseJson);
        res.set('Content-Type', 'text/html')
            .send(`<script>const jsonV=${jsonStr};window.parent.postMessage({data:jsonV,type:"iframeresponse"},"*")</script>`);
    }
```

in the backend


and a frontend like :
make the backend set a uuid as cookie for identifying users
```
let cookieCheckPromise = new Promise(async (res, thr) => {
    const iframe = document.createElement('iframe');
    window.addEventListener('message', messageEvent => {
        let eventData = messageEvent.data;
        if(eventData.type === 'iframeresponse') {
            res();
            iframe.remove();
        }
    });

    iframe.src = `${backendDomain}/mapserver/rest/message/${btoa(JSON.stringify({ type: 'method', ...args}))}/message.html`;
    document.body.appendChild(iframe);
});
```

**Comment by Lurkars** [comment]
I will take a look at your first reply. Regarding your second comment. I am talking explicit about the variable (state) feature, so I want like an endpoint to trigger an authorized `WA.state.saveVariable` from an external (trusted) service and the actual call in frontend by a user should be forbidden. (I am not talking about general talking with external service from scripting api.) 

Simple use case would be my [TicTacToe](https://github.com/Lurkars/wa_maps/tree/main/tictactoe) game, where the gamestate could be handled only by external service (to avoid cheating for example).

**Comment by jonnytest1** [comment]
> I will take a look at your first reply. Regarding your second comment. I am talking explicit about the variable (state) feature, so I want like an endpoint to trigger an authorized `WA.state.saveVariable` from an external (trusted) service and the actual call in frontend by a user should be forbidden. (I am not talking about general talking with external service from scripting api.)
> 
> Simple use case would be my [TicTacToe](https://github.com/Lurkars/wa_maps/tree/main/tictactoe) game, where the gamestate could be handled only by external service (to avoid cheating for example).

well if you have your own backend you can set up authentication as you please and handle gamestate as well

**Comment by Lurkars** [comment]
yeah in the end you're right, if I have server anyway I can ignore the state API and build a onVariableChange my own too.

**Comment by Lurkars** [comment]
Okay, I'll close this.
I added the following line into iframe.html `script.type = "module";` afterwards, I can simply use typescripts import function. This solves my multiple scripts approach.
And @jonnytest1 is write, if I implement a third-party-logic for game/logic, I can implement my own state there and don't need to rely on variables.
