### ISSUE TITLE
Initial Commit - Deploy fails

### ISSUE THREAD

**Issue by edomedicks** [thecodingmachine/workadventure#1390]
I've tried installing the template repository to github as described here: https://workadventu.re/map-building
No idea why, 
The deploy job fails in the Build Scripts part:

Run npm run build
  npm run build
  shell: /usr/bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX

> workadventure-map-starter-kit@1.0.0 build /home/runner/work/OtherLand/OtherLand
> webpack --config webpack.prod.js

assets by status 273 bytes [cached] 1 asset
./src/index.ts 506 bytes [built] [code generated] [3 errors]

ERROR in /home/runner/work/OtherLand/OtherLand/src/index.ts
./src/index.ts 7:3-7
[tsl] ERROR in /home/runner/work/OtherLand/OtherLand/src/index.ts(7,4)
      TS2339: Property 'room' does not exist on type 'WorkAdventureApi'.

ERROR in /home/runner/work/OtherLand/OtherLand/src/index.ts
./src/index.ts 8:23-25
[tsl] ERROR in /home/runner/work/OtherLand/OtherLand/src/index.ts(8,24)
      TS2339: Property 'ui' does not exist on type 'WorkAdventureApi'.

ERROR in /home/runner/work/OtherLand/OtherLand/src/index.ts
./src/index.ts 11:3-7
[tsl] ERROR in /home/runner/work/OtherLand/OtherLand/src/index.ts(11,4)
      TS2339: Property 'room' does not exist on type 'WorkAdventureApi'.

webpack 5.31.2 compiled with 3 errors in 2106 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! workadventure-map-starter-kit@1.0.0 build: `webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the workadventure-map-starter-kit@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-08-24T09_28_10_653Z-debug.log
Error: Process completed with exit code 1.

**Comment by alexandria-p** [comment]
Hi, the template repo has recently been updated to fix a build issue (package.json updated to latest API ref). Try pulling the latest from main/master and run it again :)

**Comment by moufmouf** [comment]
Closing this, since this is indeed fixed by https://github.com/thecodingmachine/workadventure-map-starter-kit/pull/21
