### ISSUE TITLE
[Doc] Write a specific section for variables in the documentation

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1409]
Variables are very much used in the scripting API but also in the "extra" package.
Right now, they are described only in the api-state.md doc.

We should put the definition of variables in the main documentation.

**Comment by kno10** [comment]
I tried using them, but I only get "The iFrame sent a message of type "setVariable" but there is no service configured to answer these messages." - is there some additional configuration necessary?
