### ISSUE TITLE
The camera is still active even if not enabled

### ISSUE THREAD

**Issue by ThibBal** [thecodingmachine/workadventure#1412]
Hi everyone!

Since the update released these last days, an issue has reappeared: my camera is still activated even if I've disabled it via the bottom right button.

The problem was released a few months ago (but was still happening once in a while), today it's everytime. I can tell because, on MacBook, we have a green light next to our camera that indicate that.

Good luck for solving that!

**Comment by moufmouf** [comment]
Damn it!

We indeed introduced a regression when switching the way disabled tracks are handled.
It should still work in Firefox, but not in Chrome.

What we need to do:

In Firefox:

- We need to use the "disabled" property of MediaStreamTrack. It's the only way. "stop()"ing the track works but the next call to  getUserMedia will prompt for camera authorisation again.

In other browers:

- The "disabled" property of MediaStreamTrack does not turn off the light of the webcam. We need to "stop()" the MediaStreamTrack on the video tracks, then do a new call to getUserMedia to enable it again. This will not prompt for authorisation.

**Comment by moeffju** [comment]
This prevents me from using WA on rC3 2021. I have multiple webcams and use OBS to provide a virtual device. In Firefox, WorkAdventure insists on grabbing the first webcam found, which is the built-in webcam of the laptop and never the one I want. So I tried using Edge which allows the user to define the default webcam device, However now, if I start OBS first, it holds the camera and WA fails when enumerating devices and complains that the camera access was denied; if I start WA first, then it holds on to the main camera which prevents OBS from using it.
Is there some workaround?
