### ISSUE TITLE
yarn install fails when run from docker-compose

### ISSUE THREAD

**Issue by axfelix** [thecodingmachine/workadventure#1433]
```
[3/4] Linking dependencies...
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.3.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-react@^7.20.0".
warning "eslint-config-airbnb-typescript > eslint-config-airbnb@18.2.0" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
warning " > eslint-plugin-sonarjs@0.5.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
error Could not write file "/var/www/messages/yarn-error.log": "EACCES: permission denied, open '/var/www/messages/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/var/www/messages/node_modules'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'front' failed to build: The command '/bin/sh -c yarn install && yarn proto' returned a non-zero code: 1
```

Anything I'm missing? Thanks!

**Comment by moufmouf** [comment]
Hey @axfelix ,

It sounds like a right issue between your containers and your hard disk. Probably linked to the way Docker is setup.

I think people have had the same kind of problems in the past with Windows. What OS are you using? And how did you install Docker?

**Comment by axfelix** [comment]
Hmmm, this is on a pretty stock Ubuntu 18.04 I think, already running Jitsi via docker...

**Comment by tabascoeye** [comment]
according to https://github.com/thecodingmachine/workadventure/issues/738, you still need to swap the two lines in the Dockerfile for the "front" container:
https://github.com/thecodingmachine/workadventure/blob/develop/front/Dockerfile#L2-L3

If that works for you, we should post that as a PR because so many people reported it already

**Comment by axfelix** [comment]
Yup, the fix from that issue worked, thank you!

**Comment by moufmouf** [comment]
The fix was breaking my setup, but hopefully, I found a way that will make it work for everybody:

https://github.com/thecodingmachine/workadventure/pull/1457
