### ISSUE TITLE
Silent zones next to Jitsi don't work when exiting Jitsi

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1454]
If a silent zone is adjacent to a Jitsi zone, when leaving the Jitsi zone, the user is no more in "silent" mode.

This is because, when exiting Jitsi, we set the silent zone to false.

http://github.com/thecodingmachine/workadventure/blob/01bd36ca3f67faddd46849190ee38825d6de9261/front/src/Phaser/Game/GameScene.ts#L1815-L1821

We should instead have a look at the properties, and set the silent mode accordingly.

**Comment by Lurkars** [comment]
can this be related to #1440 too? It's seems that some properties like silent, playAudio are not applied correctly when not simple walked over.
