### ISSUE TITLE
openWebsiteWidth property not working

### ISSUE THREAD

**Issue by LancelotBompard** [thecodingmachine/workadventure#1462]
Hello,

I noticed recently the documentation was updated with a new property allowing us to control the width of the iframe ( used with the "openWebsite" property). 

According to the documentation I'm supposed to add a property and set the name of that property to "openWebsiteWidth" with a value of type "number" (between 0 and 100). Using Tiled I've tried that but the type number does not exist (from Tiled at least). I've tried modifying the value of the "type" in the json file with the value "number" as said in the documentation, but nothing work, I always get my iframe to open with 50% of the window width.

Here is the part of the json where I tried using the new property, does anyone see anything that could break and explain me where I did wrong ?

`"height":61,
         "id":61,
         "name":"IFrameWithEightyWidth",
         "opacity":1,
         "properties":[
                {
                 "name":"openWebsite",
                 "type":"string",
                 "value":"https:myWorkingUrl.com"
                }, 
                {
                 "name":"openWebsiteWidth",
                 "type":"number",
                 "value":80
                }],
         "type":"tilelayer",
         "visible":true,
         "width":89,
         "x":0,
         "y":0
        }, `

**Comment by tabascoeye** [comment]
no type has to be "string". It's just that the string content needs to be a number between 0 and 100 getting interpreted as %.

So 

"height":61, "id":61, "name":"IFrameWithEightyWidth", "opacity":1, "properties":[ { "name":"openWebsite", "type":"string", "value":"https:myWorkingUrl.com" }, { "name":"openWebsiteWidth", "type":"string", "value":"80" }], "type":"tilelayer", "visible":true, "width":89, "x":0, "y":0 }, 

should work
