### ISSUE TITLE
same-map exits no longer working

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#1500]
I noticed that "exitUrl" no longer works with start point on the same map.

The address-bar in the browser even shows the correct URL with "map.json#start-layer-name" but the startpoint is the default start layer of the map.

When hitting "return" on the addressbar again, to realod using the full URL however, the correct startpoint is used

**Comment by gparant** [comment]
Hi @tabascoeye 

This issue was already fixed and push on develop branch. We wait some final test to deploy the next version on production (1.5.3).

Thanks for your feedback 🚀

**Comment by tabascoeye** [comment]
I though "play.staging.workadventu.re" _is_ the develop branch?!

**Comment by gparant** [comment]
No, is a master branch.

**Comment by tabascoeye** [comment]
Is the develop branch being deployed public? I know about play.test.workadventu.re but it uses a self-signed cert with HSTS which brwosers _really_ don't like
