### ISSUE TITLE
Help with sendChatMessage and onChatMessage

### ISSUE THREAD

**Issue by TeflonAntihaft** [thecodingmachine/workadventure#1507]
Hi,
I'm currently writing a simple passphrase-based dialog skript for a event at my university and currently struggle with some aspects of the chat message system. I hope someone her can help me.

Firstly how does the 'author' system work for sendChatMessage? If i issue a chain of messages with different fictional authors to the chat box via, let's say, a block in a function, they are correctly displayed as different messages, but lumped together as if the were all said by the first fictional author, effectively ignoring the author property of most messages. Is this behaviour intended? Because this problem also persits between calles to sendChatMessage at different times, e.g. on different event callbacks, as long as no 'real' player has said something in the chat. 

Secondly how is the event WA.chat.onChatMessage() supposed to work? I'm very inexperienced with JavaScript but when using this function on the top level of my script file with a pre-defined function wich takes an string argument, i could not get the callback to trigger, no matter what i did. Could sombody provide a simple working example on how to use this callback? My code below, nor the example one-liner from the wiki, does not seem to work at all, so maybe i'm missing something. 

```
WA.chat.onChatMessage(parseChat);

function parseChat(message) {
    if (!crewAwaitAnswer) return;
    var l_msg = message.toLowerCase();

    if (l_msg.includes('krach')) {
        print_station2();
    } else if (l_msg.includes('katz')) {
        print_station5_opt();
    } else if (l_msg.includes('anker')) {
        print_station5();
    } else if (l_msg.includes('goessling')) {
        print_station7();
    }
}

```
Thanks in advance for any help!
-- David

Edit: For context: Im using a local map for development and debugging, but i can't image why that should be aproblem.

**Comment by moufmouf** [comment]
Hey David!

> Firstly how does the 'author' system work for sendChatMessage? If i issue a chain of messages with different fictional authors to the chat box via, let's say, a block in a function, they are correctly displayed as different messages, but lumped together as if the were all said by the first fictional author, effectively ignoring the author property of most messages. Is this behaviour intended? 

Nope, this is not intended. I think it is the first time we are reported this issue. We will look into it!

For your second question, it should work. Could you try to wait for the whole page being loaded using an event listener first? Something like:

```javascript
window.addEventListener('load', () => {
WA.chat.onChatMessage(parseChat);

function parseChat(message) {
    if (!crewAwaitAnswer) return;
      var l_msg = message.toLowerCase();

      if (l_msg.includes('krach')) {
          print_station2();
      } else if (l_msg.includes('katz')) {
          print_station5_opt();
      } else if (l_msg.includes('anker')) {
          print_station5();
      } else if (l_msg.includes('goessling')) {
          print_station7();
      }
  }
})
```

**Comment by moufmouf** [comment]
> Firstly how does the 'author' system work for sendChatMessage? If i issue a chain of messages with different fictional authors to the chat box via, let's say, a block in a function, they are correctly displayed as different messages, but lumped together as if the were all said by the first fictional author, effectively ignoring the author property of most messages. Is this behaviour intended?

Ok, the problem seems wider than just with the API. I've just realized that sometimes, in the chat between humans, we attribute the message to the wrong person. I'm currently working on a fix for this.
