### ISSUE TITLE
Layout: Audiocontrols block global messages

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#1510]
See picture for the problematic effect:
<img width="1279" alt="Screenshot 2021-10-08 at 00 09 34" src="https://user-images.githubusercontent.com/111893/136469561-4e74d6a6-e7f7-4c04-86b3-0f7bedf2580d.png">

Some CSS wizard with a good idea to fix?

**Comment by tabascoeye** [comment]
bump. Maybe already fixed, but I think global messages should have highes z-index of all?

**Comment by gparant** [comment]
Thanks for your feedback 💪

**Comment by nolway** [comment]
All UI component z-indexes are going to be changed in this pr : https://github.com/thecodingmachine/workadventure/pull/1620 
This solves this problem :ok_hand:
