### ISSUE TITLE
Feature Request: Possibility to mute mic/video on locking the screen

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1536]
The mic and video is still active when you lock your screen.
For privacy reasons that should be muted on locking the screen.

**Comment by gparant** [comment]
Hi @buenni86 unfortunately I think that we cannot use lock screen operation in a web browser and define a rule that switch off cam and mic when your computer is locked.
In the future we want to develop a native application cross OS and in this app we could use many options of the OS and this rule will be implemented.

Thanks for your feedback 🚀
