### ISSUE TITLE
Feature Request: More than 4 people in a bubble

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1537]
It would be awesome to be able to increase the number of people able to communicate in a bubble to 5 or 6.
Maybe make it configurable in the dashboard?

**Comment by flonix8** [comment]
@buenni86 
If you want to go over the 4 person limit, you absolutely can as soon as you run your own instance of workadventure. I haven't done any thorough testing, but setting the environment variable `MAX_PER_GROUP` to `6`  on the `front` container should technically work.
However, I think @moufmouf concerns are to be taken seriously. Peer-to-peer doesn't scale very well and the experience correlates closely with the participants network and compute resources.

**Comment by pizkaz** [comment]
Indeed, we tested that - specifically @tabascoeye did - and IIRC, more than six people in a bubble turn client devices into frying pans in the blink of an eye. I think the default limit of four makes sense if you don't want to (effectively) exclude everyone with a Laptop >2 years of age and/or bad internet connection.

**Comment by tabascoeye** [comment]
yes. Until @moufmouf implemented using an SFU, just stick to 5 or lower direct connections to lower your headaches

**Comment by gparant** [comment]
Hi, yes we want to implement SFU or MCU in the future to improve circle discussion and increase the number or user.
This subject is in our backlog and we want to start this beginning of the year 🚀
