### ISSUE TITLE
The iframe is in front of the main menu

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#1538]
😅

![image](https://user-images.githubusercontent.com/858611/138605100-797b5965-5aef-462e-9db1-9bd69b9065cf.png)

**Comment by Lurkars** [comment]
@moufmouf Is this already solved in latest dev? I cannot reproduce (Tested in Firefox and Chrome).

**Comment by jacquesbh** [comment]
Seems ok to me!

![image](https://user-images.githubusercontent.com/858611/146918049-b036e5f9-1cc3-4ab2-b1e2-1c2b5b0045a5.png)
