### ISSUE TITLE
Problems with Phaser

### ISSUE THREAD

**Issue by Carabas** [thecodingmachine/workadventure#1548]
While installing the newest version of game via Docker, I can see lines
`maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/Sound/Sound.d.ts(1,22): error TS2503: Cannot find namespace 'Phaser'.`
`maps_1           | node_modules/@workadventure/iframe-api-typings/Api/iframe/room.d.ts(2,32): error TS2307: Cannot find module '../../Phaser/Map/ITiledMap' or its corresponding type declarations.`
... in the logs, and connecting to the game leads to an empty (dark) map. Is that related? How can I get rid of these Phaser errors?

**Comment by moufmouf** [comment]
Hey @Carabas !

Are you using the Docker image "workadventure/front" ?
Or are you using the "docker-compose.yml" at the root of the workadventure project that is building WorkAdventure from NodeJS?

Could you share your docker-compose file with us (if you are using one) so I can understand where to look?

**Comment by Carabas** [comment]
Hey @moufmouf,
I simply cloned the repo, and I use the `docker-compose.single-domain.yaml` provided at the root project, after changing variables values according to my setup. Does one have to use the Docker image "workadventure/front" instead ?

**Comment by Carabas** [comment]
I also add that I had to manually `npm install` the genetic-type-guard module in the maps container, as there were more than 20 errors related to it in the logs.

**Comment by unilogica** [comment]
Same problem here. Trying `yarn add genetic-type-guard` at docker-compose.yaml solve 26 errors, but I no lucky with Phaser

**Comment by moufmouf** [comment]
If I read correctly, this error happens on the "map" container.
Don't worry about it. It is of no use and I just need to remove the old code that lives there.

I'll keep the issue open until I manage to tidy that.
