### ISSUE TITLE
Erroneous example in API reference on webpage

### ISSUE THREAD

**Issue by fabiankrieg** [thecodingmachine/workadventure#1557]
I hope this is the right place for pointing this out. I got zero JavaScript experience but decided to give the UI examples you provide [here](https://workadventu.re/map-building/api-ui.md) a go. Specifically, the code below:

```js
let helloWorldPopup;

// Open the popup when we enter a given zone
helloWorldPopup = WA.room.onEnterZone('myZone', () => {
    WA.ui.openPopup("popupRectangle", 'Hello world!', [{
        label: "Close",
        className: "primary",
        callback: (popup) => {
            // Close the popup when the "Close" button is pressed.
            popup.close();
        }
    });
}]);

// Close the popup when we leave the zone.
WA.room.onLeaveZone('myZone', () => {
    helloWorldPopup.close();
});
```

When running things I figured that the brackets are wrong. For me '}}])});' did work, though I couldn't get the example to run in the end, probably due to other issues.

If this is the wrong place to point to such things please let me know where I should put it.

**Comment by gparant** [comment]
Hi @fabiankrieg do you have any error in your web console?

**Comment by fabiankrieg** [comment]
Hi @gparant , thanks for asking. The original example above did raise a syntax-error due to the wrongly set brackets. We also managed to get the pop-ups to work at some point. I think the other major problem was that we didn't put the rectangles to the floor layer.

I don't know whether you had the chance to check the docs, but on my end the issue is resolved. Thanks!

**Comment by gparant** [comment]
Ok, thanks @fabiankrieg, don't hesitate if you have any other questions 🚀
