### ISSUE TITLE
Still on call even if not…

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#1569]
I got a strange behavior this morning.

I (Jacko) was talking with David and then we split up.
And like magic his "square" showed up again, I got the sound, not the video.

![image](https://user-images.githubusercontent.com/858611/142171158-9a1c581c-6889-406f-aa34-71780fef9ba1.png)

It happened twice today already.

**Comment by gparant** [comment]
Thanks for your feedback, we deployed a new version of WebRtc conversation. This new version should fix this problem. Thanks for you feedback 💪
