### ISSUE TITLE
Popup window

### ISSUE THREAD

**Issue by johnandrewabala** [thecodingmachine/workadventure#1571]
Anyone has a tutorial on youtube how to add / create a popup window.. thank you.

**Comment by Lithimlin** [comment]
You can just use the Popup from the `ActionMessage`:

```ts
/// <reference path="../node_modules/@workadventure/iframe-api-typings/iframe_api.d.ts" />

import { ActionMessage } from '@workadventure/iframe-api-typings/Api/iframe/Ui/ActionMessage';

function foo() {
  WA.ui.openPopup(
    "my_popup", // name of the rectangle object (see below)
    "Foo message to be shown.", // Popup message
    [] //empty array for no buttons
  );
}

function bar() {
  WA.ui.openPopup(
    "my_popup", // name of the rectangle object (see below)
    "Bar message to be shown.", // Popup message
    [
      {
        label: "Button1", // Text of button 1
        className: "primary", // css class, here for primary buttons
        callback: (p) => {} //place for a callback
      }, {
        label: "Button2", // Text of button 2
        className: "normal", // css class, here for normal buttons
        callback: (p) => {} //place for a callback
      },
    ]
  );
}
```

In Tiled, you need to also create a rectangle object within the `floorLayer`.

**Comment by johnandrewabala** [comment]
hi, thank you. but im new in scripting. where im going to put this scripts?

**Comment by Lithimlin** [comment]
Try referring to [this tutorial on map scripting](https://workadventu.re/map-building/scripting.md). I'm fairly new to scripting for WA myself unfortunately

**Comment by Jacques-Olivier-Farcy** [comment]
Hi @Lithimlin ,

It seems interesting, do you have an example of map with this script online ?
And also are you on the Discord of WorkAdventure ?

**Comment by Lithimlin** [comment]
Unfortunately not publicly available. I might be able to put a little something together some time but no promises.

And no, I'm not. I wasn't aware one exists.

**Comment by Jacques-Olivier-Farcy** [comment]
The server is here : https://discord.gg/YGtngdh9gt if you want to join us.

**Comment by gparant** [comment]
I close this issue, thanks for your feedbacks 🚀
