### ISSUE TITLE
Hiding a layer in group not working

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1574]
Hi,

When using this in my script :

```
WA.room.onEnterZone(zone1myzoneName, () => {
	WA.room.hideLayer('mylayer');
})
```

If the layer is in a group of layers, it won't work, else it will.
Maybe i need to add the group name ?

**Comment by Lurkars** [comment]
Yes, you need to add group name with dot between.

So GroupName -> LayerName is addressed by `GroupName.LayerName`

**Comment by Jacques-Olivier-Farcy** [comment]
Thanks, i tried this, but it is not working.
My script is here : https://play.workadventu.re/_/global/mapwa.net/static/wa/wacman/script.js
The map is here : https://play.workadventu.re/_/global/mapwa.net/static/wa/wacman/start.json
I tried with the fruits.
In tiled:
![image](https://user-images.githubusercontent.com/19731340/142762042-78323204-b2f9-462f-bbe7-4e9eb39321f6.png)

**Comment by Lurkars** [comment]
Difficult to quick check the map, but you also named the zones fox example  `var zone2bananaName = "fruits/banana";'` since zone is property on layer it is independent from group layer! So check if you really gave the name "fruits/banana" to the zone or use the correct zone name in script!

**Comment by Jacques-Olivier-Farcy** [comment]
thanks, it worked !

**Comment by Jacques-Olivier-Farcy** [comment]
Thanks @Lurkars
