### ISSUE TITLE
Too many "Press SPACE5"

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1575]
Hi,

I was on the https://play.staging.workadventu.re/@/tcm/workadventure/wa-village map and it seems that the pop up never closed when moving around for each case.

![image](https://user-images.githubusercontent.com/19731340/142828340-a583bac7-237d-4a91-b744-e5a93520dbab.png)

**Comment by moufmouf** [comment]
Indeed! We are trying to fix this bug as I speak. Thanks for reporting it @Jacques-Olivier-Farcy  !

**Comment by nolway** [comment]
This bug has been fixed!
