### ISSUE TITLE
Feature Request: player.isInZone

### ISSUE THREAD

**Issue by Lithimlin** [thecodingmachine/workadventure#1577]
Such a function, determining whether a player is inside a zone, would be very helpful for scripting, for example for determining where a player spawned.

**Comment by Jacques-Olivier-Farcy** [comment]
Hi @Lithimlin ,

Nice idea as the WA.player.onPlayerMove(console.log); function only shown coordinate.

**Comment by nolway** [comment]
Hi @Lithimlin ,
We have a subscriber that fires when a user enters or leaves a map layer 😀
https://workadventu.re/map-building/api-room.md#detecting-when-the-user-entersleaves-a-layer

Is this what you are looking for?

**Comment by Lithimlin** [comment]
Hi @nolway,
no, this is not what I am looking for. I am already aware of those.
I'm specifically interested in a way to check whether or not a player is already inside of a zone/layer. For example, when the player spawns, they do not trigger `onLayerEnter()`. It is thus not helpful in determining where a player spawns. `onPlayerMove()` is similarly useless until a player moves and much more complicated.

**Comment by gparant** [comment]
Hi @Lithimlin I think that we will fix the problem of onLayerEnter when user spawns, but with function onEnterLayer and onLeaveLayer, you could define if the user is in layer or you could go in the future and define global variable to stock the route of all users and use it in your script.

I will add this fix in our issue. Thanks for your feedbakc 💪 🚀
