### ISSUE TITLE
Store start layer in lastRoomUrl

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1587]
Currently the startLayer (hash value) is not stored in lastRoomUrl. I think it was before, anyways I think it will be useful if you quit a windows, that at least you start where you started before.

Currently this issue affects me when using OpenID, because of the redirect, lastRoomUrl is always used and I am completely unable to start direct on a different layer, because the hash always gets discarded.

**Comment by moufmouf** [comment]
:+1:

Ping @gparant
