### ISSUE TITLE
CORS Error because of http://localhost returned by pusher

### ISSUE THREAD

**Issue by cyb3rwr3ck** [thecodingmachine/workadventure#1596]
Hi there, 
we have deployed an instance on a publicly reachable server. After the build is finished the page errors with a network error caused by a CORS issue following an request to the pusher url. If we overwrite CORS via a browser plugin the maps is loaded correctly and is fully usable. Any idea how to debug this? 
 
![screen](https://user-images.githubusercontent.com/6362497/143722704-e8b41dca-7b05-446a-bad1-7e37bb05db80.png)
e

**Comment by moufmouf** [comment]
Thanks, this should be fixed by https://github.com/thecodingmachine/workadventure/pull/1609
