### ISSUE TITLE
Error message in console

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1613]
Hi,

Uncaught Error: Unexpected batch message type onmessage RoomConnection.ts:181 RoomConnection.ts:181:30
    onmessage RoomConnection.ts:181
   
It seems to be from these lines in my script:

```
var player = {
	//score: 0,
	x: 0,
	y: 0,
}
WA.player.onPlayerMove( e => {
			player.x = e.x
			player.y = e.y
			WA.state.saveVariable('player', player)
		});
```

**Comment by moufmouf** [comment]
Merci Jacques pour ce retour. Bug corrigé.
Il est du aux variables déclarées "readableBy".

Sera déployé dans la prochaine version!

Entre temps, vous pouvez simplement retirer la propriété "readableBy" de vos variables.
