### ISSUE TITLE
documentation for allowApi seems wrong

### ISSUE THREAD

**Issue by jonnytest1** [thecodingmachine/workadventure#1617]
the documentation at https://workadventu.re/map-building/website-in-map.md says 

> If you are planning to use the WorkAdventure scripting API inside your iframe, you need to explicitly allow it, by setting an additional allowApi property to true.

the GameMapPropertiesListener only checks for GameMapProperties.OPEN_WEBSITE_ALLOW_API which equals openWebsiteAllowApi

(GameMapPropertiesListener.ts#71)

**Comment by moufmouf** [comment]
Ping @nolway

**Comment by nolway** [comment]
The allowApi is for the embed website and the GameMapPropertiesListener for the CoWebsite who will be open by a space key trigger. Isn't the same thing but I understand the names are a bit confusing.
