### ISSUE TITLE
An error occurred while loading resource

### ISSUE THREAD

**Issue by Youngbokz** [thecodingmachine/workadventure#1619]
Hello. 
I have this error message. I am in local I test with Mamp. I do not see where the problem comes from. Can you help me?

**Comment by moufmouf** [comment]
Do you have an URL of the resource that fails to load? Maybe you could send a screenshot and also a link to your map?

**Comment by Youngbokz** [comment]
Hello thank you for you answer. 

here s the URL 

https://play.workadventu.re/_/hm15t5rncnf/localhost:8888/360wellness-fun-office/map.json <https://play.workadventu.re/_/hm15t5rncnf/localhost:8888/360wellness-fun-office/map.json>

I read that i need to create a git repository ?

**Comment by moufmouf** [comment]
Hey @Youngbokz ,

The URL you sent refers to a map hosted on your computer (you can see that from the "localhost" part) so there is no way for me to test this.

Indeed, you need to create a GIT repository to make the map available to others. If you haven't done so yet, you could watch the video I made explaining the process here: https://workadventu.re/map-building/

**Comment by gparant** [comment]
@Youngbokz thanks for your feedback, don't hesitate to tell us if you have any questions 🚀
