### ISSUE TITLE
rxjs in iframe api

### ISSUE THREAD

**Issue by jonnytest1** [thecodingmachine/workadventure#1622]
if a script api user wants to handle re - occurring events they can use Observables if they were exported (might be an idea)

alternatively I'd recommend writing the scripting api with callbacks instead of Subjects to not needlessly bring in dependencies and increase the script size

**Comment by moufmouf** [comment]
Well, we cannot really remove Subjects from the scripting API now. It would be a huge BC break. So there is nothing we can do for the script size without BC breaks.

So maybe we should consider the first option: exporting Observables?

**Comment by gparant** [comment]
Thanks for your feedback @jonnytest1 🚀
