### ISSUE TITLE
Properly document meta properties of maps

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1630]
Looking at the code, I realize there are a number of properties we never really documented:

- mapName
- mapDescription
- mapCopyright
- tilesetCopyright
- mapLink

We should definitely document those correctly in /docs

See https://github.com/thecodingmachine/workadventure/pull/1626

Also, `mapLink` is pointing to the map instead of the Github directory in a number of demo maps. We need to fix this.

**Comment by tabascoeye** [comment]
`mapLink`still needs to be added once #1626 is merged
