### ISSUE TITLE
server.tld/_/global/..... becomes server.tld/_/undefined/..... on map change

### ISSUE THREAD

**Issue by onkeloki** [thecodingmachine/workadventure#1631]
i created a wa-world made of several .json map files.
since i have installed the latest server, i noticed that the string 'global' in url becomes 'undefined' 

i can reproduce it on the https://play.staging.workadventu.re/ server

**Comment by moufmouf** [comment]
Holy cow!

You are perfectly right.
We'll take a look at it ASAP. Thanks for reporting the issue.

**Comment by moufmouf** [comment]
@onkeloki Could you confirm that the error is happening on a `exitSceneUrl` property with an absolute path to another map?

I'll definitely fix this, but please be aware that the `exitSceneUrl` property is deprecated and that you should instead use the `exitUrl` property (see https://workadventu.re/map-building/entry-exit.md#defining-exits)

**Comment by moufmouf** [comment]
Closed in #1634

**Comment by onkeloki** [comment]
you are right it was on:
`exitSceneUrl : othermap.json#anchor`

(with relative path to json file in same folder)

**Comment by moufmouf** [comment]
Yes, it is fixed and will be deployed in next release (probably next week!)
