### ISSUE TITLE
Looking for info on implementing Mumble Support

### ISSUE THREAD

**Issue by hellerbarde** [thecodingmachine/workadventure#1635]
I am evaluating implementing mumble (https://www.mumble.info/) support for workadventure, but I'm not sure how deeply jitsi meet is integrated and thus how difficult or impossible that endeavor would be. 

Any input?

**Comment by moufmouf** [comment]
Hey @hellerbarde ,

I've never tested Mumble but.... it does not seem web-based to me.
Integration in WorkAdventure happens through iframes.

Is there a webpage for Mumble that can be embedded in an iframe?

**Comment by tabascoeye** [comment]
There is a web-client:
https://github.com/Johni0702/mumble-web

and a node-JS client implementation:
https://github.com/Rantanen/node-mumble  (but "not maintained"!)

So it should be doable. Minimum viable product would likely be using an `openWebsite` on a public mumble-web client and allowing microphone usage with `openWebsitePolicy`

**Comment by hellerbarde** [comment]
The fact that jit.si is integrated via iframe is a shame. The whole idea about the mumble integration would have been to always be connected, but not join any rooms until you get close to a group, to remove the connection delay. But it sounds like that is probably not going to be a simple thing to do.

**Comment by gparant** [comment]
Thanks @tabascoeye, I will add this potential integration in our improvement feature.

@hellerbarde Yes, today we want to stay in the philosophy where the user must to be inside of other player to start a bubble discussion and don't have possibility to listening meeting before. But your idea is very interesting, thanks for your feedback 💪
