### ISSUE TITLE
Stale room on pusher after unprivileged user access

### ISSUE THREAD

**Issue by albanbruder** [thecodingmachine/workadventure#1646]
Scenario: At our organization we have integrated a small back office allowing us to have shorter room URLs and member authentication.

If a user connects a room is created in the pusher: https://github.com/thecodingmachine/workadventure/blob/8a96ff8ee4866a1ed80a786ec96b43fded3b5663/pusher/src/Controller/IoSocketController.ts#L243

If the user is not allowed to connect to the room pusher responds with an error and closes the websocket connection:
https://github.com/thecodingmachine/workadventure/blob/8a96ff8ee4866a1ed80a786ec96b43fded3b5663/pusher/src/Controller/IoSocketController.ts#L268-L282

It seems like in the provided case that close handler is never called such that the empty room is never deleted. If I query the `/dump` endpoint on the pusher I get the following data:

<details>
  <summary>data returned by /dump endpoint of the pusher</summary>
  
  ```json
    {
        "http://localhost/@/org/world/room": {
            "roomUrl": "http://localhost/@/org/world/room",
            "socketListener": {
            "rooms": {
                "http://localhost/@/org/world/room": "~http://localhost/@/org/world/room"
            }
            },
            "versionNumber": 1,
            "isClosing": false,
            "listeners": [],
            "tags": ["moderator"],
            "policyType": 3,
            "positionNotifier": {
            "roomId": "http://localhost/@/org/world/room",
            "zoneWidth": 320,
            "zoneHeight": 320,
            "socketListener": "~http://localhost/@/org/world/room~socketListener",
            "zones": []
            },
            "backConnection": {
            "_readableState": {
                "objectMode": true,
                "highWaterMark": 16,
                "buffer": { "head": null, "tail": null, "length": 0 },
                "length": 0,
                "pipes": [],
                "flowing": true,
                "ended": false,
                "endEmitted": false,
                "reading": true,
                "sync": false,
                "needReadable": true,
                "emittedReadable": false,
                "readableListening": false,
                "resumeScheduled": false,
                "errorEmitted": false,
                "emitClose": true,
                "autoDestroy": true,
                "destroyed": false,
                "errored": null,
                "closed": false,
                "closeEmitted": false,
                "defaultEncoding": "utf8",
                "awaitDrainWriters": null,
                "multiAwaitDrain": false,
                "readingMore": false,
                "decoder": null,
                "encoding": null
            },
            "_events": {},
            "_eventsCount": 3,
            "call": { "next_call": { "next_call": null, "requester": {} } },
            "finished": false,
            "reading": true,
            "read_status": null,
            "received_status": null
            }
        }
    }
  ```
</details>

The room gets deleted if a user with access to the room connects and disconnects again. But in the meantime the room will not receive any updates by calling `/room/refresh`.

**Comment by moufmouf** [comment]
Hey @albanbruder ,

Congrats for developing your own admin to have short URLs!
Thanks a lot for the feedback, I'll take a look.

**Comment by moufmouf** [comment]
Hey @albanbruder ,

This should be closed by #1659. Could you let me know if your issue is fixed?

**Comment by albanbruder** [comment]
Hey @moufmouf,

first of all, thank you for your response!

The room seems to be only set if the admin api returns an 403 error. See: https://github.com/thecodingmachine/workadventure/blob/develop/pusher/src/Controller/IoSocketController.ts#L269-L282

In cases where the pusher throws an error (e.g: user is not allowed to access the room) the room property is not set on the websocket object: https://github.com/thecodingmachine/workadventure/blob/develop/pusher/src/Controller/IoSocketController.ts#L364-L389

As a result the room still exists with no members and stale information.

**Comment by moufmouf** [comment]
True. Let me fix that again....

**Comment by albanbruder** [comment]
This resolved the issue. Thanks a lot!
