### ISSUE TITLE
Limit /metrics endpoint access

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#165]
Currently, the /metrics access point is public.
We might want to restrict it to the local network (or to provide some sort of credentials to Prometheus if this is possible)

**Comment by Lithimlin** [comment]
Are there any updates on this?
I'd like to limit the access to my metrics as well as put them on a different port (9100). Any ideas on how to accomplish this?
Being able to direct them to port 9100 would be enough already as I can do the rest with firewalling.

I tried adding another entry point to traefik (for now just for testing) but I get a bad gateway when attempting to connect to it.
