### ISSUE TITLE
Changing email in back office

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1656]
Hi,

I tried to change my email in the backoffice, but when i press update information, the button turn indenefinately.
![update](https://user-images.githubusercontent.com/19731340/146577591-446ee99c-561f-443f-a620-a89c839bf979.gif)

**Comment by moufmouf** [comment]
@nolway , could you take a look at that?

**Comment by gparant** [comment]
Hi @Jacques-Olivier-Farcy, a fix have pushed and will be deployed with new version. Thanks for your feedback 🚀
