### ISSUE TITLE
Feature Proposal: Queue for admin messages

### ISSUE THREAD

**Issue by albanbruder** [thecodingmachine/workadventure#1666]
As part of https://github.com/thecodingmachine/workadventure/pull/1665 I thought about the current handling of admin messages.
If a user receives more than 1 message while offline, only the most recent message will be displayed because the others get overwritten.

You/we could introduce a message queue allowing the user to decide when she/he is done reading a message. Two if the interface options that I have in mind:

![Screenshot 2021-12-21 at 13-43-57 WorkAdventure](https://user-images.githubusercontent.com/36596731/146932979-5f524486-abd8-43c5-886a-552368d2caab.png)

![Screenshot 2021-12-21 at 13-46-35 WorkAdventure](https://user-images.githubusercontent.com/36596731/146933008-2e35935b-e647-4157-b6c4-213942534e7e.png)
 
The first one has the problem that space is limited and even if only an edge case we would then need to paginate messages if the screen is full.

If anyone is interested I could create a PR.

**Comment by tabascoeye** [comment]
PRs welcome ;)

**Comment by moufmouf** [comment]
@albanbruder I very much like your second proposition. If you feel like opening a PR, I'll merge it with pleasure :D
