### ISSUE TITLE
IFRAME opening animation messes with some pages

### ISSUE THREAD

**Issue by dronus** [thecodingmachine/workadventure#1675]
Some pages don't like Workadventure opening the IFRAMEs in an animated fashion.

As the embedded page is loaded, the opening animation of the IFRAME presents the page with some very small width at the beginning. Fast loading pages already have passed the window "load" event at some point of animation, and may trigger a redirect to a mobile page, or just place elements by JS arkwardly. 

So it would be cool to delay the IFRAME loading until the animation has finished. Doesn't look that nice for full responsive pages, though.

**Comment by nolway** [comment]
This is already handle by the new co-website management (it'll be deploy soon in master branch) =)
