### ISSUE TITLE
CORS problem appears since the last version

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1681]
Hi,

This map was working fine…
But today i have the CORS error message.
https://play.workadventu.re/@/hart-city/hart-city/newgame

**Comment by Jacques-Olivier-Farcy** [comment]
Using a wilcard instead of the WorkAdventure domain works :

My new .htaccess :

# Allowing CORS  from domain
# Header set Access-Control-Allow-Origin "https://play.workadventu.re"
Header set Access-Control-Allow-Origin "*"
# Diminution du cache Varnish à 1 seconde
Header add Cache-Control "max-age=1"

**Comment by moufmouf** [comment]
Weird... this makes really no sense. :question: :grey_question:

**Comment by Jacques-Olivier-Farcy** [comment]
isn't it :)

**Comment by gparant** [comment]
@Jacques-Olivier-Farcy I haven't problem on this map, I close this issue. Thanks 🚀
