### ISSUE TITLE
OBS with Virtual Webcam is preventing access to other webcams

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1682]
This happens at least on MacOS (maybe on Windows too).

It seems OBS Virtual webcam changes some settings, making the othe webcam not accessible anymore in WorkAdventure.
Despite that, the webcam remains available in Jitsi, so the issue is not 100% related to OBS it seems.

**Comment by nolway** [comment]
Not reproduced on Windows 11 (firefox/chrome latest versions).
