### ISSUE TITLE
introduce ENV var to enable/disable Jitsi roomnae slugification

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#1683]
https://github.com/thecodingmachine/workadventure/blob/be3c1eea6fef969177139ddd5c724688ec614f05/front/src/WebRtc/JitsiFactory.ts#L132

this breaks our own concept of having unique but also cross-map-shared Jitsi rooms if we decide to.

Should be OPT-OUT

**Comment by gparant** [comment]
You can share Jitsi map between card.

The Jitsi instance name is <team slug>_<world_slug>_<name of Jitsi>. If you use the same name in your maps and rooms, the Jitsi instance will be same.

**Comment by tabascoeye** [comment]
This is about self-hosting with own jitsi.
Then it just interferes with our own slugification.
That's why I suggested an ENV var, because only self-hosters will care about this

**Comment by gparant** [comment]
It's very interesting, I will add this improvement in our backlog.
