### ISSUE TITLE
Using OBS virtual webcam leads to wrong "access denied" message

### ISSUE THREAD

**Issue by fnordsh** [thecodingmachine/workadventure#1684]
When I use a virtual webcam using v4l2loopback and OBS, WorkAdventure will claim that it has no permission to access the webcam, even when it has. The virtual webcam works fine with other software, like BigBlueButton. I get the same behavior in Firefox 95.0.2 and Chromium 96.0.4664.110.
I'm guessing it might have to to with OBS having exclusive access to the physical webcam and then WorkAdventure mistakenly tries to access this camera instead of the virtual one? I'm just guessing, though.

**Comment by jonnytest1** [comment]
i use obs with virtualcam myself and the camera works 🤔

**Comment by jonnytest1** [comment]
duplicate of https://github.com/thecodingmachine/workadventure/issues/1682

**Comment by fnordsh** [comment]
Not sure if this is a duplicate, tbh.

**Comment by fnordsh** [comment]
To make matters more confusing, it sometimes (very rarely) works, but stops working again when I reload or walk to another map.

**Comment by fnordsh** [comment]
OBS Studio is Version 27.1.3-3.

```
[root@xykon ~]# modinfo v4l2loopback
filename:       /lib/modules/5.15.11-arch2-1/updates/dkms/v4l2loopback.ko.zst
license:        GPL
author:         Vasily Levin, IOhannes m zmoelnig <zmoelnig@iem.at>,Stefan Diewald,Anton Novikovet al.
description:    V4L2 loopback video device
srcversion:     1D589CEF9763A5D588748E9
depends:        videodev
retpoline:      Y
name:           v4l2loopback
vermagic:       5.15.11-arch2-1 SMP preempt mod_unload 
parm:           debug:debugging level (higher values == more verbose) (int)
parm:           max_buffers:how many buffers should be allocated (int)
parm:           max_openers:how many users can open loopback device (int)
parm:           devices:how many devices should be created (int)
parm:           video_nr:video device numbers (-1=auto, 0=/dev/video0, etc.) (array of int)
parm:           card_label:card labels for every device (array of charp)
parm:           exclusive_caps:whether to announce OUTPUT/CAPTURE capabilities exclusively or not (array of bool)
parm:           max_width:maximum frame width (int)
parm:           max_height:maximum frame height (int)
```

**Comment by mrweiler** [comment]
After running:
`sudo modprobe v4l2loopback devices=1 video_nr=10 card_label="OBS Cam" exclusive_caps=1`
it seems to work in Firefox 95.0.2-1. Not sure why. Maybe because of the exclusive_caps option?

**Comment by fnordsh** [comment]
Don't know if this is fixed already, but I lost interest.
