### ISSUE TITLE
yet another z-index issue?

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#1690]
it looks like embedded website iframes are above the global messages box:
<img width="1513" alt="Screenshot 2021-12-30 at 17 53 36" src="https://user-images.githubusercontent.com/111893/147772451-0422f648-4c52-4577-b1a7-91dc4beb9b92.png">

Not 100% sure this is the case on vanilla head, though...

**Comment by moufmouf** [comment]
Ping @nolway

**Comment by nolway** [comment]
Fix in : https://github.com/thecodingmachine/workadventure/pull/1620
