### ISSUE TITLE
integrated website iframe allow fullscreen 

### ISSUE THREAD

**Issue by tatrapikao** [thecodingmachine/workadventure#1694]
Is there a way to allow fullscreen in an in-map-website iframe created as mentioned [in the guide](https://workadventu.re/map-building/website-in-map.md) ? 
When using [open website](https://workadventu.re/map-building/opening-a-website.md) i can just use the property `openWebsitePolicy: fullscreen` .
A way to do the same thing for in-map-websites would be great.

**Comment by moufmouf** [comment]
Indeed! That would be a cool feature.
I'm adding this as a possible improvement.

**Comment by gparant** [comment]
Same issue here : #1685

**Comment by gparant** [comment]
This feature was deployed with the new version 🚀 

Thanks for your feedback 💪 
Don't hesitate if you have any other requirement 😍
