### ISSUE TITLE
Enhancement : add notification when group is created

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/workadventure#170]
Would be nice if group is created when app is not focused, so the user is aware that someone is trying to reach him.

This will improove experience if there if 'enter' sound could not be heard.

**Comment by gparant** [comment]
@nguyenk can you exeplain in détail your feature ?

**Comment by VmickaelV** [comment]
I don't know if @nguyenk  has the same need as me. But i think we have the same need/idea.
It will be nice, if the app is not focused, when someone wants talk to you, we have a notification. Currently, we have a sound, but some people may have their earphones off, or muted their computer, so we can't ear the sound.
Maybe, some peoples prefer this feature is can be configurable in some settings pannel.
