### ISSUE TITLE
Messages hang-up pusher and back 

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1701]
With latest develop branch, I get the following on start-up:
```
pusher_1         | [INFO] 12:31:46 Restarting: /usr/src/app/src/Messages/generated/messages_pb.js has been modified
back_1           | [INFO] 12:31:48 Restarting: /usr/src/app/src/Messages/generated/messages_pb.js has been modified
```
Afterwards pusher and back are not running at all or hanging in this state. I think this came from #1698 

For now I can simply fix this, by comment out the messages container in docker-compose yaml, but it worked before and of course generating messages will be necessary on updates, so I would of course prefer if this works as before.

**Comment by gparant** [comment]
ping @moufmouf

**Comment by moufmouf** [comment]
@Lurkars I don't know why this is behaving this way but I experienced the same issue.
I believe that the "messages" container is generating .ts files while NodeJS is compiling those files and it is kind of wreaking havok inside Node which simply hangs.

I solved that by running twice.

```
docker-compose down
docker-compose up
```

Also, if this does not work, try deleting completely `messages/node_modules` and restart all the containers again.

**Comment by moufmouf** [comment]
The problem was actually due to the fact that .ts files are modified while Typescript is compiling.
For some reason, ts-node-dev does not like that.

Fixed this by adding a delay here: https://github.com/thecodingmachine/workadventure/pull/1710
