### ISSUE TITLE
Examples for API Codes, Tiles and Hyperlinks?

### ISSUE THREAD

**Issue by patman1987** [thecodingmachine/workadventure#1704]
Hi, 

I am new to workadventu.re and I need a little bit helps: 

1) Do you have an example for the API codes you described on your homepage?
2) If it´s not possible to embed a homepage, do you think it´s possible to add sth. like a popup with a clickable hyperlink?
3) Where can I find cool tiles examples? Google is not very helpful ATM 

Thank you so much for your help

**Comment by moufmouf** [comment]
Hey @patman1987 ,

1. The API documentation is right here: https://workadventu.re/map-building/scripting.md

You can view the code of our own office here if you are interested: https://github.com/ValdoTR/wa-internal-map/tree/master/src
(the URL to our office is https://play.staging.workadventu.re/@/tcm/workadventure/wa-village)

2. It is definitely possible to embed a homepage or a popup with a link. Embedding a page is shown in this tutorial: https://workadventu.re/map-building/opening-a-website.md

3. Check out https://github.com/workadventure/awesome-workadventure/

Hope this helps!

**Comment by patman1987** [comment]
Wow great. I love it. 

Long night is straight ahead ;)

**Comment by gparant** [comment]
Your welcome @patman1987 and if you need more information, don't hesitate to meet us at our virtual office https://play.staging.workadventu.re/@/tcm/workadventure/wa-village 🚀
