### ISSUE TITLE
confusing exit(scene)url

### ISSUE THREAD

**Issue by jonnytest1** [thecodingmachine/workadventure#1713]
🤔 i havent exactly looked into where the change came from but a while back some of my maps didnt work anymore because exitSceneUrl now seems to require urls in the format of 

`https://somegithub.io/repo/map.json`

however when using the same format for exitUrl

Room.ts#constructor throws an error because exitUrl needs the format of 
`_/global/somegithub.io/repo/map.json`

i'd very much prefer if both exitUrls could handle both cases
(also its probably not obvious why an url should be given in the format of _/global/... )

**Comment by gparant** [comment]
Hi @jonnytest1,

If I understand your idea, you want that define only the url map and the application create your environment `global` in the next map because you are on the map with environment with name `global`? It could be a good idea.

In waiting, you can set `/_/global/...` in the ExitUrl properties.

**Comment by jonnytest1** [comment]
well the main point is that url parsing works differently for exitUrl and exitSceneUrl

**Comment by gparant** [comment]
Yes, at the beginning, we have different process, but today `exitSceneUrl` is deprecated and we use `exitUrl`

**Comment by jonnytest1** [comment]
🤔 i feel like as long as its not completely removed it sohuld still be updated

**Comment by gparant** [comment]
This property will be deleted at a moment, but today is not in our documentation and deprecated in our repository.

I think that we could completely delete it when we will be available to manage versions of map. For this we could save or load JSON file of the map in back and I think that only back (or other specific service) could be manage versioning of map properties.
