### ISSUE TITLE
SecurityError: The operation is insecure

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1715]
On latest dev [, I just get directly to error page with 
> SecurityError: The operation is insecure

Console outputs following, but I am unsure where it directly come from and what was changed to trigger this.

```
DOMException: The operation is insecure. ConnectionManager.ts:170:28
    initGameConnexion ConnectionManager.ts:170
DOMException: The operation is insecure. ErrorScene.ts:80:16
    showError ErrorScene.ts:80
    create EntryScene.ts:60
```
Also I am asking if others also got this error.

**Comment by Lurkars** [comment]
Okay, I could trace it down to:
`ConnectionManager.ts:190`: `await localUserStore.setLastRoomUrl(this._currentRoom.href);`

**Comment by moufmouf** [comment]
Hey @Lurkars ,

I fixed this on Thursday I think. If I'm correct, this is only happening on Firefox in private browsing mode.

I merged this in master directly (hotfix) and did not backport it in develop yet.
Will do that tomorrow.


PR is here:

https://github.com/thecodingmachine/workadventure/pull/1708

If you still see the bug after applying this fix, let me know!

**Comment by moufmouf** [comment]
This is now merged in develop. Closing this.
