### ISSUE TITLE
Microphone and Camera control with Iframe : strange behaviour

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1716]
Hi,

It seems that when my Camera and Microphone button are in an Iframe zone, i can't interact with these buttons

https://user-images.githubusercontent.com/19731340/148920712-04bed90c-c2d1-477e-82d4-3532febf2931.mp4

**Comment by moufmouf** [comment]
Hi @Jacques-Olivier-Farcy 

Thanks for the feedback. I think @nolway reworked the z-index of most elements in #1620. I'm keeping this open until the PR is merged and we can check it solves the issue.

**Comment by nolway** [comment]
Yes, I confirm that it will be fixed in #1620 (I tested it).
