### ISSUE TITLE
Better approval request for micro / camera

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/workadventure#172]
Enhance the request for micro and camera authorization. add a modal, or a visial element that explains why we need access to camera and micro, and warn the user that a dialog will prompt for authorizations.

**Comment by moufmouf** [comment]
Completely :+1:

In my opinion, we need a third page (after user name and choose character) that asks for permissions for the microphone and the camera.
Otherwise, people don't activate it and it kills the "demo effect"
