### ISSUE TITLE
Loading <script type="module"> is turning script requests into CORS requests

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1721]
When we merged https://github.com/thecodingmachine/workadventure/pull/1472, we did not realize that HTTP requests to the script would now be handled by CORS.

(See the "CORS" chapter of https://medium.com/ghostcoder/using-es6-modules-in-the-browser-5dce9ca9e911)

And because the script is loaded inside a sandboxed iframe that has no origin, this is bad. The webserver needs to allow CORS on all origins, otherwise, the script will not load.

We should probably explain that in the documentation and add a feature to load the script without the CORS header.

**Comment by Jacques-Olivier-Farcy** [comment]
Well this could explain my CORS problems
