### ISSUE TITLE
Use double click to walk to pointer position

### ISSUE THREAD

**Issue by anbraten** [thecodingmachine/workadventure#1755]
The walk shortest path on click feature added by #1735 is pretty cool and works perfectly for me. One thing that drives me crazy about it is the moment when I miss-click for example the mute / stop video buttons and my Woka accidentally start to run to that position. What do you think about changing the click to a double click to prevent such cases. 

PS: I can try to open a PR if this is welcome.

**Comment by anbraten** [comment]
I would prefer double click. On right click I would expect some kind of context menu where you could select something like `Go here`, but that sound quite complicated as there currently is nothing else you could select on right click.

**Comment by gparant** [comment]
Yes, nothing else we could select on right click, but tomorrow we could imagine moving element or switch to building mode to add new elements or... 🚀

The problem is that the double click could be a difficult to use to move the player. Hum, it's not easy and it's a very good feedback, thanks 💪

**Comment by Lurkars** [comment]
I really would appreciate dbl-click too. Happens to often to accidentally click somewhere when menus are open and then player just starts walking somewhere I didn't want to. And I also don't understand why this is difficult to use. Even on mobile a double tap seems intuitive for me.

**Comment by moufmouf** [comment]
Ping @Waclaw-I 
Any idea on this?

One of the problem we have is that new users often don't understand that you can move with the keyboard and try to click on the screen. By moving on click, we have a solution that is more friendly to new comers. If we make it a double-click or a right click, it is likely that new-comers will not understand / discover the feature (we can fix this with a tutorial though...)

Gamers would probably use the right click first. At least, this is what is customary in MOBA (like Dota or LOL): left click to select, right click to move.

We could also make this configurable in the menu (not sure if this is a good idea)

**Comment by anbraten** [comment]
Thanks
