### ISSUE TITLE
Feature Request: Announcement to all as moderator/admin

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1765]
This is actually two things

First: A moderator should be able to send text message to all users on CURRENT map, BUT NOT TO ALL ROOMS.

Second: Audio-Broadcast as a moderator/admin on the map. Directly speaking to everybody (except people on silent area) NOT by uploading a file.

**Comment by gparant** [comment]
First: it's possible if you don't check "Brodcast to all room of the world"
<img width="1090" alt="Capture d’écran 2022-01-26 à 16 34 43" src="https://user-images.githubusercontent.com/23724509/151194588-67004602-16f2-44b8-891d-892208db3478.png">

Second: same thing, it's possible if you check this checkbox

**Comment by buenni86** [comment]
It is only possible for admins, but not for moderators.

And the second request was to send broadcast audio, but not as a file instead direct audio transmission

**Comment by buenni86** [comment]
It would be better to give moderators not the admin tag.
They should be able to do the same thing like an admin, BUT without the possibility to send to all rooms (hide the option).
On Events there are more moderators and there is the possibility they will click to all rooms and the others will get confused.

**Comment by Schroedingberg** [comment]
Did anybody get the broadcast to all rooms of the world to work? For me it only worked for the current room, with no error message.
