### ISSUE TITLE
Feature Request: The possibility to select which speaker to use

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1769]
For microphones there is a possibility to select which microphone to use at the beginning or through "Edit your camera",
which by the way is not only camera but microphone, too. Maybe "Edit your A(udio)/V(ideo) Device"
The same ability for speakers would be nice.
So it would be possible to select headset or pc/laptop speakers or any other external speakers.

**Comment by gparant** [comment]
For the headset you can set in your computer settings. If it's workable it could be a good improvement 👍

**Comment by gparant** [comment]
Developed and deployed 🚀
