### ISSUE TITLE
Feature Request: An API for the Admin-Dashboard to create/delete users

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1771]
I know there is a xls or csv import.
It would be better to have an API to easily create/delete users.

**Comment by gparant** [comment]
This work is in progress 💪

**Comment by gparant** [comment]
Deployed with the new version and Zapier integration has been deployed to connect the WorkAdventure API 🚀 

Thanks for your feedback 💪 
Don't hesitate if you have any other requirement 😍
