### ISSUE TITLE
Feature Request: Only select from specific wokas/customisation

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1773]
On some events we want the users only be able to select wokas from the setup we specify them to take.
The admin can limit by tags/public or on a map basis.
That goes for the default wokas/customisation provided by WA, too

**Comment by Jacques-Olivier-Farcy** [comment]
I would really enjoy this feature for my Wacman game ;)
(https://play.workadventu.re/@/hart-city/hart-city/newgame)

**Comment by moufmouf** [comment]
Yes, we are adding this idea to the backlog.

We will need to find a way to design a nice UI for this, though. If you guys have any idea of what could be a cool UI, please share!

**Comment by gparant** [comment]
New design of custom your own Woka was deployed 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create a new issue 😍
