### ISSUE TITLE
Feature Request: Show a symbol when someone is participating in a Jitsi Meeting

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1774]
If someone is on a jitsi zone and is participating in jitsi meeting, show a speaker symbol over their head maybe.
The need for this is because, it is possible to quit the jitsi meeting (closing the jitsi iframe) and do a circle communication on the jitsi zone.
And not showing the symbol the others can see he left the jitsi meeting.
And the possibility to re-enter the jitsi meeting without moving the character out of the zone and back in.

**Comment by gparant** [comment]
The last part is in progress and will be available soon 🚀

**Comment by gparant** [comment]
A talking icon was deployed when you are in Jitsi 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create a new issue 😍
