### ISSUE TITLE
Hard to select wokas if there are too many custom Wokas

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1787]
If there are too many custom wokas, it is hard to select the wokas below the buttons.

![image](https://user-images.githubusercontent.com/1290952/151564384-c40fb380-3275-4aa0-8143-5eaeaacc1300.png)

The buttons should go down (or we should have a way to scroll the wokas).

Note: we will need to change the screen when we implement NFTs anyway.

**Comment by tabascoeye** [comment]
OMG. Do not go down the NFT road. Please reconsider.
