### ISSUE TITLE
Multiple tilesetCopyright in tileset's property seems to only show one ingame

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#1792]
I added on several tilesets the tilesetCopyright property, but it only shows one in the menu ingame

**Comment by gparant** [comment]
Hi @Jacques-Olivier-Farcy can you share us the link of your map and how have you add `tilesetCopyright`?

**Comment by Jacques-Olivier-Farcy** [comment]
Hi Grégoire,
Well my mistake i was not editing in the right place.
It works now
