### ISSUE TITLE
Persist microphone/camera state

### ISSUE THREAD

**Issue by lukashass** [thecodingmachine/workadventure#1794]
I am always a bit anxious about accidentally un-muting myself by reloading workadventure.

Hence, it might be a good idea to persist the state of the microphone and camera in e.g. `localStorage`.

**Comment by moufmouf** [comment]
Weirdly enough, I think it was persisted in the past. @gparant did we change anything or did I dream this?

**Comment by gparant** [comment]
No, we don't stock this in `localStorage`. But we could it, I think that it will be no more complex 🚀

**Comment by nolway** [comment]
Done in #1801

**Comment by moufmouf** [comment]
Closed by #2233
