### ISSUE TITLE
Speed up frontend build and dev-server

### ISSUE THREAD

**Issue by lukashass** [thecodingmachine/workadventure#1796]
I noticed the frontend build and especially the dev-server startup take quite some time.

To speed those up, I would propose migrating from webpack to [vite](https://github.com/vitejs/vite).
I am using vite in some projects and it really is quick :wink:.
The configuration is very similar to webpack (just simpler IMO).

I could open a PR if this is something you would consider.

**Comment by moufmouf** [comment]
Hey @lukashass ,

I would absolutely love to have a faster dev-server startup time.

However, please note that the Webpack config is non-trivial. We have several entry points, custom file generation for the environment variables, Svelte and SASS support.

I have never played with Vite so I don't know if this is possible in Vite or not.

If you want to give it a try, don't hesitate. If the startup time is faster and it's not breaking anything, I'll be happy to merge it! :D
