### ISSUE TITLE
Jitsi blurring is not available

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1808]
Our new Jitsi version can blur background but the option is not exposed in Jitsi (probably because the feature moved from interface_config.js to config.js in the current release).

**Comment by makefu** [comment]
I can confirm this, when clicking on the three dots in the UI the "change background" is not available, however when going directly to the jitsi instance the feature is there.

**Comment by gparant** [comment]
This issue seems solved with the new Jitsi version deployed 🚀
