### ISSUE TITLE
Please remove external ressources

### ISSUE THREAD

**Issue by saschafoerster** [thecodingmachine/workadventure#1842]
For privacy and stability reasons, I would be really happy if all external ressources could be directly hosted by WorkAdventure itself and not link to external ressources. 
I found this two to be linking outside of our domain: 
- https://unpkg.com/nes.css@2.3.0/css/nes.min.css
- https://cdn.quilljs.com/1.3.7/quill.snow.css

Especially with the context of GDPR external ressources embedded like this can cause privacy issues. That's why embedding Google fonts for instance is not recommended anymore: 

https://www.golem.de/news/landgericht-muenchen-einbindung-von-google-fonts-ist-rechtswidrig-2202-162826.html

"A Munich Regional Court judge has ruled that the integration of dynamic web content such as Google Fonts from US web services is illegal without the consent of the visitor. The ruling stated that there is no legitimate interest within the meaning of the General Data Protection Regulation (GDPR), because the Google Fonts can be downloaded and delivered from your own server instead of integrating them via external Google servers. The website operator faces a fine of up to 250,000 euros or imprisonment for up to six months if the plaintiff's IP address is passed on to Google when the website is visited.
While this judgement is about the integration of Google fonts specifically, the principles established by the court also apply to all other content from US services integrated externally into websites. If the ruling stands, any content served by a CDN would be affected. To avoid violating the law, websites must host content such as fonts, scripts or images themselves. Alternatively, website hosts could obtain consent to the disclosure of the IP address via a consent banner."

**Comment by moufmouf** [comment]
This is actually linked to https://github.com/thecodingmachine/workadventure/pull/938 and to https://github.com/nostalgic-css/NES.css/issues/452

There is an issue with Nes.css and Yarn preventing us from bundling Nes.css into the project right now.

For Quill, I'll happily accept a PR :D

**Comment by saschafoerster** [comment]
@moufmouf I am able to install and check connections of a browser. And maybe this issue encourages someone with the ability of programming to change it, as I am not able to do this. Thanks in advance! :)
