### ISSUE TITLE
Camera/User View position stuck to the top left corner of main map

### ISSUE THREAD

**Issue by ps66dev** [thecodingmachine/workadventure#1857]
Hi,

my entire project was last edited 9 months ago - since December (?) I do have the following problem:

When loading my main map the camera/view of the map is stuck to the top left map corner. You can not see the player model, zoom out or in and so on. However, there is a test map in this project which can be loaded and viewed properly. The test map was not been edited since May 2021 as well.

Do you have any recommendations for where to look at?

Thanks a lot!

**Comment by moufmouf** [comment]
Hey @ps66dev ,

Any chance you could send us a link to your map file so we can take a look?

**Comment by ps66dev** [comment]
Hi @moufmouf,

the project is currently the only public repository on my account. Should be accessible via:
https://github.com/ps66dev/KompZe-Berlin

The problematic map file is map.json. The attached image is a screenshot of the json - the "data" section seems to be corrupted? I've only seen that "format" in the map.json, but not in the working test map. This might already be the obvious reason - however, I can not explain why this happened since no one did touch the files since May 2021..
![corruptedMap](https://user-images.githubusercontent.com/69719901/153958542-33986168-8de6-4ad6-a355-cab4a72a0f59.JPG).

**Comment by tabascoeye** [comment]
They are not "corrupted" just encoded as Base64: `"encoding":"base64",`
Open the file in TilEd (preferably in the latest version of the mapeditor) and check if you can convert the encoding back to CSV.

**Comment by ps66dev** [comment]
Hi @tabascoeye,
converting the map encoding back to CSV solved the issue - thank you for the hint.
According to my GitHub versioning, the base64 encoding was active since May 2021 and back then it did work.
Hence the confusion.
Thanks a lot!
