### ISSUE TITLE
Issues with openWebsite / jitsiRooms

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#1863]
I created a small test map. There are even more combinations possible, but I think those already point out some problems:
Map: [lurkars.github.io/wa_maps/tests/openwebsite/openwebsite.json](https://lurkars.github.io/wa_maps/tests/openwebsite/openwebsite.json)

I tested those behaviors on latest Firefox, Ubuntu 21.04. with https://play.staging.workadventu.re 

Basic behavour with just walking on tiles, clicking triggers and close buttons, but ignore icon bar and swap!
1. simple open Website ✔️ works fine
2. simple onaction ✔️ works fine
3. onaction with custom messaage ✔️ works fine
4. onicon ✔️ works fine
5. two simple open Websites on same tile: both sites open in Main Slot (have to click close twice to close them). Expectation on my side: first site open in Main, second site open in Co-Website-Slot
6. two onaction Websites on same tile: same as 5!
7. 1-4 on same tile: same as 5,6
8. Jitis+open Website: same as 5
9. three Jitsi Rooms on same tile, two with onaction: only one trigger Message shown, other properties ignored. Expectation on my side: one jitis room opens directly, after click on one trigger, seconds Jitsi open in Co-Website-Slot

Some more testing on multiple sites (5-9) with swap button and icons bar
- clicking on icon bar opens seconds side in Co-Website-Slot, then clicking swap-button just puts second site to main, so two sites must be closed in main. Expectation on my side: swap just toggles main and co-website slot
- clicking two times on icon seems to move website to main instead of minimizing (also not grayed out icon). Expectation on my side that clicking on icon of opened website just minimize into tray icon.

I recommend just playing around with my example map or create maps on your own to check behavior of openWebsite/jitsiRoom properties on same tile. This was use case before with the multiple Co-Websites slots (where up to 4-5 sites could be opened at once) and check for issues.

@moufmouf @nolway

**Comment by moufmouf** [comment]
Thanks a lot @Lurkars for the tests. We'll look into it tomorrow!

**Comment by nolway** [comment]
> three Jitsi Rooms on same tile, two with onaction: only one trigger Message shown, other properties ignored. Expectation on my side: one jitis room opens directly, after click on one trigger, seconds Jitsi open in Co-Website-Slot

Currently you can't, because Jitsi room properties is unique with the actual checking, to have many Jitsi we must use the enter/exit layer trigger but with this modification Jitsi room on tile properties will stop to work like Co-Website : https://github.com/thecodingmachine/workadventure/issues/1829

**Comment by Lurkars** [comment]
Short reminder, still have some issues with my tests. Example: two websites on one tile, opens now fine one site in main other in slot. But clicking on tray icon of slot site, the icon toggles down but is still active and moved to main slot. So again two sites then in main slot. I think the problem is, that clicking on tray icon should behave completely same like clicking on close button, but doesn't.
