### ISSUE TITLE
Feature Request: Possibility to use O365 as WebApps in WorkAdventure

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#1872]
It would be nice if it is possible to use MS Office Tools within WorkAdventure.
It works with Google Office Tools.

**Comment by moufmouf** [comment]
This is alas not something we can control.
Microsoft can decide if a website can be embedded or not, and it seems they chose the route to forbid it.

https://stackoverflow.com/questions/51188729/embed-office-online-word-excel-powerpoint-in-iframe

**Comment by tabascoeye** [comment]
@buenni86 you can always use `openTab`instead of `openWebsite`. That alsow works with sites not allowing embedding.
Better than nothing…
