### ISSUE TITLE
Problem moveTo property when I leave standby of my computer

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#1915]
I use `moveTo` parameter in the URL. When I leave the standBy and I'm back on google chrome, my Woke move on the place.

I think that we must move the Woka only when the user refresh the URL.

**Comment by gparant** [comment]
So I think that we must clear parameter of the url when the `#moveTo` is used?

**Comment by Waclaw-I** [comment]
> So I think that we must clear parameter of the url when the `#moveTo` is used?

Good idea!
