### ISSUE TITLE
et ça continue :-)

### ISSUE THREAD

**Issue by gregory-r4** [thecodingmachine/workadventure#193]
<img width="1433" alt="Capture d’écran 2020-06-18 à 15 10 12" src="https://user-images.githubusercontent.com/66115296/85024041-d1f4e900-b175-11ea-8580-f75e5b551c35.png">

**Comment by moufmouf** [comment]
Error:

```
        this.scene.physics.world.enableBody(this);

```

world is null. Why? Maybe the scene is not initialized YET.

Idea: this might occur if we are receiving an event from the server while the GameScene is still loading.

We could put all events in a kind of big queue and dequeue the event in the "update" method.
