### ISSUE TITLE
Custom people are overridden in the choice screen

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#1936]
Hey Woka People!

On the screen to choose our character we have two custom ones: (bottom left)

<img width="616" alt="image" src="https://user-images.githubusercontent.com/858611/156140368-31744ebf-de3c-4911-87ae-98645504e943.png">

But when I go over the second one the first is taking his place!! This is sorcery!!!

![woka](https://user-images.githubusercontent.com/858611/156140571-27f28e31-a5bc-48e5-ab19-95cc273e3c8b.gif)

**Comment by Jacques-Olivier-Farcy** [comment]
I love this WOKAt :) is ta availlable somechere ?

**Comment by tabascoeye** [comment]
do they accidentally use the same index ID?
Are you using the original Admin backend or your own?

**Comment by nolway** [comment]
@Waclaw-I can you reproduce this problem ?

**Comment by jacquesbh** [comment]
I can't reproduce anymore since they moved place.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/858611/160358649-9d24075b-7411-442c-9232-4a74a9130858.png">

But now I can't select them, the selection page reloads when I try with one.

**Comment by jacquesbh** [comment]
> do they accidentally use the same index ID? Are you using the original Admin backend or your own?

I don't know if they share the same ID.

We are on Staging environment from Workadventu.re.

**Comment by Waclaw-I** [comment]
Closing - Selection Scene had a makeover and this will soon not be an issue.

**Comment by jacquesbh** [comment]
We are on the staging environment of Workadventu.re.

-- 
Monsieur Biz <https://monsieurbiz.com>
@jacquesbh <https://twitter.com/jacquesbh>
+33 (0)6 75 54 11 97
GPG : https://keybase.io/jacquesbh

🦄


Le ven. 11 mars 2022 à 12:01, TabascoEye ***@***.***> a
écrit :
