### ISSUE TITLE
Unable to connect to WorkAdventure

### ISSUE THREAD

**Issue by radvc** [thecodingmachine/workadventure#1954]
Hello,

I followed this installation instruction https://wiki.techinc.nl/Work-Adventure/install and this video tutorial https://www.youtube.com/watch?v=NQrxne7lS34 to deploy WorkAdventure on my Ubuntu server. After I did all the steps and visit the page I received "Unable to connect to WorkAdventure. Are you connected to the internet?".

<img width="1434" alt="Screen Shot 2022-03-10 at 11 11 32 AM" src="https://user-images.githubusercontent.com/11433690/157581323-1e773a9d-f528-47e8-b25f-dd494a6e8744.png">

SSL is working fine and I am receiving requests logs on docker-compose workadventure-front service.

Appreciate your help. Thanks

Operating System: Ubuntu 20.04
Server: AWS EC2

**Comment by moufmouf** [comment]
Hi @radvc ,

I've never tested those installations method that have been written by the community at large.

Could you try to start WorkAdventure using the docker-file provided in this repository at contrib/production/docker-compose.yaml ?

**Comment by radvc** [comment]
I'm going to close this issue. I figured out my issue.

Thanks!

**Comment by franckya** [comment]
Hi @radvc,
What have you done specifically to resolve this issue? 
I restarted it, but it did not fix the issue. 
Thanks,

**Comment by esra9910** [comment]
HI @radvc ,
Does it work?
I follow the Tutorial and the Documentation too. But my WA Project dosent show. can you help me?
Thank you:)

**Comment by FlorianD78** [comment]
Hi!
Any update?
