### ISSUE TITLE
What does this `void` do?

### ISSUE THREAD

**Issue by pizkaz** [thecodingmachine/workadventure#1957]
Just stumbled upon this during a rebase of the "federation" hack:

https://github.com/thecodingmachine/workadventure/blob/0196eae0552cdcc6e866f7a836368b80e8499716/front/src/Connexion/ConnectionManager.ts#L320

This `void` was added in 24baf5664cf1cc04cdd70fb726b0e2ba667a5e4c. Looks like a bug to me.
Disclaimer: I'm a C / Python guy. ;-)

**Comment by tabascoeye** [comment]
thats good practise in C as well and some style guides mandate it.
If you do not use the return value of a function call, prepend it with a cast to void.

https://pvs-studio.com/en/docs/warnings/v2547/

;)

==> close?

**Comment by pizkaz** [comment]
Hmm shouldn't a typecast look something like `foobarFunction() as void`?

Anyhow. Closed. :-)
