### ISSUE TITLE
Language of the screenshot in "could not start your camera" popup

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1966]
With the German translation, in the popup explaining we cannot start the webcam/microphone, the screenshot is in French.
We need a german one (or at least an english one)

![image](https://user-images.githubusercontent.com/1290952/158351767-0ce041cc-77cc-4193-9218-2d9cdeb05635.png)

**Comment by moufmouf** [comment]
Here is a screenshot of a German browser:

![image](https://user-images.githubusercontent.com/1290952/158359446-62c151d6-5bf8-4cca-af62-3fb648021fcb.png)

(courtesy of Kai, thanks!)

**Comment by nolway** [comment]
I think it is better to display only the English screenshot ?
