### ISSUE TITLE
A way to fix visual artifacts when moving

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#197]
Found in the Phaser 3 devlogs:
https://phaser.io/phaser3/devlog/122

(End of the article)

There is a tool that rewrites the tile sets to avoid the nasty glitch

**Comment by pwab** [comment]
Thanks for the hint! The explanation below "Tileset Extrusion" could be included into the docs because I also ran into this.
Maybe also change the default tileset of the workadventure template with an extruded one made by https://github.com/sporadic-labs/tile-extruder?

**Comment by moufmouf** [comment]
Hi  @pwab ,
Actually, we introduced a way to automatically extrude tiles in the map starter kit (https://github.com/thecodingmachine/workadventure-map-starter-kit)

There is a Github action there that automatically extrude tiles. It is based on https://github.com/sporadic-labs/tile-extruder.

**Comment by pwab** [comment]
Oh that is interesting. As I started my project from your template everything should be fine then.
So maybe my problem is something else?

See here the vertical lines which are getting another color when they are left to the player (this is the ground layer - so no layer below):
![green_lines](https://user-images.githubusercontent.com/19271185/98645103-c4f9b180-2331-11eb-9025-8d000edbc281.png)

The switch from green to the normal color can be seen here:
![xPDlNwq3cZ-min](https://user-images.githubusercontent.com/19271185/98645268-02f6d580-2332-11eb-8ec6-f32e96b7247d.gif)

You can test it yourself:
https://play.workadventu.re/_/global/pwab.github.io/cltadventure/map.json

So this has nothing to do with tileset extrusion?
