### ISSUE TITLE
2 Jitsi can open at the same time

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#1977]
On a map, put 2 jitsi layers, 2 tiles apart from each other.

Walk in straight line, going through one, to the other.

2 window will open instead of one.

See:

https://user-images.githubusercontent.com/1290952/158618200-fb1bf4cd-17d1-40a4-adfc-de5563775965.mp4

**Comment by nolway** [comment]
Fix in master branch
