### ISSUE TITLE
Jitsi session problem in chrome based browsers

### ISSUE THREAD

**Issue by spezi** [thecodingmachine/workadventure#1988]
we have currently Problems to open the Meeting Room Jitsi Sessions with chrome based browsers. Sometimes the Jitsi session stay blue background and will not start or open. After leaving the room camera is deactivated and have to be re-enabled. the Problem is not permanent, sometimes it works and sometimes not. So it is possible you join a room and everything ok and if you want to change to a nother jitsi session it stop working. 

In case of failure it throws some errors in Browser Console:

`Logger.js:154 2022-03-19T10:35:57.944Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Cannot destructure property 'id' of '$p(...)' as it is undefined. Script: null Line: null Column: null StackTrace:  TypeError: Cannot destructure property 'id' of '$p(...)' as it is undefined.
    at Object.changeLocalDisplayName (https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:558897)
    at Object.display-name (https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:560908)
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:567339
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:487234
    at Set.forEach (<anonymous>)
    at Lee.on (https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:487221)
    at Object.init (https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:567274)
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:2:258132
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:1603177
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:737729
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:711359
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:710670
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:706055
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:705722
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:705115
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:703918
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:703057
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:700623
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:700547
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:685596
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:679212
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:679019
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:678031
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:673008
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:670442
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:668967
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:668799
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:668469
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:667458
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:667051
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:664376
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:662212
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:662067
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:661784
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:661745
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:656292
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:655482
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:655209
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:652369
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:652001
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:651597
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:650064
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:647849
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:646435
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:644643
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:644380
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:644310
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:642839
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:638121
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:637327
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:634062
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:631535
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:630121
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:628873
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:628834
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:627335
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:626425
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:626151
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:620014
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:617400
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:611796
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:609304
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:608403
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:608047
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:607055
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:606385
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:605840
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:603951
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:602806
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:602768
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:601467
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:601238
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:599404
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:597914
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:597838
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:596106
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:595117
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:592956
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:592014
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:587745
    at Object.dispatch (https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:587333)
    at APP.componentDidMount (https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:2:258081)
    at async APP.componentDidMount (https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:585769)
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:530
window.onunhandledrejection @ middleware.js:127
conference.js:3086 Uncaught (in promise) TypeError: Cannot destructure property 'id' of '$p(...)' as it is undefined.
    at Object.changeLocalDisplayName (conference.js:3086:17)
    at Object.display-name (API.js:140:28)
    at API.js:554:22
    at Transport.js:159:17
    at Set.forEach (<anonymous>)
    at Lee.on (Transport.js:158:35)
    at Object.init (API.js:552:15)
    at actions.js:27:44
    at index.js:11:18
    at middleware.js:30:12
    at middleware.js:33:20
    at middleware.js:19:20
    at middleware.web.js:30:20
    at middleware.any.js:44:20
    at middleware.js:67:12
    at middleware.js:45:12
    at middleware.js:61:12
    at middleware.js:19:20
    at middleware.js:121:12
    at middleware.js:71:12
    at middleware.js:79:20
    at middleware.js:39:12
    at middleware.js:221:12
    at middleware.js:11:20
    at middleware.js:68:12
    at middleware.js:31:20
    at middleware.web.js:46:12
    at middleware.web.js:24:12
    at middleware.any.js:94:20
    at middleware.js:77:12
    at middleware.web.js:34:20
    at middleware.js:32:12
    at middleware.js:25:12
    at middleware.js:16:20
    at middleware.js:21:12
    at middleware.js:23:12
    at middleware.js:20:20
    at middleware.js:167:12
    at middleware.js:16:16
    at middleware.js:39:20
    at middleware.js:33:12
    at middleware.js:209:12
    at middleware.js:39:12
    at middleware.js:24:12
    at middleware.js:28:20
    at middleware.web.js:20:20
    at middleware.js:42:20
    at middleware.js:227:12
    at middleware.js:21:20
    at middleware.js:130:12
    at middleware.js:44:12
    at middleware.js:49:12
    at middleware.js:90:20
    at middleware.js:12:20
    at middleware.js:39:12
    at middleware.js:35:12
    at middleware.web.js:30:12
    at middleware.any.js:105:12
    at middleware.js:203:12
    at middleware.js:106:20
    at middleware.js:29:16
    at middleware.js:27:12
    at middleware.js:23:20
    at middleware.web.js:11:20
    at middleware.any.js:78:12
    at middleware.js:16:20
    at middleware.js:91:12
    at middleware.js:75:12
    at middleware.js:24:20
    at middleware.js:20:12
    at middleware.js:15:20
    at middleware.js:101:12
    at middleware.js:23:20
    at middleware.js:21:20
    at middleware.js:25:12
    at middleware.js:76:20
    at middleware.js:236:12
    at middleware.web.js:26:12
    at middleware.js:201:12
    at middleware.js:38:12
    at Object.dispatch (middleware.web.js:124:12)
    at APP.componentDidMount (BaseApp.js:100:26)
    at async APP.componentDidMount (AbstractApp.js:44:28)
changeLocalDisplayName @ conference.js:3086
display-name @ API.js:140
(anonymous) @ API.js:554
(anonymous) @ Transport.js:159
on @ Transport.js:158
init @ API.js:552
(anonymous) @ actions.js:27
(anonymous) @ index.js:11
(anonymous) @ middleware.js:30
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:19
(anonymous) @ middleware.web.js:30
(anonymous) @ middleware.any.js:44
(anonymous) @ middleware.js:67
(anonymous) @ middleware.js:45
(anonymous) @ middleware.js:61
(anonymous) @ middleware.js:19
(anonymous) @ middleware.js:121
(anonymous) @ middleware.js:71
(anonymous) @ middleware.js:79
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:221
(anonymous) @ middleware.js:11
(anonymous) @ middleware.js:68
(anonymous) @ middleware.js:31
(anonymous) @ middleware.web.js:46
(anonymous) @ middleware.web.js:24
(anonymous) @ middleware.any.js:94
(anonymous) @ middleware.js:77
(anonymous) @ middleware.web.js:34
(anonymous) @ middleware.js:32
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:167
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:33
(anonymous) @ middleware.js:209
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:28
(anonymous) @ middleware.web.js:20
(anonymous) @ middleware.js:42
(anonymous) @ middleware.js:227
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:130
(anonymous) @ middleware.js:44
(anonymous) @ middleware.js:49
(anonymous) @ middleware.js:90
(anonymous) @ middleware.js:12
(anonymous) @ middleware.js:39
(anonymous) @ middleware.js:35
(anonymous) @ middleware.web.js:30
(anonymous) @ middleware.any.js:105
(anonymous) @ middleware.js:203
(anonymous) @ middleware.js:106
(anonymous) @ middleware.js:29
(anonymous) @ middleware.js:27
(anonymous) @ middleware.js:23
(anonymous) @ middleware.web.js:11
(anonymous) @ middleware.any.js:78
(anonymous) @ middleware.js:16
(anonymous) @ middleware.js:91
(anonymous) @ middleware.js:75
(anonymous) @ middleware.js:24
(anonymous) @ middleware.js:20
(anonymous) @ middleware.js:15
(anonymous) @ middleware.js:101
(anonymous) @ middleware.js:23
(anonymous) @ middleware.js:21
(anonymous) @ middleware.js:25
(anonymous) @ middleware.js:76
(anonymous) @ middleware.js:236
(anonymous) @ middleware.web.js:26
(anonymous) @ middleware.js:201
(anonymous) @ middleware.js:38
(anonymous) @ middleware.web.js:124
componentDidMount @ BaseApp.js:100
Show 51 more frames
Logger.js:154 2022-03-19T10:35:57.945Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Cannot read properties of undefined (reading '_navigate') Script: null Line: null Column: null StackTrace:  TypeError: Cannot read properties of undefined (reading '_navigate')
    at https://meet.ourjitsiurl.net/libs/app.bundle.min.js?v=5818:138:737693
r @ Logger.js:154
getGlobalOnErrorHandler @ JitsiMeetJS.js:530
window.onunhandledrejection @ middleware.js:127
middleware.js:154 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_navigate')
    at middleware.js:154:48 `

and this are logged by jicofo:

Jicofo 2022-03-17 18:23:21.738 WARNING: [263] [room=globalklasse56@muc.meet.jitsi meeting_id=ed6b113b-9685-436b-9fff-376ac07ab0a1] JitsiMeetConferenceImpl.onMemberLeft#810: Participant not found for 7417444d. Terminated already or never started?

i had the same Problem at other Instances too, so it could be a Bug

**Comment by moufmouf** [comment]
Hi @spezi ,

I'm pretty sure this is fixed by #1974.
This will be deployed tonight on the SAAS release. If you are self-hosting, you need to redeploy the latest version.

**Comment by spezi** [comment]
hi @moufmouf

You are right, works like a charme ;) Thanks a lot for workadventure, you guys are great
