### ISSUE TITLE
Naked character

### ISSUE THREAD

**Issue by E-OssO** [thecodingmachine/workadventure#1992]
Hi,

This morning all of our characters are naked... We need to reload our Woka.
Maybe, if we loose our Woka a default will be nice than naked ;)

**Comment by moufmouf** [comment]
Hi @E-OssO ,

Sorry about that, a bug in the Tuesday morning release lost most character textures.
This is now fixed.

By the way, the character is not exactly naked. If you look closely at it, it is also transparent. It's a ghooooOOooost :ghost:  ;)
