### ISSUE TITLE
Cannot switch devices (Camera or Microphone) on Firefox

### ISSUE THREAD

**Issue by maximehuran** [thecodingmachine/workadventure#1998]
I change the value in the select but it's not saved.
I tried to remove the `cameraSetup` param in local storage but still persist.

![camera](https://user-images.githubusercontent.com/11380627/159973864-88986273-c41e-4831-9cd1-7eb14ba54d19.gif)

**Comment by gparant** [comment]
The fix was merged in master branch 🚀
