### ISSUE TITLE
Callback after sound has played

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#2000]
It would be great if the scripting API supported giving the `sound.play()` function a callback function which is called when the sound has finished playing.

This way I could implement:

1. player enters layer
2. controls are disabled
3. sound file plays
4. controls are re-enabled after sound file finished playing

**Comment by tabascoeye** [comment]
should be doable with built-in phaser callbacks since you seem to be using the basesoundmanager:
https://photonstorm.github.io/phaser3-docs/Phaser.Sound.BaseSoundManager.html#play
https://photonstorm.github.io/phaser3-docs/Phaser.Sound.Events.html#event:COMPLETE

**Comment by tabascoeye** [comment]
btw: the sound.stop() function seems broken. it doesn't work

**Comment by moufmouf** [comment]
> btw: the sound.stop() function seems broken. it doesn't work

This issue is fixed by https://github.com/thecodingmachine/workadventure/pull/2132
