### ISSUE TITLE
Pusher connexion error when i'm sign in

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2022]
Connexion error on the pusher:

<img width="691" alt="Capture d’écran 2022-03-30 à 13 11 05" src="https://user-images.githubusercontent.com/23724509/160824603-35c29267-441d-44a9-98bc-a95babd1e0d5.png">

OS: MAC
Browser: Chrome

**Comment by moufmouf** [comment]
Related to #2063
