### ISSUE TITLE
UI too many private WOKA

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2040]
When I try to add many private WOKA, I can't select the last.
![Capture d’écran 2022-04-05 à 13 26 05](https://user-images.githubusercontent.com/23724509/161747268-ca25f8e7-85c3-4c80-bfbd-5e0cfcfba22b.png)

**Comment by Waclaw-I** [comment]
I suggest waiting for this to be (hopefully :D ) merged
https://github.com/thecodingmachine/workadventure/pull/1997
