### ISSUE TITLE
Follow mode breaks across worlds

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2049]
Let's see player B follows player A.

When player A takes an exit, player B stops following player A. This is normal since we don't yet support following across rooms.

However, on player A screen, there is still the "player B is following you" message displayed. And Player A cannot click the "follow" icon to desactivate this.

**Comment by Waclaw-I** [comment]
It is possible to click "unfollow" icon after entering new room. We could make it to be done automatically though.

**Comment by gparant** [comment]
> It is possible to click "unfollow" icon after entering new room. We could make it to be done automatically though.

I think we may use chat to send request message and stop following?

**Comment by Waclaw-I** [comment]
After closer investigation, there are more problems to Follow feature (mainly cancelling it out, refusing). I will work on it.
