### ISSUE TITLE
Could not extract instance from "..."

### ISSUE THREAD

**Issue by albanbruder** [thecodingmachine/workadventure#2064]
If I understand https://github.com/thecodingmachine/workadventure/commit/c9fa9b9a923c3d4add81b99dc3e074b9088d1c68 correctly the front should be able to handle arbitrary room urls. Such as `/@/test` or `/@/test/123`. But I still get the error `Could not extract instance from "@/test/123"` if I use shorter room urls without the organization slug. I think this is because the Phase GameScene still uses the deprecated function `getInstance` here: https://github.com/thecodingmachine/workadventure/blob/develop/front/src/Phaser/Game/GameScene.ts#L237

Is this a bug or is this feature not supported?

**Comment by gparant** [comment]
Hi @albanbruder, in this commit, we speak of agnostic front about organization, world and room slug. So this is not verified in the open source repository and we share the complete URL to our SAAS. It checks the structure, so we keep this URL structure to be connected to our SAAS (`/@/organization/world/room`)

**Comment by albanbruder** [comment]
Thank you for your answer.

I guess the sentence `This allows the backend to act as a complete router.` is a little misleading. I would love to see support for arbitrary room urls, where the backend manages all the logic of routing. I think GameScene is the only class still using the `getInstance` function. We might be able to replace this with the `room.id`?

This would allow custom admin servers to use different naming schemes than SAAS. (e.g another prefix)

**Comment by moufmouf** [comment]
@albanbruder The idea is indeed that the admin should be able to act as a router. And indeed, for "historic" reasons, we still need the "getInstance" part. We can't really replace this with the room id (it is too long). I think we should send the "instance" from the admin/pusher via the /map endpoint.

**Comment by moufmouf** [comment]
@albanbruder If you want to help, I'd happily accept a PR to change this.
We should be able to fetch the "instance" in the Room.getMapDetails map.
This means the "instance" should be computed in the pusher (if there is no admin) or received from the admin if there is one.
