### ISSUE TITLE
Please create deployment instructions/docker compose for your largest audience 

### ISSUE THREAD

**Issue by timdonovanuk** [thecodingmachine/workadventure#2078]
![image](https://user-images.githubusercontent.com/8156439/162957680-e529417d-0918-4e7b-89a9-a36551d4713c.png)

The current compose files are useful for an extremely weird audience that has the knowledge and understanding to have an external hosted server but DOES NOT have any reverse proxy or https issuer in place.

**Comment by moufmouf** [comment]
Hey @timdonovanuk ,

Nice graph ;)
You are referring to the docker-compose file in /contrib/docker, right?

There are really as many production environment as there are users and we don't really plan to support thousands of different use cases.

> The current compose files are useful for an extremely weird audience that has the knowledge and understanding to have an external hosted server but DOES NOT have any reverse proxy or https issuer in place.

I should probably make the README clearer, but here is what I wanted to do with the file in "/contrib/docker". I was looking for a simple file to bootstrap a working environment on a bare VM that has just Docker.

The idea is that by reverse engineering docker-compose, you can adapt it to your own environment (for instance, some users are deploying to Kubernetes and used the docker-compose file from "/contrib/docker" as an example.

How would you improve this?

**Comment by CarlosX4vier** [comment]
I thought I was the only one having difficulties using WA in prod.

After 3 days of trying, I gave up because with each attempt I came across a different problem.

**Comment by moufmouf** [comment]
@albanbruder The setup for Mailu is quite nice!

I don't really have the time to dig into this right now, but at least, I'm working on a small doc to help people getting started at #2109 

You guys can see the doc here:

https://github.com/thecodingmachine/workadventure/blob/fa012afa2f41acc1f95ea5a2941cc7017a0cf030/contrib/docker/README.md

Any feedback is appreciated!
