### ISSUE TITLE
"Edit member" button not working

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#2081]
Hi, I noticed that the pencil icon to show the member's modal is not doing anything (in production environment).
I have errors in the console but they don't seem to be linked to this error:
![image](https://user-images.githubusercontent.com/14997703/163139105-1640fa24-ee67-44f0-ae1f-cd7afe56875a.png)

**Comment by gparant** [comment]
Deploy in new version of admin 🚀
