### ISSUE TITLE
Purple box and green lines appearing

### ISSUE THREAD

**Issue by timdonovanuk** [thecodingmachine/workadventure#2088]
Hi,

Please let me know how to remove these features:

![image](https://user-images.githubusercontent.com/8156439/163239307-e9d81875-b348-4a62-af23-1613e545a814.png)

DEBUG_MODE is set to false.

Many thanks!

**Comment by timdonovanuk** [comment]
Hmm, these suddenly vanished. I have been through 3 hours clearing/rebuilding docker volumes, Chrome cache, nginx cache etc. Suddenly stopped showing. Oh well!

**Comment by moufmouf** [comment]
Allright! If this ever happens again and there is something we can do about it, let us know :D
