### ISSUE TITLE
[RFC] Change the way Jitsi room names are generated

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2089]
Right now, when you use a jitsiRoom property and you are in SAAS mode, the Jitsi room is prepended with org + world (and not org + world + map like the documentation implies)
When using the self-hosted version, the jitsiRoom property is preprended with the "instance" part of the URL (as in "https://play.workadventu.re/_/[instance]/[map_url]").

I think both are wrong.

In SAAS mode, if you have 2 rooms in the same world that have the same jitsiRoom property, they will end up on the same Jitsi meeting.
In self-hosted version, if you are using the "global" instance (which became the default for most people), 2 rooms that have the same jitsiRoom property will end up on the same Jitsi meeting.

99% of the time, this is not what the user wants. I mean, I never really had a case where people in different rooms wanted to attend the same Jitsi meeting.

This PR #2079 by @albanbruder made me realize the whole notion of room "instance" is probably broken and should not be used for Jitsi.

Proposal:

The Jitsi room name should be prepended with a short hash of the current URL.

So if the URL of my room is: "https://play.staging.workadventu.re/@/tcm/workadventure/wa-village" and if my property "jitsiRoom" is "Albert Einstein", then the Jitsi meeting name should be something like: "z4pd24-albert-einstein", where "z4pd24" is a short hash of "https://play.staging.workadventu.re/@/tcm/workadventure/wa-village".

If we do this, we can close #1928, #2060 and #2064

The problem: some people are using the Jitsi application on their mobile device and have bookmarked the Jitsi meetings. They will have to benchmark the new meeting names.

Also, I'm propositing adding an additional property (maybe `jitsiRoomUseFullName: true`) that would use the jitsiRoom name without prepending anything.

@albanbruder @tabascoeye @Lurkars @gparant @nolway Thoughts?

**Comment by ValdoTR** [comment]
> The problem: some people are using the Jitsi application on their mobile device and have bookmarked the Jitsi meetings. They will have to benchmark the new meeting names.

I don't think it's an issue, we just have to communicate on that. If you need the direct link of a jitsi room you just have to do the process again (maybe we can facilitate this process?).

> Also, I'm propositing adding an additional property (maybe jitsiRoomUseFullName: true) that would use the jitsiRoom name without prepending anything.

So if we set `jitsiRoomUseFullName: true`, what will be the generated name of the jitsi room? If we just use the jitsiRoom value as a name, we will cause many maps to have the same jitsi rooms.

**Comment by moufmouf** [comment]
> So if we set jitsiRoomUseFullName: true, what will be the generated name of the jitsi room? If we just use the jitsiRoom value as a name, we will cause many maps to have the same jitsi rooms.

Yes, that would be "on purpose". I don't expect many people to use this feature. And if you specify a "jitsiUrl" + a "jitsiRoomUseFullName", you can actually target any Jitsi room of any Jitsi server. This could maybe be useful for some of our users?

**Comment by albanbruder** [comment]
I'm also in favor of dropping the notation of instances. Especially since the URL of the Jitsi room is hidden anyway (at least in the game).

**Comment by tabascoeye** [comment]
Well for rc3 we needed both.
There was the very popular "global phonebooth" which lots of assemblies used in their maps. So one jitsi room across multiple rooms across multiple worlds in your old definition.

To achieve that, we removed the "slug" code because our map linter created those slugs _if_ the jitsi room was not prepended with "shared" keyword, which disabled the slug prefix generation.

So as always. You need to let users choose ;)

**Comment by Lurkars** [comment]
Yes,I also think it would be a good idea, to create jitsi room name unique for map and then add additional property to mark a room as "global" to be accessible in all worlds and important outside jitsi. I have also use case, that I have a room in map that should also be easily accessible from outside. 
So default unique I'd via map URL, option for global room would be my preference.
