### ISSUE TITLE
admin api search and discover

### ISSUE THREAD

**Issue by lochot** [thecodingmachine/workadventure#2092]
to stop my own flood on discord, i will write here ;)

i am trying to creating my own admin api.
Actualy, it can receive the 
>/api/map request and answer correctly
>/api/room/access and answer as anonyme
>/api/woka/list and answer with the json list of woka
and now, i do not have any errors anymore on my console, i didn't receive request that i do not answer, so it's pretty cool

BUT
map do not show, and show me the woka list, server side it show that : 

```console
pusher_1         | Calling joinRoom   
back_1           | joinRoom called    
back_1           | 2022-04-14T12:18:41.816Z A user joined    
pusher_1         | A user left 
back_1           | A user left
pusher_1         | Connection lost to back server
pusher_1         | A user left
pusher_1         | Calling joinRoom
back_1           | joinRoom called
back_1           | 2022-04-14T12:18:47.839Z A user joined
pusher_1         | A user left
back_1           | A user left
pusher_1         | Connection lost to back server
pusher_1         | A user left
```

admin api side that : 

```logs
2022-04-14 14:18:36 : a:8:{s:3:"api";s:16:"/api/room/access";s:14:"userIdentifier";s:36:"aaaaaaaa-68bb-45f5-860e-f1f033a180fc";s:7:"playUri";s:63:"https://on-my-shop.com/_/global/wamap.larp-place.com/wamap.json";s:9:"ipAddress";s:10:"172.23.0.1";s:15:"characterLayers";a:1:{i:0;s:5:"male7";}s:6:"module";s:13:"workadventure";s:10:"controller";s:9:"workadret";s:2:"fc";s:6:"module";}
2022-04-14 14:18:36 : a:5:{s:3:"api";s:8:"/api/map";s:7:"playUri";s:63:"https://on-my-shop.com/_/global/wamap.larp-place.com/wamap.json";s:6:"module";s:13:"workadventure";s:10:"controller";s:9:"workadret";s:2:"fc";s:6:"module";}
2022-04-14 14:18:36 : a:6:{s:3:"api";s:14:"/api/woka/list";s:7:"roomUrl";s:63:"https://on-my-shop.com/_/global/wamap.larp-place.com/wamap.json";s:4:"uuid";s:36:"aaaaaaaa-68bb-45f5-860e-f1f033a180fc";s:6:"module";s:13:"workadventure";s:10:"controller";s:9:"workadret";s:2:"fc";s:6:"module";}
```

so i am in a loop, when i watch my admin api log, i see that wa call /api/woka/list, after that, it call /api/map, and /api/room/acces and that is ok, but just after it call one more time /api/room, and send only playUri and not anymore userId

Actualy, i am stuck

**Comment by moufmouf** [comment]
When you arrive on a map, WA will call the /api endpoint of all the exits.
Maybe this is what you are looking at?

If you are going in a loop, my guess is that the room/access endpoint is not sending the details of the woka (so you are sent back to the woka selection page)

**Comment by lochot** [comment]
Logic, i am looking on it.
So i look on  PlayerTextures.ts and zod details are thoses : 
```typescript
export const isWokaDetail = z.object({
    id: z.string(),
    url: z.optional(z.string()),
    layer: z.optional(z.string()),
});
```
So my admin Api send this : 
```json
{"email":"345b2b3b-68bb-45f5-860e-f1f033a180fc",
"userUuid":"345b2b3b-68bb-45f5-860e-f1f033a180fc",
"tags":[],
"visitCardUrl":null,
"textures":{"id":"male2","url":"resources/characters/pipoya/Male 02-2.png"},
"messages":[]}
```
based on that (in AdminApi.ts)
```typescript
export const isFetchMemberDataByUuidResponse = z.object({
    email: z.string(),
    userUuid: z.string(),
    tags: z.array(z.string()),
    visitCardUrl: z.nullable(z.string()),
    textures: z.array(isWokaDetail),
    messages: z.array(z.unknown()),
    anonymous: z.optional(z.boolean()),
    userRoomToken: z.optional(z.string()),
});
```
But pusher is not very happy with it
```console
openIDCallback => fetchMemberDataByUuid Error: Invalid answer received from the admin for the /api/room/access endpoint.
```
As soon as i remove the content of textures, error disappear, but loop is looping.
So what am i doing wrong with my woka ?

**Comment by albanbruder** [comment]
Hello @lochot,

I think the Pusher error occurs because `textures` is defined as an array but you are returning an object.

**Comment by lochot** [comment]
@albanbruder well done !
no more errors from fetchMemberDataByUuid. I think that i tried it but a problem with the map confused me ;)

Thank you, i close this issue
