### ISSUE TITLE
Http is fine but Https 404

### ISSUE THREAD

**Issue by bluefish625** [thecodingmachine/workadventure#2105]
When i clone the latest version, run docker-compose up, waiting for a while to finish building - it is not working as expected.

by the way, the host is set to  meta.xxx.com.

http://play.meta.xxx.com works fine.

https://play.meta.xxx.com show just: 404 page not found.

**Comment by gparant** [comment]
Hi @bluefish625,
Please can you share us more details on your configuration, proxy use, acme with let’s encrypt use or manual certification…

**Comment by bluefish625** [comment]
> Hi @bluefish625, Please can you share us more details on your configuration, proxy use, acme with let’s encrypt use or manual certification…

em... maybe the problem is: I'm not set certification.

Please, How to set it ?

**Comment by bluefish625** [comment]
> 



> Hi @bluefish625, Please can you share us more details on your configuration, proxy use, acme with let’s encrypt use or manual certification…

I have a CA certification, how to set it?

**Comment by bluefish625** [comment]
> 



> Hi @bluefish625, Please can you share us more details on your configuration, proxy use, acme with let’s encrypt use or manual certification…


In docker-compose.yaml, I add :
- --entryPoints.https.tls.Certificates.certFile=/crtFile/xxx.com.pem
- --entryPoints.https.tls.Certificates.keyFile=/crtFile/xxx.com.key

but, it not work.

**Comment by gparant** [comment]
If you use traefik, you can see the documentation here: https://doc.traefik.io/traefik/https/tls/

**Comment by bluefish625** [comment]
> If you use traefik, you can see the documentation here: https://doc.traefik.io/traefik/https/tls/

thanks verfy much， i fix it with ACME

**Comment by bluefish625** [comment]
done
