### ISSUE TITLE
No connection to wss with ssl

### ISSUE THREAD

**Issue by localtux** [thecodingmachine/workadventure#2108]
Hello,

I have tried to install Workadventure on my local PC and also on a server. When I establish an unencrypted connection (http://) it works so far. But as soon as I try to establish an encrypted connection the error message "Firefox can't connect to the server at wss://play.workadventure.localhost:80/" appears. The following can be observed:

local: Firefox just stays at a black output and page loading stops.
server: Firefox loads in a loop for a very long time and after some time, "Unable to connect to Workadventure. Are you connected to internet?" appears.

It doesn't matter if it's local or on a server. I use the provided docker-compose.yaml and the following .env:

```
DOMAIN=workadventure.localhost

DEBUG_MODE=true
JITSI_URL=meet.jit.si
JITSI_PRIVATE_MODE=false
JITSI_ISS=
SECRET_JITSI_KEY=
START_ROOM_URL=/_/global/maps.workadventure.localhost/starter/map.json


DISABLE_NOTIFICATIONS=true
SKIP_RENDER_OPTIMIZATIONS=false

ACME_EMAIL=

MAX_PER_GROUP=4
MAX_USERNAME_LENGTH=8

OPID_CLIENT_ID=
OPID_CLIENT_SECRET=
OPID_CLIENT_ISSUER=
OPID_CLIENT_REDIRECT_URL=
OPID_LOGIN_SCREEN_PROVIDER=http://pusher.workadventure.localhost/login-screen
OPID_PROFILE_SCREEN_PROVIDER=
DISABLE_ANONYMOUS=
CONTACT_URL=

CERT_LOCATION=/etc/traefik/acme
```

![Screenshot_20220422_083530](https://user-images.githubusercontent.com/97430797/164618951-c3a5bbbd-ee35-4233-a2c7-6910a71b3703.png)

**Comment by moufmouf** [comment]
Hi @localtux ,

The /docker-compose.yaml file at the root of the project is meant for development.
It is supposed to be used in HTTP only and cannot be used in HTTPS (you actually would not be able to get a valid certificate for the domain workadventure.localhost).

When deploying on a server, you should instead use `contrib/docker/docker-compose.prod.yaml` which contains support for fetching a certificate with Let's encrypt automatically.
By the way, I'm currently working on the documentation of this docker-compose.prod.yaml so you can take a look at this doc in #2109

**Comment by localtux** [comment]
Wow, thank you so much, that's great. Either I didn't understand the doc properly or I just read over it but the contrib/docker/docker-compose.prod.yaml I just didn't see or pay attention to.

It also works wonderfully with an SSL certificate now.

Thanks a lot for the hint.
