### ISSUE TITLE
No background set for openWebsite

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2128]
If we open a website that does not define any background-color, the "loading cup" will still be visible.

![image](https://user-images.githubusercontent.com/1290952/165280008-b98d3bbf-3e7f-4ad9-b89e-a63ca5f29bd2.png)

Since browsers are using a white background by default, we should probably do the same.

On iframe load event, we should consider removing the cup of coffee and displaying a white background instead.

**Comment by nolway** [comment]
Fix in develop branch.
