### ISSUE TITLE
Import Woka

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2130]
- When I update woka in default collection with tag `speaker`, new woka collection is created. Why not. But when I apply the same changes on other Woka, new collection again is created. I think ot could be smart to have one collection with tag `speaker`. Apply same thing for accessories.
 
 - When I try to import Woka, I choose Default, all of woka is present. The Woka already imported must have information already imported ( see exemple ). The default Woka not imported could be listed in first. Apply same thing for accessories.
 
 - I import WOKA public and try to connect in public room. When I arrived on Select Woka Scene, just the last Woka imported is displayed. Woka by default are not diplayed. 
 Same thing when I try to connect with user who have tag `speaker`. Just last public Woka imported is displayed.

**Comment by nolway** [comment]
> When I update woka in default collection with tag speaker, new woka collection is created. Why not. But when I apply the same changes on other Woka, new collection again is created. I think ot could be smart to have one collection with tag speaker. Apply same thing for accessories.
Done.

> When I try to import Woka, I choose Default, all of woka is present. The Woka already imported must have information already imported ( see exemple ). The default Woka not imported could be listed in first. Apply same thing for accessories.
Keep in memory for the default woka re-work

> I import WOKA public and try to connect in public room. When I arrived on Select Woka Scene, just the last Woka imported is displayed. Woka by default are not diplayed.
Same thing when I try to connect with user who have tag speaker. Just last public Woka imported is displayed.
Not reproduced
