### ISSUE TITLE
Why not use jitsi for group chat

### ISSUE THREAD

**Issue by ZacharyJia** [thecodingmachine/workadventure#2141]
It seems the group chat is implemented via webRTC by hand in this project. However as jitsi is integrated, why not just use jitis api (lib-jitsi-meet https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ljm-api) for group chat? And there are also some libraries like [jitsi-svelte](https://github.com/relm-us/jitsi-svelte) for convinence. Therefore no extra STUN/TURN servers need to be deployed and the complexity will be reduced.

**Comment by gparant** [comment]
Hi @ZacharyJia, thanks for your feedback 💪 

For group chat, we are developing a new WorkAdventure chat service through XMPP protocol. We are implementing the Ejaberd server in this merge request #1899
