### ISSUE TITLE
MacOs trackpad user experience

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2152]
On Mac, the trackpad is the reverse of the normal scroll.

When the user is dragging to the left, scroll to the right and reverse.
Similarly for vertical scroll, when the user is dragging up, the scroll must be down.

<img width="1436" alt="Capture d’écran 2022-05-01 à 19 34 45" src="https://user-images.githubusercontent.com/23724509/166157774-36239d94-5602-4db9-8627-7732f6fa5f4a.png">

**Comment by Waclaw-I** [comment]
I believe this is working as intended (@moufmouf )
We are not able to distinguish input devices - Trackpad is basically sending `wheel` events so we treat it as such.
More precisely, if you scroll down with you mouse, the list should go forward (so either down or right), and this is what is happening right now.
