### ISSUE TITLE
Customize scene error

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2153]
In incognito mode the WOKA custom scene is perfect! But when I use my browser with local storage data, there is error (see movie)

https://user-images.githubusercontent.com/23724509/166158035-675411b8-75f9-4b7a-91ab-33c40a18bb64.mov

**Comment by nolway** [comment]
Some times the lost connection scene and woka scene has been superposed.
![image](https://user-images.githubusercontent.com/3711182/166419210-8d936269-06a2-478d-b65f-ccb3d3abd566.png)

**Comment by Waclaw-I** [comment]
@nolway it seems you have an old version still
