### ISSUE TITLE
Problems with uppercase letters in Email

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#2156]
We use SSO to login and have users with uppercase letters in their Email.
If the user was NOT created through admin-dashboard and is logging in, he will be created automatically.
Now if i want to modify the user by adding a tag or add some information I am unable to save it.

It is showing me an error at the Email field. -> "If you want change the email, please delete the member and invite a new".
That does not happen if the Email only has lowercase letters.
Why are no uppercase letters allowed? Email address should be case insenstive

**Comment by gparant** [comment]
Hi @buenni86, yes this fix was merged in new release in test progress 🙌
