### ISSUE TITLE
Can not click on Continue

### ISSUE THREAD

**Issue by buenni86** [thecodingmachine/workadventure#2160]
If you have a laptop with a small resolution or the WorkAdventure window is NOT maximized but instead a small window, you are unable to click "Continue", because the "Powered by WorkAdventure" is on top of it.

![image](https://user-images.githubusercontent.com/12584248/166430136-e9c7d936-de93-4ca2-952a-5207abbee768.png)

**Comment by gparant** [comment]
Thanks for your feedback @buenni86
