### ISSUE TITLE
Translation error of the "away mode" settings

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#2172]
As you can see the away mode wordings are still displayed in EN even if the game language is in DE.
Also, notice that the both sentences have the "Keep camera active" (not microphone).
![image](https://user-images.githubusercontent.com/14997703/167097445-0a3004c5-371e-43d5-b123-8ca908ab8d93.png)

For some reason I can't reproduce it in FR.

**Comment by moufmouf** [comment]
Fixed :+1:
