### ISSUE TITLE
Feature request: Login and curriculum vitae

### ISSUE THREAD

**Issue by LancelotBompard** [thecodingmachine/workadventure#2178]
Hello,
It would be cool to have some kind of login system that would ask you to tell "first name", "last name", "job title".

You could then display these informations by clicking on someone's character when in the bubble so that you can get some informations about the person you're talking with.

**Comment by gparant** [comment]
Hi @LancelotBompard, I don't know if we're referring to the same thing, but this functionality already exists in WorkAdventure:

https://user-images.githubusercontent.com/23724509/167239717-cb003074-7d77-4a27-8b97-8dd2413c0c9c.mov

**Comment by gparant** [comment]
Perfect, don't hesitate if you have any other questions 🚀
