### ISSUE TITLE
Force to load https map

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2219]
I'm trying to check my map builded but I've this error: 

<img width="951" alt="Capture d’écran 2022-05-23 à 18 56 22" src="https://user-images.githubusercontent.com/23724509/169870508-ff6f1fd5-347b-4a68-a19f-4d34e098d6ea.png">

My map is available: 
<img width="1436" alt="Capture d’écran 2022-05-23 à 18 56 34" src="https://user-images.githubusercontent.com/23724509/169870559-b543ad4c-0ee8-460a-9a59-2d598e92ed06.png">

I believe the problem is that we force to get map with protocol `https` and when we use kit starter map in local, the protocol is `http`.

**Comment by moufmouf** [comment]
Normally, there is a fallback mechanism that tries Https first and falls back to http.
Normally, http on a https connection is ok in case http connects to localhost.

**Comment by moufmouf** [comment]
I tried and cannot reproduce this.
@gparant Can we see that on your computer when you are available?
