### ISSUE TITLE
Integrate website iframe into the map

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2220]
I'm trying to integrate website iframe but I can't use fullscreen 😭
[https://workadventu.re/map-building/website-in-map.md](https://workadventu.re/map-building/website-in-map.md)

<img width="1435" alt="Capture d’écran 2022-05-23 à 19 06 32" src="https://user-images.githubusercontent.com/23724509/169871937-164fbc26-be09-4a42-afe8-0aa6ff623815.png">

**Comment by moufmouf** [comment]
Indeed, we lack a map property to set the "allow" attribute!
It is always set to "".

See: http://github.com/thecodingmachine/workadventure/blob/faa43f4240b6a819dde6f885721098c1ba44c7ea/front/src/Phaser/Game/GameScene.ts#L533-L533
