### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by fcecagno** [thecodingmachine/workadventure#2222]
On 1.10.2 we're getting frequent disconnects from the map. We can read on the browser console:
```
Socket closed with code 1006. Reason: 
GameScene.ts:765 Player disconnected from server. Reloading scene.
RoomConnection.ts:552 WebSocket is already in CLOSING or CLOSED state.
emitPlayerShowVoiceIndicator @ RoomConnection.ts:552
```
The auto-reconnect doesn't seem to work properly - although the woka continues being displayed on the map for others, the current player view only the Connection lost screen.

![image](https://user-images.githubusercontent.com/502164/169909085-ffe65e19-5cfd-4619-ae85-78398bc18515.png)

I can confirm it was not affecting 1.9.5.

If there's any other information I can provide, please let me know, we're very interested to have it sorted out.

**Comment by moufmouf** [comment]
Hi @fcecagno ,

Thanks a lot! We are kind of aware of the issue as we encountered it ourselves once or twice.
We are currently looking for a way to reproduce the issue.

If you find a way to reproduce that easily, I'm interested!

**Comment by moufmouf** [comment]
Screenshot of the logs (when closing Wifi connection):

![image](https://user-images.githubusercontent.com/1290952/170033981-c1609a0e-7115-4428-ba2e-01fbbc10d286.png)

It does not seem to be enough to cause the issue as when I restore the Wifi, connection is open again (but with an error message that stays displayed:)

![image](https://user-images.githubusercontent.com/1290952/170034186-8b1bab00-4e2b-4973-8bf3-cee7b95aa332.png)

A few things are wrong in the stacktrace:

- [ ] We try to send a message on the connection but the connection is closed (the message is about turning off the speach indicator)
- [ ] We do this because the system believes we are in a bubble... but we are not! => The stacktrace is going through SimplePeer::closeConnection => so we have an issue with cleaning up the SimplePeer users table

**Comment by fcecagno** [comment]
Hi @moufmouf , we saw this log on the back, at the same time user sees the connection lost screen:

```
An error occurred in listenZone stream: [Error: The async function encountered an error]
```

Would it be an option to try to enrich this log message with some more contextual information, so we can better understand why it happens?

**Comment by moufmouf** [comment]
Oh damn!
This error message comes from gRPC: https://github.com/grpc/grpc/issues/11411
It's almost impossible to understand what is going under the hood (except there is some kind of connection issue between pusher and back)

**Comment by fcecagno** [comment]
Just wanted to add that if we force-close the websocket in the client, it reconnects properly.
So it looks like the issue isn't on the reconnect itself.

**Comment by moufmouf** [comment]
@fcecagno Actually, no need to test that. I've already done it and it does not fix the issue.
It fixes the error messages we see in the console, but the issue turns out to be unrelated to those messages alas.

So back to square one 😥

**Comment by fcecagno** [comment]
Hi @moufmouf , that's OK, let's try to figure out what's going on, I hope we can help on that.

We see on pusher log the following quite often:
```
2022-05-26T12:19:55.063184094Z stderr F Connection lost to back server back-ws:50051' for room 'https://map'
2022-05-26T12:19:55.063140232Z stdout F A user left
2022-05-26T12:19:55.058898528Z stdout F A user left
```

I do not see a reason for the connection to drop, because pusher and back are connected locally, but I might be misunderstanding the meaning of this message. Can it be related to the issue we're pursue?

**Comment by moufmouf** [comment]
Nope, the "Connection lost to back server" seems to trigger each time someone leaves a room. Which is a bit stupid actually.

I'll make some changes to try to have cleaner logs.

**Comment by fcecagno** [comment]
Got it.

Unfortunately we do not see any reason at this moment in the logs OR in the components monitoring that give us any indication on where the problem is.
I think improving the logs might lead to something good, otherwise we are kind of blind in regards to this issue. Is it something impacting severely other deployments as well? What changed from 1.9.5 to 1.10.2 that could have introduced this error?

**Comment by moufmouf** [comment]
I'm not sure yet, but I think I'm onto something.

This is the code that triggers the "reconnecting" screen

http://github.com/thecodingmachine/workadventure/blob/5cc1646f30d906122659bfa26b2918389373fd0e/front/src/Phaser/Game/GameScene.ts#L620-L637

and this is the code that removes it:

http://github.com/thecodingmachine/workadventure/blob/5cc1646f30d906122659bfa26b2918389373fd0e/front/src/Phaser/Game/GameScene.ts#L842-L847


Notice the "setTimeout" of 1 second before displaying the screen.

I'm wondering if somehow, we couldn't have a race condition here. I'm not sure how, because we do check in the setTimeout that this.connection is not null.
Still.... I'm wondering...

**Comment by moufmouf** [comment]
Another possibility!

```
                if (this.scene.isSleeping()) {
                    const error = get(errorScreenStore);
                    if (error && error?.type === "reconnecting") errorScreenStore.delete();
                    //this.scene.stop(ReconnectingSceneName);
                }
```

If for some reason the scene is NOT sleeping, this will not be triggered.
We know that the scene is probably not sleeping because we can be seen on the map when the "reconnecting" scene is displayed.

The question: WHY wouldn't the scene be sleeping?

**Comment by moufmouf** [comment]
I hope #2232 will help move this forward.

**Comment by fcecagno** [comment]
@moufmouf would it be possible to use a log in the pusher to add more information on disconnections?
I think it's very important to have a proper working reconnect mechanism, but also try to investigate the disconnections in order to try to minimize the occurrences. In this area, I know posthog can be used to keep track of some user actions - would it make sense to register on posthog disconnection related activities as well?

**Comment by fcecagno** [comment]
> I hope https://github.com/thecodingmachine/workadventure/pull/2232 will help move this forward.

We'll try it next week. :)

**Comment by fcecagno** [comment]
> I'm wondering if somehow, we couldn't have a race condition here. I'm not sure how, because we do check in the setTimeout that this.connection is not null.

That's most likely the case - last time it occurred here, I look at the logs and saw three occurrences of the following log:
```
RoomConnection.ts:747 Socket closed with code 1006. Reason:
GameScene.ts:765 Player disconnected from server. Reloading scene.
RoomConnection.ts:949 Trying to send a message to the server, but the connection is closed. Message:  Object
send @ RoomConnection.ts:949
```

But only on the last occurrence, the screen get locked on the Connection Lost screen.

**Comment by fcecagno** [comment]
Hi @moufmouf, just wanted to confirm the PRs linked here have fixed the issue for us. In fact, since we're using ingress-nginx default timeouts for websockets, users were reconnecting pretty often when idle (15 times per hour), that's why this issue impacted us so badly. Now we're testing the following annotations for pusher:
```
nginx.ingress.kubernetes.io/proxy-read-timeout: "21600"
nginx.ingress.kubernetes.io/proxy-send-timeout: "21600"
```
Thanks for your help.
