### ISSUE TITLE
Talking icon

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2239]
I don't see a talking icon: 

<img width="706" alt="Capture d’écran 2022-05-31 à 16 20 39" src="https://user-images.githubusercontent.com/23724509/171210693-8cece946-c6cb-4bee-94b1-75ee9e273e30.png">

**Comment by Waclaw-I** [comment]
Should be fixed with https://github.com/thecodingmachine/workadventure/pull/2396
