### ISSUE TITLE
Bug: bubble conversation stops working after awhile and requires reload

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2254]
We have started onboarding a lot of our collaborators in our self hosted WA instance and though most of the time everything works fine, I heard quite some complains about the bubble stop working after sometime. Leaving the bubble and joining it back doesn't fix the issue and the user is required to refresh the browser to make it work again.

In one instance, I got a screenshot of the user debug console at the time it stopped working

![image](https://user-images.githubusercontent.com/96873/171937876-091876f5-bef7-42b3-a36f-b1d699df7632.png)

Version: 1.10.0

**Comment by moufmouf** [comment]
Hi @taksan ,

Thanks a lot for the screenshot, we are taking a look!

Ping @Waclaw-I

**Comment by moufmouf** [comment]
@taksan Could you tell me what tag is deployed on your server? (or is it the master branch?)

Or even better, if this happens again, could you show me the lines of code around GameScene.ts:706 (by clicking on the link in the developer console?)

And also the lines of code around Character.ts:240

I'm pretty sure it has to do with this.

**Comment by taksan** [comment]
Tag: v1.10.0

I'll tell people to get lines of code  in that case

**Comment by taksan** [comment]
Well, it just happened to me. Here are the details:

Around GameScene.ts:706
```ts
        this.jitsiParticipantsCountStoreUnsubscriber = jitsiParticipantsCountStore.subscribe((participantsCount) => {
            this.jitsiParticipantsCount = participantsCount;
            this.tryChangeShowVoiceIndicatorState(this.jitsiDominantSpeaker && this.jitsiParticipantsCount > 1);
        });

        availabilityStatusStore.subscribe((status) => {
            this.connection?.emitPlayerStatusChange(status);
            this.CurrentPlayer.setStatus(status);
        });

        this.emoteUnsubscribe = emoteStore.subscribe((emote) => {
            if (emote) {
                this.CurrentPlayer?.playEmote(emote.url);
                this.connection?.emitEmoteEvent(emote.url);
                emoteStore.set(null);
            }
        });
```

![image](https://user-images.githubusercontent.com/96873/172449658-32adc255-998d-4977-9835-5759e78142f5.png)


Character.ts:240
```
    private async getSnapshot(): Promise<string> {
        const sprites = Array.from(this.sprites.values()).map((sprite) => {
            return { sprite, frame: 1 };
        });
        return TexturesHelper.getSnapshot(this.scene, ...sprites).catch((reason) => {
            console.warn(reason);
            for (const sprite of this.sprites.values()) {
                // we can be sure that either predefined woka or body texture is at this point loaded
                if (sprite.texture.key.includes("color") || sprite.texture.key.includes("male")) {
                    return this.scene.textures.getBase64(sprite.texture.key);
                }
            }
            return "male1";
        });
    }

    public showTalkIcon(show: boolean = true, forceClose: boolean = false): void {
        this.talkIcon.show(show, forceClose);
    }

    public setStatus(status: AvailabilityStatus, instant: boolean = false): void {
        this.statusDot.setStatus(status, instant);
    }

    public addCompanion(name: string, texturePromise?: CancelablePromise<string>): void {
        if (typeof texturePromise !== "undefined") {
            this.companion = new Companion(this.scene, this.x, this.y, name, texturePromise);
        }
    }
```

![image](https://user-images.githubusercontent.com/96873/172449570-39557960-ab76-4e0a-93d4-596c8b52d86d.png)

**Comment by Waclaw-I** [comment]
Error shown here is the same as in this issue:
https://github.com/thecodingmachine/workadventure/issues/2263

I will reopen this issue if problem with bubble conversation will still occur in newer version.
