### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by blastmaster** [thecodingmachine/workadventure#226]
Hi, under which license this project is distributed? I could not found any information on the repository.
Can you please provide license information? Thanks in advance.

**Comment by moufmouf** [comment]
Hey @blastmaster ,

The license is "hidden" in both "front" and "back" directories.
The current license is "AGPL + Commons Clause".

The idea is that you can install / modify / redistribute WorkAdventure but:

- if you make any changes, you need to redistribute the source code
- you are not allowed to sell a SAAS version of WorkAdventure ("commons clause" is the "anti-amazon" clause)

This is the same license used by [Neo4J](https://github.com/neo4j/neo4j/blob/3.5/packaging/LICENSE.txt)

WorkAdventure is actually quite a young project and you are the first one asking about the license (so we have not has the opportunity yet to assess whether this license choice is good or not). I'd be interested to gather any feedback. Do you think about any use case in particular and does the license as it currently stands allow for this use case or not?

Regards!

**Comment by PaulPetring** [comment]
Thanks for the Info. This very is helpful :)
