### ISSUE TITLE
Error lock circle button

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2267]
After some minutes with locked circle, the button switching off while the circle conversation still locked.
(there is no error in the navigator console)

<img width="1303" alt="Capture d’écran 2022-06-08 à 16 48 15 3" src="https://user-images.githubusercontent.com/23724509/172648320-285f8579-8d48-4fa8-9d6e-20eee87aa484.png">

<img width="1050" alt="Capture d’écran 2022-06-08 à 16 47 44" src="https://user-images.githubusercontent.com/23724509/172648594-275a685f-ebde-4bcc-a0ac-f4a84221fe7d.png">

**Comment by Waclaw-I** [comment]
How to reproduce:
- Create and lock one group
- Create a separate group and close it

Lock icon will change its state. Fixed in:
https://github.com/thecodingmachine/workadventure/pull/2275
