### ISSUE TITLE
Tile not visible emit onEnterLayer subscribe event.

### ISSUE THREAD

**Issue by E-OssO** [thecodingmachine/workadventure#2318]
This comporment produce a lot of problem when you use script to show/hide layer

**Comment by E-OssO** [comment]
I do a map to explain the problems.

You have 3 rooms.

Room1 is the left one, Room2 the center and Room3 the right

Room1 : 
The problem is the onEnterLayer on hidden layer.
In this room i have a hidden layer. But, if you enter the room you get the console.log of this layer with attribut visible to false.

Room2 : 
The layer attribut visible/property are not updated by function WA.room.showLayer/WA.room.hideLayer/WA.room.setProperty
So we can't implement a toggle pattern.

Room3 :
In this room, i try to move a layer. But the old position are still trigger onEnterLayer.

The map project is :
https://github.com/E-OssO/wa

**Comment by gparant** [comment]
Hi @E-OssO, yes it's not possible to use `visible` property because is not updated in the file. 
So there is another possibility to use state, I create pull request on your project to use it: https://github.com/E-OssO/wa/pull/1  🚀

**Comment by E-OssO** [comment]
Sorry, but i don't want a solution. i have already implemented it. All i do is to report improvement.
You have a memory version of first display state. Your function doesn't update this version and this is very unfortunate.

In my main project i use my own function to wrap your and update visible/properties and it work well ;)

```
export type LayerPropertyValue = string | number | boolean | undefined;
layer: {
        show: async (layerName: string) => {
            const layers = await getLayersMap();
            const layer = layers.get(layerName);
            if (layer) {
                layer.visible = true;
                WA.room.showLayer(layerName);
            }
        },
        hide: async (layerName: string) => {
            const layers = await getLayersMap();
            const layer = layers.get(layerName);
            if (layer) {
                layer.visible = false;
                WA.room.hideLayer(layerName);
            }
        },
        setProperty: async (layerName: string, propertyName: string, propertyValue: LayerPropertyValue) => {
            const layers = await getLayersMap();
            const layer = layers.get(layerName);
            if (layer) {
                let property = layer.properties?.find((p) => p.name === propertyName);
                if (property) {
                    property.value = propertyValue;
                } else {
                    layer.properties?.push({ name: propertyName, value: propertyValue, type: typeof propertyValue });
                }
                WA.room.setProperty(layerName, propertyName, propertyValue);
            }
        },
    }
```

**Comment by gparant** [comment]
Ok perfect, this issue was already reported on our scripting extra project 🚀 
https://github.com/workadventure/scripting-api-extra/issues/153

Thanks
