### ISSUE TITLE
WA.room function showLayer/hideLayer/setProperty doesn't update layer object

### ISSUE THREAD

**Issue by E-OssO** [thecodingmachine/workadventure#2324]
The function on WA.room doesn't update layers object. They work on display. But not to know the current state of display.

Sample with hidden layer
```
let layerName = 'XXX';
WA.room.showLayer(layerName);
const layers = await getLayersMap();
const layer = layers.get(layerName);

// layer.visible is still false

```

**Comment by gparant** [comment]
Issue reported in our scripting project => https://github.com/workadventure/scripting-api-extra/issues/153
