### ISSUE TITLE
404 FILE NOTE FOUND

### ISSUE THREAD

**Issue by lotfiidir** [thecodingmachine/workadventure#236]
![Screen 1-before error](https://user-images.githubusercontent.com/16717662/88911865-c3aee800-d25e-11ea-8d6e-4811442f69aa.png)

When i enter the map TCM:// (look screen 1-before error) i got this error 

![Capture d’écran du 2020-07-30 12-14-53](https://user-images.githubusercontent.com/16717662/88911637-66b33200-d25e-11ea-9f98-5b6e856bf89b.png)

**Comment by moufmouf** [comment]
:+1: This is related to the corridor map and will be fixed when https://github.com/npeguin/corridor-map/pull/4 is merged.

**Comment by AiyionPrime** [comment]
#4 got merged a while ago. And while this isn't a problem on the public server very often, it's a pity that this is not caught before one actually enters a door;
or, if that alone would increase loading times upon entering doors significantly, let the players browseer test all? exits upon entering a level and check them before the player is even near them.

**Comment by moufmouf** [comment]
@AiyionPrime Thanks for the suggestion. It would be great to have a way to find these kind of errors while deploying the map. We'll try to think about something along those lines.
