### ISSUE TITLE
"Talking" icon shows up even in a silent zone

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#2369]
So all the red seats area is silent. But I saw one guy "David" at the left with this "talking" icon above him.

![Capture d’écran de 2022-07-02 17-40-03](https://user-images.githubusercontent.com/14997703/177010612-f08cbaeb-d517-4a58-8a55-6622a2bce0df.png)

Don't know why, don't have logs and everything because it was not my PC, but this is **very bad from the user's point of view** because they will start thinking that WorkAdventure listen to them secretly.

**Comment by Waclaw-I** [comment]
Should be fixed with: https://github.com/thecodingmachine/workadventure/pull/2396
