### ISSUE TITLE
BUG in documentation

### ISSUE THREAD

**Issue by Jahe0010** [thecodingmachine/workadventure#2383]
Hey,

I think i found a bug in the documentation.Its about the PopUps. You assing the returnnof a subscription to a variable but the variable assignment should be inside the subscrption block. Shouldnt it? 

https://workadventu.re/map-building/api-ui.md

Kind regards,
Freakz

**Comment by moufmouf** [comment]
Oh, gee. Of course! Thanks for the notice!

**Comment by moufmouf** [comment]
Fixed in #2385.

PS: there is an edit link at the bottom of each pages of the documentation if you prefer to propose changes directly :heart:
