### ISSUE TITLE
Refactor the GameMap

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2387]
The way the `GameScene`, `GameMap`, `GameMapPropertiesListener` and `PathFindingManager` work together is a bit problematic.

We have a lot of places where we don't properly listen to changes in the GameMap.
For instance, if we edit tiles on a layer, the `GameMapPropertiesListener` 

http://github.com/thecodingmachine/workadventure/blob/147124633cd7b76ddaed383ab444f4c116dbddf8/front/src/Phaser/Game/GameScene.ts#L1572-L1597

Let's take a look at this code in `GameScene`:

```
    private setLayerVisibility(layerName: string, visible: boolean): void {
        const phaserLayer = this.gameMap.findPhaserLayer(layerName);
        let collisionGrid: number[][] = [];
        if (phaserLayer != undefined) {
            phaserLayer.setVisible(visible);
            phaserLayer.setCollisionByProperty({ collides: true }, visible);
            collisionGrid = this.gameMap.getCollisionGrid(phaserLayer);
        } else {
            const phaserLayers = this.gameMap.findPhaserLayers(layerName + "/");
            if (phaserLayers.length === 0) {
                console.warn(
                    'Could not find layer with name that contains "' +
                        layerName +
                        '" when calling WA.hideLayer / WA.showLayer'
                );
                return;
            }
            for (let i = 0; i < phaserLayers.length; i++) {
                phaserLayers[i].setVisible(visible);
                phaserLayers[i].setCollisionByProperty({ collides: true }, visible);
            }
            collisionGrid = this.gameMap.getCollisionGrid(undefined, false);
        }
        this.pathfindingManager.setCollisionGrid(collisionGrid);
        this.markDirty();
    }
```

This function has 4 responsibilities:

- setting the visibility in GameMap
- editing the Phaser layer (and reconfiguring collisions)
- then re-generating the collision grid in the GameMap
- and finally putting that collision grid in the PathFindingManager

Assuming we edit a single layer for a single tile, we should probably do the same thing.

We could probably have something way cleaner.

Here is a proposition:

Any way to edit the map is directly exposed on the `GameMap` object.

For instance:

`gameMap.setVisible(layerName: string, visible: bool)`

Then, the GameMap class emits events (or contains an observer) that fires on each map change.

Ideally, the `PathFindingManager` is never called directly when a map changes. Instead, it reacts to the events triggered by the GameMap.

TODO:

- [x] `GameMap.setLayerVisibility` method should be added
- [x] `GameMap.putTile` should trigger an event (listened by the `PathFindingManager`)
- [ ] The `PathFindingManager` should recompute the shortest path (not on each event received but once per frame if an event was received)

**Comment by Waclaw-I** [comment]
It was so long ago that it probably changed two more times. Closing
