### ISSUE TITLE
Upgrade map in place

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2389]
On a big map (like the one added in the test map that weights 17MB), I see this:

![image](https://user-images.githubusercontent.com/1290952/177339808-71873232-23ca-481d-be11-2d04da12f53a.png)

The new `upgradeMapToNewest` takes about 500ms to execute (so longer than the optimized collision grid computation)

I'm pretty sure this is because of:

https://github.com/workadventure/tiled-map-type-guard/blob/a637b8ab7c78ac78e46a5439df77623ff2f778b8/src/utility.ts#L5

```
const newMap: ITiledMap = JSON.parse(JSON.stringify(map));
```

We could add a "boolean" property that allows editing the object in place (rather than making a copy).
In our case, we are already making this copy just before, using the new "structuredClone" method.

**Comment by Waclaw-I** [comment]
https://github.com/workadventure/tiled-map-type-guard/pull/16
