### ISSUE TITLE
Prompt=login parameter is hardcoded in OpenID configuration

### ISSUE THREAD

**Issue by fvztdk** [thecodingmachine/workadventure#2429]
The Prompt=login parameter is hardcoded in OpenID configuration, that causes some ID providers (i.e. Okta) to asks the user to provide again their password, even when they are already logged in and have a valid token.

What is the use case that made you add this parameter initially?

We tested the request without the parameter and it produces the expected behaviour (completes the SSO flow)

Maybe this should be parametrised like the other parameters of the configuration or removed from completely. We are trying to understand the requirements so we can propose a PR. 

https://github.com/thecodingmachine/workadventure/blob/57f0dcfcb23986204818a62d1d9d4828a2242e94/pusher/src/Services/OpenIDClient.ts#L34-L41

**Comment by gparant** [comment]
I think that it's a good idea to propose another value for the "prompt" parameter. Today we use hydra with a certain setting and we need to use "prompt". 
So we could imagine having another environment variable for that like `OPID_SCOPE`?

**Comment by fvztdk** [comment]
That's the idea, we'll propose a PR adding a new env var like `OPID_PROMPT` with the default value as login so we don't change the default behaviour.

We'll try to do it in the next few days.

**Comment by fvztdk** [comment]
I opened the PR #2472

**Comment by moufmouf** [comment]
Thanks a lot for the PR @fvztdk .
It's merged :+1:
