### ISSUE TITLE
Unable to connect Workadventure... locally 

### ISSUE THREAD

**Issue by esra9910** [thecodingmachine/workadventure#2447]
Hello everyone,
I have Problems to run my WA locally(in my UbuntuVM). I pulled the code from Github and try to run it with docker with the command **docker-compose up** and open this l**ink http://play.workadventure.localhost/** but all I got it this error:

**Error! unable to connect to Workadventure. Are you connected to the internet?**

 I'm connected to the internet but I don't know why this isn't working... 
I have some questions too:
- Is it necessary to install Traefik or can we use it without?

Pls help mee. I appreciate  all help and informations.
Thank youuuu!!! ^^

**Comment by franckya** [comment]
Same for me. I am having the same issue.

**Comment by gparant** [comment]
Today you could use something else than Traefik, it's just a reverse proxy to communicate between docker service. 
The problem might come of `pusher` or `back` service, have you any logs to share us?

**Comment by franckya** [comment]
Hi @gparant ,
Could you share the proper docker-compose.yaml file and the .env file to use? Everything that I found and used isnt working.

**Comment by gparant** [comment]
Hello, you share with us the logs of pusher, back and navigator when you try to connect to WorkAdventure?

**Comment by gparant** [comment]
For the development, you can use the same file that `.env.template` and the same file that docker-compose.yaml in our last version.

If you have an error, could you please share with us more details of logs for the service `pusher`, `back` and navigator.

**Comment by esra9910** [comment]
Hello,
I solved the Problem: 
 I clone the Github repository from the 2nd August (It works for me but you can use the current one)
https://github.com/thecodingmachine/workadventure/tree/1aa0b997bf650cf4c346c5a377af8cb24f5534aa

and enable the Port 8080 in my Server and it worked!
Here is a link that helps:
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-20-04
