### ISSUE TITLE
Setup support for temporary TURN passwords

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#245]
Currently the user/password of the TURN server used by WorkAdventure is hard coded in the config and shared with every single user.
We should be able to support TURN server that provides Time-Limited Credentials Mechanism (like coturn).

**Comment by moufmouf** [comment]
See https://stackoverflow.com/questions/35766382/coturn-how-to-use-turn-rest-api/54725092

**Comment by Kharhamel** [comment]
this was done
