### ISSUE TITLE
 Lets encrypt Email- which one?--Setup WA Project --

### ISSUE THREAD

**Issue by esra9910** [thecodingmachine/workadventure#2457]
Hello,
I follow this Documentation : https://wiki.techinc.nl/Work-Adventure/install
And i want to setup my WA Projekt but before that i create the directory /opt/traefik-infra/ and in the directory the File .env. 

I copy this in the empty .env File:

DOMAIN=some.domain.tld
#These are not used yet
TURN_SERVER=
TURN_USER=
TURN_PASSWORD=

**# The email address used by Let's encrypt to send renewal warnings (compulsory)
ACME_EMAIL=my_letsencrypt_contact@email.address**
#The directory on your OS that Traefik will store all ACME-produced certs in
CERT_LOCATION=/etc/traefik/acme

My Question is can we use a normal email for the Section ACME-EMAIL or did we need/create a new lets encrypt Email-adresse. When the Answer is yes, how can I create that?Can you help me?

Thank you very much:)

**Comment by franckya** [comment]
I have used my email for my letsencrypt. Many people say that using that is fine, so I will guess you can use your own.

**Comment by esra9910** [comment]
Oh thank you very much !!  :)

**Comment by franckya** [comment]
@esra9910  I have a question, were you able to get your workadventure up and running?

**Comment by esra9910** [comment]
@franckya No, I struggle with problems.

**Comment by esra9910** [comment]
@franckya  the HTTPS Certificate does work a bit. In the URL it shows https:// but the website say the connection is not secure. Did you know why?

**Comment by franckya** [comment]
same here. My issue is that I am getting a "Unable to connect to workadventure, are you connected to the internet?" Is this the same for you?

**Comment by franckya** [comment]
I believe that is the letsencrypt.

**Comment by esra9910** [comment]
No my website shows me that the connection is not secure and the WA Project doesn't show :(

**Comment by franckya** [comment]
Are you getting the 404 message? Send your screenshot.

**Comment by esra9910** [comment]
It only says potential security risk identified

**Comment by esra9910** [comment]
in the Traefik-infra directory?

**Comment by esra9910** [comment]
version: '3'

services:
    reverse-proxy:
      image: traefik:v2.3
      command:
        - --log.level=WARN
        #- --api.insecure=true
        - --api.dashboard=true
        - --providers.docker.network=web
        - --providers.docker
        - --entryPoints.web.address=:80
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - --entryPoints.websecure.address=:443
        - --entryPoints.video.address=:10000/udp
        - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
        - --certificatesresolvers.le.acme.storage=/etc/traefik/acme/acme.json
        # used during the challenge
        - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      ports:
        - "80:80"
        - "443:443"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "${CERT_LOCATION}:/etc/traefik/acme"
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=888"
        - "traefik.http.routers.traefik.rule=Host(`admin.${DOMAIN}`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=le"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        # You should modify the line below to set a password for your Traefik-dashboard
        - "traefik.http.middlewares.traefik-auth.basicauth.users=admin: #myhashedpsw"
      networks:
        web:
        meet.jitsi:

# Still working on a useful COTURN setup. Included for later use.
#    coturn:
#      image: coturn/coturn:4.5.2
#      command:
#        - turnserver
#        - --log-file=stdout
#        - --external-ip=$$(detect-external-ip)
#        - --listening-port=3478
#        - --min-port=10000
#        - --max-port=10010
#        - --tls-listening-port=5349
#        - --listening-ip=0.0.0.0
#        - --realm=coturn.${DOMAIN}
#        - --server-name=coturn.${DOMAIN}
#        - --lt-cred-mech
#        # Enable Coturn "REST API" to validate temporary passwords.
#        # - --use-auth-secret
#        # - --static-auth-secret=SomeStaticAuthSecret
#        # - --userdb=/var/lib/turn/turndb
#        - --user=workadventure:WorkAdventure123
#        # use real-valid certificate/privatekey files
#        # - --cert=/root/letsencrypt/fullchain.pem
#        # - --pkey=/root/letsencrypt/privkey.pem
#      network_mode: host
 
networks:
  meet.jitsi:
  web:
    external: true
