### ISSUE TITLE
Workadventure doesn't work

### ISSUE THREAD

**Issue by esra9910** [thecodingmachine/workadventure#2459]
Hello,
I follow this Documentation: https://wiki.techinc.nl/Work-Adventure/install and this Tutorial: https://www.youtube.com/watch?v=NQrxne7lS34 to Self host my WA-Project but it didnt work.

I have also problems to start it locally, but I couldn't find a solution, so I thought it doesn't work because of the Traefik Container in Docker. So I tried the Tutorial and Documentation but it doesn't work.

Can someone help me?
 I appreciate any help or informations. 

Thank you:)

**Comment by gparant** [comment]
Curse, would you be able to share your docker composition file and the error found when you try to launch the project?

**Comment by esra9910** [comment]
version: '3'

services:
    reverse-proxy:
      image: traefik:v2.3
      command:
        - --log.level=WARN
        #- --api.insecure=true
        - --api.dashboard=true
        - --providers.docker.network=web
        - --providers.docker
        - --entryPoints.web.address=:80
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - --entryPoints.websecure.address=:443
        - --entryPoints.video.address=:10000/udp
        - --certificatesresolvers.le.acme.email=${ACME_EMAIL}
        - --certificatesresolvers.le.acme.storage=/etc/traefik/acme/acme.json
        # used during the challenge
        - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      ports:
        - "80:80"
        - "443:443"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "${CERT_LOCATION}:/etc/traefik/acme"
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.traefik.loadbalancer.server.port=888"
        - "traefik.http.routers.traefik.rule=Host(`admin.${DOMAIN}`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=le"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        # You should modify the line below to set a password for your Traefik-dashboard
        #- "traefik.http.middlewares.traefik-auth.basicauth.users=#hashedmyadmin:"
      networks:
        web:
        meet.jitsi:

# Still working on a useful COTURN setup. Included for later use.
#    coturn:
#      image: coturn/coturn:4.5.2
#      command:
#        - turnserver
#        - --log-file=stdout
#        - --external-ip=$$(detect-external-ip)
#        - --listening-port=3478
#        - --min-port=10000
#        - --max-port=10010
#        - --tls-listening-port=5349
#        - --listening-ip=0.0.0.0
#        - --realm=coturn.${DOMAIN}
#        - --server-name=coturn.${DOMAIN}
#        - --lt-cred-mech
#        # Enable Coturn "REST API" to validate temporary passwords.
#        # - --use-auth-secret
#        # - --static-auth-secret=SomeStaticAuthSecret
#        # - --userdb=/var/lib/turn/turndb
#        - --user=workadventure:WorkAdventure123
#        # use real-valid certificate/privatekey files
#        # - --cert=/root/letsencrypt/fullchain.pem
#        # - --pkey=/root/letsencrypt/privkey.pem
#      network_mode: host
 
networks:
  meet.jitsi:
  web:
    external: true



here is the docker-compose.file


When I run Traefik and docker my Workadventure project doesn't open.

**Comment by franckya** [comment]
Hey @gparant  I am having the same issue, and I would like to know how to fix it. Please let me know if there is anything additional I can provide to be helpful.

**Comment by gparant** [comment]
Hello, you share with us the logs of pusher, back and navigator when you try to connect to WorkAdventure?

**Comment by LarsFlieger** [comment]
I tried to use the production docker out of the box: https://github.com/thecodingmachine/workadventure/tree/master/contrib/docker
But it's not working. First the ports definition in the docker files were wrong: 
```yml
services.reverse-proxy.ports contains an invalid type, it should be a number, or an object
services.reverse-proxy.ports contains an invalid type, it should be a number, or an object
```
after fix this the reference format is invalid:
```yml
ERROR: no such image: thecodingmachine/workadventure-front:: invalid reference format
```

Maybe we should update the production example?

**Comment by esra9910** [comment]
@LarsFlieger should I place the new folder in the contrib/docker Directory or outside?

**Comment by moufmouf** [comment]
In production, you don't need to "git clone" the project.

The `docker-compose.prod.yaml` and `.env` files are enough to start a full environment.
The `docker-compose.prod.yaml` refers to images stored on Docker Hub.

**Comment by esra9910** [comment]
@moufmouf You mean I don't need the Github repository? 
the docker-compose.prod.yaml start it automatically? 
But how can I connect to my created Map (should I paste my created map-link in the .env- File?)

**Comment by esra9910** [comment]
@LarsFlieger I tried what you said but my page show me the 404 Error Page not found. 
I change the .env file too my Serveradresse but I didn't work for me.

**Comment by LarsFlieger** [comment]
> @moufmouf You mean I don't need the Github repository? the docker-compose.prod.yaml start the WA-Project automatically? But how can I connect to my created Map (should I paste my created map-link in the .env- File?)

Yes, just a folder with the two files: 
![image](https://user-images.githubusercontent.com/47084064/185925971-e1cc3aef-3ae1-4c09-88bd-42e5d7fa4f5e.png)

Yes, I think you can set the default map via this in the env file:
```yml
# The URL used by default, in the form: "/_/global/map/url.json"
START_ROOM_URL=/_/global/thecodingmachine.github.io/workadventure-map-starter-kit/map.json
```

**Comment by LarsFlieger** [comment]
> @LarsFlieger I tried what you said but my page show me the 404 Error Page not found. I change the .env file too my Serveradresse but I didn't work for me.

When you launch it with docker compose it should work out of the box without the need to modify the .env.

**Comment by esra9910** [comment]
I did it and the Project open itself runs in the Port 9999, but when I type my public Ip Adresse of my machine. 
With my Domain name my WA-Project doesn't open.
 I don't know why?

**Comment by LarsFlieger** [comment]
> I did it and the Project open itself runs in the Port 9999, but when I type my public Ip Adresse of my machine. With my Domain name my WA-Project doesn't open. I also start my Nginx Proxy Manger. I don't know why?

If it's working on your machine where you started the docker your problem is not related to this issue anymore. You could try to google or aks on stackoverflow :)

**Comment by esra9910** [comment]
Thanks for your help, you really saved me :)
