### ISSUE TITLE
Setup a scaling STUN servers architecture

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#246]
In order to be able to scale TURN servers (and still get turns support with Let's Encrypt certificates), we need to:

- setup an Amazon image with Coturn
- Setup a unique AWS machine whose goal is to:
    - Get certificates using certbot + DNS01 requests (which implies switching DNS to Route 53 since OVH DNS does not support DNS01 requests)
    - Share the certificates in a NFS drive
    - Renew the certificates
    - Act as a Redis server containing coturn credentials

- setup an autoscaling group of coturn images
- setup Route53 to do round-robin DNS on the autoscaling group (see insipiration here: https://stackoverflow.com/questions/57803903/updating-route-53-automatically-when-auto-scaling-brings-up-new-instance) => a single domain should reach randomly any server

**Comment by moufmouf** [comment]
Done: only thing missing is a dynamic scaling of the instances.

**Comment by Kharhamel** [comment]
closing for now
