### ISSUE TITLE
The camera is active even if not enabled

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#248]
Hi!

My camera is still activated even if I've disabled it via the bottom right button.
It's kind of strange :).

(I can tell because on macOS we have a light next to the camera when it's active.)

**Comment by moufmouf** [comment]
Salut Jacques!

Glad you are having a look at WorkAdventure! :)

Indeed! I confirm I can reproduce the bug on my Dell XPS too.
We'll look into that. WebRTC can be hard core at times :D

**Comment by moufmouf** [comment]
Thanks for notifying us! Indeed, the camera was not properly closed on the "enable your webcam screen", causing a kind of leak.

This should be fixed now!
