### ISSUE TITLE
Follow window obscures trigger message window

### ISSUE THREAD

**Issue by ialja** [thecodingmachine/workadventure#2484]
When players follow each other, the follow notice is overlayed over the trigger message window at the bottom of the screen, so the trigger message cannot be read. This is an issue for both the player being followed and the one following.

<img width="719" alt="follow-vs-trigger_message" src="https://user-images.githubusercontent.com/1607407/185055914-d40550f9-11f2-4aed-b986-fdc8b01c3804.png">

**Comment by nolway** [comment]
Thank you for your feeback we will fix that bug in the next release =)
