### ISSUE TITLE
WorkAdventure-starter-kit doesn't work on Github page

### ISSUE THREAD

**Issue by esra9910** [thecodingmachine/workadventure#2487]
Hello everyone,
i want to test my created Map, so I replace the map.json on the branche gh-pages to test my Map on the Github livepage , but unfortunately it doesn't show me my created map there is only black screen. Can someone help me out?

**Comment by gparant** [comment]
Could you please send me your map project to check the problem?

**Comment by esra9910** [comment]
yes of course 
https://github.com/esra9910/waproject.git

**Comment by gparant** [comment]
Thanks, what is your gh-pages public URL?

**Comment by esra9910** [comment]
I think it is this https://play.workadventu.re/_/global/esra9910.github.io/waproject/map.json ?

**Comment by gparant** [comment]
I can't open your project map with Tiled, how have you built your map?

**Comment by esra9910** [comment]
I have build it in Tiled and import it to the Github Repository, all Tilesets are in the map.json.

**Comment by esra9910** [comment]
also the created map is in the gh-pages branche

**Comment by gparant** [comment]
Could you try to push your changes on the master branch? With the starter-kit project, we have the GitHub action that build, optimize your map / file and push it automatically in gh-pages?

**Comment by esra9910** [comment]
Ok I give it a try..
so I must push the changes of the master branche to the gh-pages brand right?

**Comment by gparant** [comment]
No, just replace your map.json file with all png files in the Master branch. Will be automatically pushed on gh-pages branch.

**Comment by esra9910** [comment]
also the Tiltsets.png or only the map.png?

**Comment by esra9910** [comment]
got an Network Error.
![image](https://user-images.githubusercontent.com/65394101/185356846-03a94563-25de-48a7-979a-e88557df8934.png)

**Comment by gparant** [comment]
Yes, the url https://esra9910.github.io/waproject/map.json is broken. Do you have errors in Github action?

**Comment by gparant** [comment]
Really weird, have this error with my Tiled

<img width="1507" alt="Screenshot 2022-08-18 at 11 13 15" src="https://user-images.githubusercontent.com/23724509/185358277-be462c79-0281-4688-9644-acb2f6b0db6c.png">

**Comment by esra9910** [comment]
No I haven't. I only clone the WorkAdventure-starter-kit to my new repository and replace the map.json and the map.png.

**Comment by gparant** [comment]
Have you `clone` or `use this template`?

**Comment by esra9910** [comment]
I have cloned the WorkAdventure starter kit but use my own created map.json.

**Comment by gparant** [comment]
Ok, if you want correctly use our kit-starter without change the core of them. You can click on `use this template`, create your own map project and replace your map.json and all file in your project on `main` branch. Thus our optimiser could build your map, files and push it on gh-pages.

There is tuto here => https://workadventu.re/map-building/
