### ISSUE TITLE
Typing space in chat triggers Co-Website

### ISSUE THREAD

**Issue by kaeff** [thecodingmachine/workadventure#2489]
We noticed that CoWebsites are triggered even if the chat side window is open. 

Steps to reproduce
1. Open a map with a CoWebsite or Jitsi that uses a trigger - [example: starter-kit on staging](https://play.staging.workadventu.re/_/e9widdjloah/kaeff.github.io/workadventure-maps/map.json)
2. Walk into the trigger area
3. Open chat and type space

Expected behavior: Space is appended to chat message
Actual behavior: Space is appended to chat message **and CoWebiste is triggered**

Reproduced on v1.11.4 and `staging.workadventu.re` today.

This can be confusing to users - a user of our instance reported this because we use `onWebsiteTrigger` in the start area to show a "New here? Press SPACE to open user guide" first-user-guidance.

Suggestion would be to disable the CoWebsite trigger while the chat message input has focus.

**Comment by moufmouf** [comment]
Thanks for the issue! We'll look into it!

**Comment by moufmouf** [comment]
This is now fixed with the release of the new chat window (that will be deployed in production in the coming weeks, already available in "master" branch).
