### ISSUE TITLE
It seems we can't be more than 2 in a circle to have a proper conversation

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#249]
Hi!

We've tested with some colleagues and it seems that we can't we 3 of us in the same circle.

I mean. Let's say: Bob, Alice and Douglas are in the circle.

Bob can talk to Alice and Douglas.
But Douglas and Alice can't talk to each other.

We use our headphones to be sure it's not sound travel :).

**Comment by moufmouf** [comment]
Damn!
I have no issues when testing locally. I can confirm I can talk with colleagues up to 4 people in a circle.

I just made a huge release. It adds a number of features and refactors a lot of code.

Could you let me know if you still see this issue?

(note that the new feature brings a few interesting things like screen sharing (button at the bottom right) and an integration with Jitsi meet (if you are walking near the coaches or in the meeting room)

If you are still seeing the issue, is there anything special in the console of your browser?

**Comment by jacquesbh** [comment]
Amazing the integration with Jitsi!! Really cool.

We'll test tomorrow.

**Comment by jacquesbh** [comment]
Worked well, 3 people with mic and camera.
