### ISSUE TITLE
Support single domain

### ISSUE THREAD

**Issue by sesmi123** [thecodingmachine/workadventure#2499]
Hi,

The current docker container deployment creates the services in different domains. Is it possible to bring them under a single domain and access like https://domainXYZ/play, https://domainXYZ/maps etc.?

**Comment by moufmouf** [comment]
The docker-compose.yaml at the root of the project is for development only.

If you are looking at production install, you need to look in the /contrib/docker directory.
There is a [docker-compose.single-domain.yaml](https://github.com/thecodingmachine/workadventure/blob/develop/contrib/docker/docker-compose.single-domain.yaml) file there. (it hasn't been tested in a while but it should work)

**Comment by sesmi123** [comment]
Thanks a lot, I will try with that.
