### ISSUE TITLE
Staging Feedback Chat

### ISSUE THREAD

**Issue by storyofyours** [thecodingmachine/workadventure#2511]
It seems like I don't have the chat box to write text.
When I click on a user, nothing's happening.
https://www.awesomescreenshot.com/video/10697558?key=cc86b91c6c050f1f79a3ef92cce67850

**Comment by moufmouf** [comment]
Interesting. It is available if you click on the "timeline" but if you could not find it, it means it is not obvious and we need to work on the UX

**Comment by storyofyours** [comment]
Oh I see!
The direct chat works only if you are in a bubble with someone?

**Comment by gparant** [comment]
There is "Your Timeline" when you want to discuss with someone in a bubble discussion. Speaking to someone one to one is coming up 🚀

<img width="1438" alt="Capture d’écran 2022-08-26 à 06 44 07" src="https://user-images.githubusercontent.com/23724509/186823892-266cdeb1-7f50-4567-b05d-227304cf250f.png">

Thanks So, I close this issue
