### ISSUE TITLE
New idea: Allow the display of an iframe

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#253]
Hey!

I have this view:

![image](https://user-images.githubusercontent.com/858611/91744994-99807b00-ebba-11ea-9212-33a652ed6f1b.png)

And it would be amazing to allow the display of a markdown document on the right like what you've done with Jitsi.
So, a tile layer with some tiles, and when we go on we get an iframe with a specific URL. Could be Google Drive, could be simple markdown file, whatever.

The idea is just "Hey, you want the documentation, go here".

Having a way to go somewhere else is great, we can even put links to get rid of people (joke), but I don't want them to leave the map.

Or like here where I have documentation:
![image](https://user-images.githubusercontent.com/858611/91745473-4ce96f80-ebbb-11ea-8c4a-17b7cb736f22.png)

**Comment by jacquesbh** [comment]
It's already done: https://workadventu.re/create-map.html#opening-a-website-when-walking-on-the-map

\o/

**Comment by moufmouf** [comment]
Hey @jacquesbh ,

This is actually already possible (I added the support yesterday :D )

See the documentation here: https://workadventu.re/create-map.html#opening-a-website-when-walking-on-the-map

**Comment by moufmouf** [comment]
By the way, nice screenshot of your map  :+1:
