### ISSUE TITLE
Self host WA: created Map doesn't open 

### ISSUE THREAD

**Issue by esra9910** [thecodingmachine/workadventure#2532]
Hello Everyone,
I sucessfully Self hosted my Server and I have the issue that, my created Map doesn't open in my Website. I put in the -env- File the created Map in the START_URL but it only shows me the default Map of the starter-ki. 
What can I d to solve this Problem?

**Comment by esra9910** [comment]
Also when I specify my URL in reference to my created Map it does open, but I want that should automatically open my created Map.

**Comment by gparant** [comment]
Hi @esra9910,

Thanks for the feedback, we will check that 🚀

**Comment by esra9910** [comment]
Hello @gparant  did you solve this Problem. I have the same issue.
