### ISSUE TITLE
Woka list menu UX

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#2562]
Clicking on the div of a user is not doing anything, we should remove the 3 dots button in order to increase the clickable zone.
So the menu will appear if the user clicks anywhere inside the user div in the list. (Much more mobile-friendly also)

![Capture d’écran de 2022-08-30 15-40-10](https://user-images.githubusercontent.com/14997703/187466644-7765a5fa-86dc-471e-a731-5929a18b829c.png)

**Comment by cesar-cardinale** [comment]
@ValdoTR At least, you will click on the user to enter in the one-2-one chat, and click on le three dots to get the menu with "Teleport to", "Visit card", "Open chat" and other things like that ...
