### ISSUE TITLE
Self host WA: How to connect self host WA-Project with Database

### ISSUE THREAD

**Issue by esra9910** [thecodingmachine/workadventure#2593]
Hello @everyone,

I have successfully self host my WA-Project with the only help of the .env and docker-compose.yml File.
I want t connect it with a database did anyone know how to? Does I need the full WA-Repo or are the two Files okay?

Hope for some answers too understand the logic behind . Thank you!

**Comment by LindezaGrey** [comment]
Hey,
your usecase is described in the docs:

https://github.com/thecodingmachine/workadventure/blob/develop/docs/dev/adminAPI.md


Unfortunately you will need more than just the docker-compose files...
