### ISSUE TITLE
Microphone appears inactive even when it is not

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#260]
![image](https://user-images.githubusercontent.com/858611/91961246-394d1e80-ed0b-11ea-991a-f8184528e5a2.png)

The microphone icon here appears in red as it is inactive, but we can clearly talk to each other, so it's not inactive.
Same for the other guy for my mic.

**Comment by gparant** [comment]
closed by : https://github.com/thecodingmachine/workadventure/pull/376
