### ISSUE TITLE
Player state issues in master branch

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2610]
I'm testing the master branch and I noticed an issue with the player state. When I save a JSON object to the player state, next time I reload the page, WA is unable to retrieve the variable from the player state. To reproduce the error:

```
WA.player.state.myjson={"field":"value}
```

Refresh the page and check the debug console:

```
09:04:35.118 Unable to unserialize value received from server for a variable. Value received: "{"field"". Error:  SyntaxError: JSON.parse: end of data after property name when ':' was expected at line 1 column 9 of the JSON data
    unserializeVariable RoomConnection.ts:1143
....
```
I actually tried to save as a string too:

```
WA.player.state.myjson=JSON.stringify({"field":"value})
```

This worked fine on version 1.11.4.

**Comment by moufmouf** [comment]
Thanks for the issue, we'll look into it!

**Comment by taksan** [comment]
I found the issue and opened a PR

**Comment by moufmouf** [comment]
Thanks @taksan for the fix!
