### ISSUE TITLE
Start layer not correctly handled

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2631]
Create a map with:

- one layer named "start" (at the top)
- other layers with the startLayer property set

When you don't put any "#" in the URL, you should start on the layer named "start".
But right now, you will pop on the last layer with the startLayer property set

**Comment by sw-fox** [comment]
is there a solution for this? I have set a start layer and a layer with startLayer property set, but the user still spawns somewhere else on the map.
