### ISSUE TITLE
A different sound when somebody leaves the circle

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#266]
The sound when somebody joins is important because we know somebody entered our circle.

Having a sound when somebody leaves could be great too. I find it sad when I am talking and nobody is listening xD.

I don't know how to avoid the hate for this sound though… Maybe only if the pebble entered more than 5 seconds ago? To avoid "noise"… ?

**Comment by moufmouf** [comment]
Hey @jacquesbh 

This is an excellent idea. I'll definitely look into it.

Sorry, I'm a bit long to answer. As you probably know, we are looking to hosting the Forum PHP on WorkAdventure.We have currently 2 big priorities:
- performance (being able to host an event with more than 100 users)
- administration (the Forum PHP team needs to be able to moderate users)

As soon as this is done (probably early October), I'll take care of your issues that are all very good ideas

**Comment by tabascoeye** [comment]
closed by #497
@jacquesbh agree?
