### ISSUE TITLE
The CI succeed while the end to end tests with firefox and webkit don't work

### ISSUE THREAD

**Issue by mlima95** [thecodingmachine/workadventure#2664]
The 2 types of end to end test failed but the CI  display shows as if the tests worked :
<img width="329" alt="Capture d’écran 2022-09-28 à 17 03 30" src="https://user-images.githubusercontent.com/43212369/192814823-ecd6f19d-e9d8-4dd3-ac0f-50314930907c.png">

**Comment by mlima95** [comment]
Here is the link : https://github.com/thecodingmachine/workadventure/actions/runs/3144348583/jobs/5121544665

**Comment by moufmouf** [comment]
Just had a closer look at the logs.
Actually, the tests are fine. Some are "flaky". They fail on first run (usually because of a timeout) and succeed on another run.

Not ideal, but still, valid.

```
Notice:   2 flaky
    [webkit] › api_players.spec.ts:271:3 › API WA.players › Test variable persistence for logged users. 
    [webkit] › chat.spec.ts:14:3 › Chat › main =====================================================
  15 passed (18m)
```
