### ISSUE TITLE
Hair layer should be over clothes, not under

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2665]
I noticed that hairs are drawn before clothes and I think that's incorrect. For example, a really long hair should be drawn above the clothes, or else it will be clipped by the clothes.

**Comment by moufmouf** [comment]
Mmmm... you are right. But on the other end, we have "hoodies" that are part of clothes and if we draw hair on top of clothes, we cannot draw "hoods" as part of clothes anymore...
I'm not sure what the best behaviour is.

**Comment by taksan** [comment]
Hoods can be categorized as hats.

**Comment by taksan** [comment]
Also, if the user uses a hoodie, you can let character bald, as the hat would not show up anyway... and if you really want to have some hair showing up hanging outside of the hoodie, in that very specific case, there would be workarounds.

The way it is now, you would have do draw part of hair as an accessory or as a hat if want it over the clothes (and that makes no sense). Besides, it would prevent users from using other hats or accessories  (which would be a shame). Hoodies on the other hand make sense being a hat, as the user would rarely use a hat over a hoodie (and in that very specific case, you can draw the hat as an accessory).

I would actually suggest having the option to have more accessories, but I understand that would be a bigger change.

**Comment by moufmouf** [comment]
Actually, glasses are in the same category as eyes, but I'd really like to have both glasses AND eyes in 2 separate categories.
So yeah.... more categories would be cool.... but that's indeed a bigger change.

**Comment by mlima95** [comment]
I'm currently working on this problem. So, which option do you prefer? As this with the hair under the clothes : 

![front under clothes](https://user-images.githubusercontent.com/43212369/210323888-f9f6288f-7e1c-40ac-b270-cbc92ba25cb7.png)
![back under clothes](https://user-images.githubusercontent.com/43212369/210323885-aeb0ae29-3a78-479d-ba4f-84257f48e695.png)
![left under clothes](https://user-images.githubusercontent.com/43212369/210323891-2713b667-a85f-4b5b-9f46-65ee071e0d74.png)

Alternatively, with hair over clothes:

![front over clothes](https://user-images.githubusercontent.com/43212369/210324141-bf88e5ef-05a4-4b62-a7a3-d7025f35ae6f.png)
![back over clothes](https://user-images.githubusercontent.com/43212369/210324139-835c7b6c-4a5b-4927-9797-6871c3ff134b.png)
![left over clothes](https://user-images.githubusercontent.com/43212369/210324143-31096cba-74dd-4f98-8b1f-7708ba17c987.png)

**Comment by moufmouf** [comment]
Ok, it's a no brainer. With the visuals, it is obvious the second version is better. Thanks @taksan and @mlima95 !
