### ISSUE TITLE
Add the map name in the html tag <title>

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#2675]
Add the map name after "WorkAdventure" in the HTML title of the page.

![image](https://user-images.githubusercontent.com/14997703/194098769-683855f4-42ae-4f91-9b07-9bd53a0045bc.png)
So that title could be "WorkAdventure | WA Village"

**Comment by nolway** [comment]
This feature will be implemented in https://github.com/thecodingmachine/workadventure/pull/2690
