### ISSUE TITLE
External font loaded from Google

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2695]
Somehow, the Roboto font is loaded from Google Fonts.
I'm not sure why and where the loading occurs right now.

![image](https://user-images.githubusercontent.com/1290952/195360158-5ec56e00-0aa7-4565-b9fc-d7c26334dd42.png)

We want to avoid that for:

- privacy reasons (RGPD...)
- chinese firewall that will block any Google IP and prevent the page from loading (for Chinese users)

Somehow, I was sure this was fixed with #874... I'm not sure why/how we got Google fonts back

**Comment by LindezaGrey** [comment]
stumbled upon this myself -> seems to be located in scss here:

https://github.com/thecodingmachine/workadventure/blob/develop/libs/tailwind/style/fonts.scss

https://github.com/thecodingmachine/workadventure/blob/develop/libs/tailwind/style/fonts.scss#L3

**Comment by Atomic-Germ** [comment]
Can the related bug #1806 be closed as well?
