### ISSUE TITLE
Chat shortcut enabled in emoji select page

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2698]
- Click the emoji button
- Click the edit button
- Type "ice"
When the c is typed, the chat window opens

The chat shortcut should be disabled (like the arrow keys that are already disabled)

**Comment by gparant** [comment]
https://user-images.githubusercontent.com/23724509/195633220-f6b0d87e-098b-4402-9963-c41a1be10e55.mov
