### ISSUE TITLE
Allow to change the size of the Jitsi up to 90% of the screen width

### ISSUE THREAD

**Issue by jacquesbh** [thecodingmachine/workadventure#270]
It could be great to have a button to enlarge the Jitsi to 90% of the screen width.
And of course the same button to go back.

Otherwise the screen sharing, as example, is too small.

**Comment by moufmouf** [comment]
Definitely! Adding this on the todo list.

**Comment by gparant** [comment]
@jacquesbh on the Jitsi you have a menu at bottom right and you have full screen mode.

**Comment by jacquesbh** [comment]
Yes but fullscreen is not practical ^^

**Comment by gparant** [comment]
Yes we know and keep this feature in todo list 😃

**Comment by freetim** [comment]
would be nice to change the size in steps or via mouse

**Comment by Kharhamel** [comment]
cowebsite resizing was added in v1.3
