### ISSUE TITLE
Authentication mandatory + OpenID connect issue

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2702]
When authentication is mandatory and when OpenID connect is configured, it is impossible to log out:

- Press log out button
- The authentication token is destroyed by the pusher
- User is redirected to "/"
- Because authentication is mandatory, we are redirected to the OpenID provider
- Because we are still logged in OpenID provider, we get logged again
- and back to the game

In order to break this loop, we need to add a new parameter "LOGOUT_REDIRECT_URL" to redirect the user when the user is logged out.

This parameter should be read first from the admin api (/map endpoint), then from the environment variables (default value = "/")
After the "/logout" route is visited, the user will be redirected to the LOGOUT_REDIRECT_URL.

In the case of an open id connect provider, one can target the logout route from the openid connect provider to log the user out from this provider.

**Comment by GregLebreton** [comment]
I was about to open an issue for this, indeed with DISABLE_ANONYMOUS=true, you're redirected to the id provider to connect, but when you click on disconnect, you're redirected to WA that redirect to the provider and as the session is still valid reconnects you to WA... infinite loop! :grin: 
Let me know if you need testing, I'll be happy to help about that!

**Comment by moufmouf** [comment]
Done!

We now have a `OPID_LOGOUT_REDIRECT_URL` environment variable that can be used to redirect the users to another location when the user clicked the "logout" button.
