### ISSUE TITLE
How to set maximum numbers of players?

### ISSUE THREAD

**Issue by sesmi123** [thecodingmachine/workadventure#2715]
Hello,

Good day.

I am having a self-hosted workadventure instance which also uses a self-hosted custom map. I need some help in knowing how to set the maximum number of simultaneous users who can enter the workadventure or the map at a time. 

Any pointers are appreciated!

Thankyou.

**Comment by sesmi123** [comment]
Hi @GregLebreton,

Thanks for your response. I appreciate it. I'm afraid the MAX_PER_GROUP is used to set the maximum number of players allowed in the bubble for p2p communication whereas what I am looking for, is to prevent further users from entering the map itself when there are already say 50 people connected right now.

**Comment by GregLebreton** [comment]
Hi, my bad for the bad information, I wasn't really sure...

**Comment by nolway** [comment]
You need an admin API or a custom development to do that.
