### ISSUE TITLE
Unable to see the author in the chat when sending a message from a script

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#2749]
This was working in the previous version of the chat.

`WA.chat.sendChatMessage("Message from the  Scripting API", "MrRobot")`

![image](https://user-images.githubusercontent.com/14997703/198660300-8f8faafe-6357-4ad7-a3a8-b0cbee81ef62.png)

PS: Maybe it's a good idea also to display a bot avatar if a message is sent via the Scripting API ?

**Comment by cesar-cardinale** [comment]
Do you have a png of a bot avatar that I can display ?
