### ISSUE TITLE
Online users and live chat users not matching

### ISSUE THREAD

**Issue by taksan** [thecodingmachine/workadventure#2756]
There's something wrong with the chat count of online users, as the "default chat" display a different number of users than the ones of the live zone. Here's a print of what I mean, it shows up 20 online users and 16 in the chat, but the chat live zone is in the same room, so it should match

![image](https://user-images.githubusercontent.com/96873/199083763-28ad1873-4228-4781-b13d-b0edcfa10fa2.png)

**Comment by cesar-cardinale** [comment]
Hi, live zone are showing only the users that are physically in the live zone, if a user is not in the zone he will be only shown in the Users list and not in the live zone "devops".

**Comment by taksan** [comment]
All users were in the same zone, I can assure you

**Comment by cesar-cardinale** [comment]
Hi, can you confirm that this bug is fixed or not with the new version of the chat ?

**Comment by taksan** [comment]
Still didn't test the new version. Will send a feedback as soon as possible
