### ISSUE TITLE
Permisson?

### ISSUE THREAD

**Issue by jamesthesnake** [thecodingmachine/workadventure#276]
Hey I think this is a really cool project, I'd like to run it on a personal server with my friends and I to  tinker with? I will not turn it into a business or anything, is that ok with you?

**Comment by saerdnaer** [comment]
see https://github.com/thecodingmachine/workadventure/blob/master/front/LICENSE.txt
> "Commons Clause" License Condition
>
>The Software is provided to you by the Licensor under the License, as
defined below, subject to the following condition. Without limiting
other conditions in the License, the grant of rights under the License
will not include, and the License does not grant to you, the right to
Sell the Software.  For purposes of the foregoing, "Sell" means
practicing any or all of the rights granted to you under the License
to provide to third parties, for a fee or other consideration,
a product or service that consists, entirely or substantially,
of the Software or the functionality of the Software. Any license
notice or attribution required by the License must also include
this Commons Cause License Condition notice.

**Comment by moufmouf** [comment]
This is absolutely ok!
You are allowed to install it on a server and run it as long as you don't turn it into a product you sell!
