### ISSUE TITLE
Question regards to license.

### ISSUE THREAD

**Issue by kwaka1208** [thecodingmachine/workadventure#2771]
Thanks for making workadventure open source.

I have a question about license for Workadventure.
We found 2 LICENSE.txt in desktop and back.
But we can't find any difference.

Could you tell us meaning of each LICENSE.txt?

**Comment by moufmouf** [comment]
Hey @kwaka1208 ,

WorkAdventure is split into several "containers". Each container could in theory have a different license. Right now, all licenses are similar: AGPL v3 restricted by the "commons clause license".

If you want is explained in simple terms, the best source of information on what we attempted to do is here: https://workadventu.re/faq/license

If you look at the issues in Github, you'll find a number of open questions (regarding the way the licenses are written). You will also notice the "map-editor" component does not yet have a license (it is not yet in use and still in development). It is possible that the map-editor component will have a slightly different license in the future that solves the aforementioned issues. The global idea will always be the same and is spelled in simple terms in the FAQ (https://workadventu.re/faq/license) :D

**Comment by kwaka1208** [comment]
Hi @moufmouf,
Thank you very much for your kind answer.
I can understood.
Thank you so much again. :D
