### ISSUE TITLE
Chat (ejabberd container) not working - missing JWT key

### ISSUE THREAD

**Issue by nextgen-networks** [thecodingmachine/workadventure#2791]
Hello community,

I got an almost working prod environment working (src: "https://github.com/thecodingmachine/workadventure/tree/develop/contrib/docker/docker-compose.prod.yaml & .env.prod.template" with commits on Nov 5, 2022)

The only not working container is "ejabberd" whatever I configure in the .env file the container crashes seconds after startup.
Reason seems to be a not used JWT token.

See container log:
root@localhorst:/opt/workadventure# docker logs workadventure_ejabberd_1
2022-11-09 23:26:17.784590+00:00 [info] Loading configuration from /opt/ejabberd/conf/ejabberd.yml
2022-11-09 23:26:17.810281+00:00 [notice] Changing loglevel from 'info' to 'debug'
2022-11-09 23:26:18.079163+00:00 [critical] Failed to start ejabberd application: Invalid value of option jwt_key: No valid JWT key found in file: /opt/ejabberd/conf/jwt_key

Any Idea how to solve this?
Tried to get this working myself but found no tutorial/howto for the current develop branch/tree.

Thanks Workadventure team and community for your support!

**Comment by nextgen-networks** [comment]
Ok used key was to long and result was the error message.
After shortending the key massively the container started regularly.

Sadly the chat is not working. See screenshot:
![image](https://user-images.githubusercontent.com/21206978/201222187-558f85af-c462-4f84-87cf-65ce1044dc60.png)

**Comment by LindezaGrey** [comment]
can you check the browser dev-tools and see if you get the same error like here : https://github.com/thecodingmachine/workadventure/issues/2784

**Comment by nextgen-networks** [comment]
> can you check the browser dev-tools and see if you get the same error like here : #2784

Hey @LindezaGrey
thanks for your reply.
For me the error message/source looks different.

Here ist the ejabberd part of my .env config:

> #
> # Ejabberd/XMPP
> #
> 
> EJABBERD_DOMAIN=ejabberd.DOMAINofWA.TLD
> 
> # MUST MATCH THE EJABBERD_HOST ENV
> EJABBERD_WS_URI=wss://ejabberd.DOMAINofWA.TLD:5443/ws
> EJABBERD_API_URI=http://ejabberd.DOMAINofWA.TLD:5443/api
> EJABBERD_USER=myUSERname
> EJABBERD_PASSWORD=myPASSword

Here is the dev-tools output from my browser (Edge 107):

> websocket.js:73
>         
>        WebSocket connection to 'wss://ejabberd.DOMAINofWA.TLD:5443/ws' failed: 
> connect @ websocket.js:73
> connect @ Client.js:333
> createClient @ XmppClient.ts:233
> (anonymous) @ XmppClient.ts:404
> (anonymous) @ CancelablePromise.mjs:28
> Ul @ CancelablePromise.mjs:28
> Hr @ CancelablePromise.mjs:104
> start @ XmppClient.ts:403
> (anonymous) @ XmppClient.ts:139
> websocket.js:91 
>         
>        Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}
> socket.onerror @ websocket.js:91
> error (async)
> connect @ websocket.js:90
> connect @ Client.js:333
> createClient @ XmppClient.ts:233
> (anonymous) @ XmppClient.ts:404
> (anonymous) @ CancelablePromise.mjs:28
> Ul @ CancelablePromise.mjs:28
> Hr @ CancelablePromise.mjs:104
> start @ XmppClient.ts:403
> (anonymous) @ XmppClient.ts:139
> XmppClient.ts:148 
>         
>        --transport-disconnected
> (anonymous) @ XmppClient.ts:148
> Kk @ events.js:79
> dt.emit @ events.js:168
> emit @ Client.js:256
> (anonymous) @ websocket.js:22
> Kk @ events.js:79
> dt.emit @ events.js:168
> ce @ _stream_readable.js:971
> Ql.t.run @ process.js:8
> a @ process.js:41
> setTimeout (async)
> Ql.Lc.nextTick @ process.js:60
> W @ _stream_readable.js:963
> Yb._.read @ _stream_readable.js:374
> M @ _stream_readable.js:769
> q @ _stream_readable.js:484
> O @ _stream_readable.js:478
> A @ _stream_readable.js:464
> p @ _stream_readable.js:213
> Yb._.push @ _stream_readable.js:203
> socket.onerror @ websocket.js:92
> error (async)
> connect @ websocket.js:90
> connect @ Client.js:333
> createClient @ XmppClient.ts:233
> (anonymous) @ XmppClient.ts:404
> (anonymous) @ CancelablePromise.mjs:28
> Ul @ CancelablePromise.mjs:28
> Hr @ CancelablePromise.mjs:104
> start @ XmppClient.ts:403
> (anonymous) @ XmppClient.ts:139
> XmppClient.ts:123 disconnected
>

**Comment by nextgen-networks** [comment]
closing this issue in favor of a new clean one ( #2805 )
