### ISSUE TITLE
OpenID Login not working with adminAPI

### ISSUE THREAD

**Issue by LindezaGrey** [thecodingmachine/workadventure#2807]
Since this change:

https://github.com/thecodingmachine/workadventure/commit/7f0561d103cc58d8600a9ed1900a55fadea8028c

I observe a strange redirect behaviour when trying to login by OpenID. Prior to the change adminAPI & OpenID have been working together. 

The problem:
When i press "Sign In" (in the menu or the chat), that is a link to /login. When i have the adminAPI env NOT set in the play container this is what happens:

![no admin api](https://user-images.githubusercontent.com/39629455/202184282-752aab75-7b97-4a94-bfbf-3ffa2dfbdc1e.png)

Which is totally fine and like before, which means i get redirected to /login-screen with the appropriate playUri as query parameter. The login in flow succeeds. As soon as i set an adminAPI env, the  behaviour is different:

![admin api](https://user-images.githubusercontent.com/39629455/202184554-2bec4c9d-a544-4288-8436-0f2a5a7d6f38.png)

As you can see a 302 happens and the request "play.localhost/login" gets send to the adminAPI. There i cannot handle it properly, since i have no information about the playUri so i cannot manually create a RedirectResponse.

i tried it with the latest tagged version as well as develop & master.
The fix here https://github.com/thecodingmachine/workadventure/issues/2804 did not change anything for me.

Do you have any suggestions? Is it the intention to handle the /login by the adminAPI?

best regards

**Comment by moufmouf** [comment]
Hey @LindezaGrey ,

Thanks a lot for the bug report.

> Do you have any suggestions? Is it the intention to handle the /login by the adminAPI?

Nope, clearly not. This is clearly a bug.

> As you can see a 302 happens and the request "play.localhost/login" gets send to the adminAP

This is not what I see in the screenshot you said.
Just so that I can understand...

`auth.localhost` => it's your OpenID connect provider, right? Is this also your Admin API? If not, I don't see any redirect to the admin API.

**Comment by LindezaGrey** [comment]
Hi @moufmouf, thanks for the fast reply.
Sorry i could be clearer, i try to explain:

What i see in the NOT working case (so when the adminAPI env is **set**):
The browser (see screenshots) asks the play container for `/login`. The play container then redirects this request to the admin API.
`Browser -->> Play -->> Admin API`
I confirmed this by looking at the logs from my adminAPI. There i could see the IP of the play container.

In the second screenshot i manually returned  a redirect response from my adminAPI.
Example code:

```py
if playUri.path == "/login":
    return RoomRedirect(
        redirectUrl="https://play.localhost/login-screen?playUri=
    )
```
But as you said a workaround like that should not be the solution.

When i remove the adminAPI env from the play container, you will see what is shown on my first screenshot. The browser asks for `/login` and the play container sends a redirect to `/login-screen?playUri=... `and everything works as expected. The play container does not contact the adminAPI

`Browser -->> Play`

`auth.localhost` is my OpenID connect provider (Authelia). My adminAPI is on `localhost:3000` (Python). But if i understand the architecture correctly the browser should not communicate with the adminAPI directly.  

If you need more information, i am glad to elaborate further

**Comment by LindezaGrey** [comment]
just saw this open issue from you, which is definitely related. Could fix my issue also, when resolved:
https://github.com/thecodingmachine/workadventure/issues/2765

**Comment by LindezaGrey** [comment]
after further fiddeling i had an idea and just returned an empty response, when the /login route was hit on the adminApi, which restored the expected behaviour

```py
    if playUri.path == "/login":
        return None
```

For me the issue is therefore closed.
