### ISSUE TITLE
Floors and a few suggestions

### ISSUE THREAD

**Issue by gaiagame** [thecodingmachine/workadventure#281]
Hi all

Thanks for the help last time I am able to embed my website now..
I am still having troubles with connecting other floors and maps
I tried different options and still not getting it 
![image](https://user-images.githubusercontent.com/71192199/93711319-90495500-fb4d-11ea-8821-47c3fb6d284e.png)
Is there like specific folder I should be creating?
Also here are some thoughts ideas:
Be able to trigger a popup for example of a video or audio message you see when you go to certain place
to be bale to customize the specific characters to use in your map and pre-name them
to be able to have a password lock of certain rooms (you can also hide the password somewhere in the map so it is a sort of treasure hunt) 
I have lots of ideas about how to use this for online theatre
truly great piece of softawre vision here

**Comment by gparant** [comment]
Hello @gaiagame, thanks for your idea, I approve this :)

For the problem to create your card, you could check this issue : https://github.com/thecodingmachine/workadventure/issues/446

Thanks.

**Comment by gparant** [comment]
@gaiagame don't hesitate to create a new issue if you have other idea 😃
