### ISSUE TITLE
Screen sharing glitch

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#282]
https://www.loom.com/share/e9e3106988e44db0b23b3d0ab6dcf192

**Comment by jacquesbh** [comment]
I can confirm this behavior.

**Comment by moufmouf** [comment]
I see.
You are walking next to a Jitsi Meet zone and it is opening and closing very fast (because you walk on the zone only a few milliseconds)...

Maybe we should display the iframe only after 1 second (or on "onLoad") and display a small loader meanwhile?
