### ISSUE TITLE
Username longer than 4 characters

### ISSUE THREAD

**Issue by ghostrich** [thecodingmachine/workadventure#286]
It would be nice to be able to use usernames that are longer than 4 characters.

I would like to use workadventure for an event, where people do have avatar names, but they are longer than 4 chars (e.g. around 10-15).

**Comment by moufmouf** [comment]
Hey @ghostrich ,
We are planning a big event for October 22nd and this is part of the things we need to look at.

We need to find the right balance between a name long enough to be understandable and short enough to keep the screen readable.

**Comment by pintman** [comment]
Looks like the issue is solved? I can enter up to 8 characters for my nickname. :+1:

**Comment by pwab** [comment]
I'm also able to enter up to 8 characters but it would be easier to see that this is possible if the line would be long enough (or changed to something like a blinking cursor).
