### ISSUE TITLE
Be able to be on a map with more than 100 people

### ISSUE THREAD

**Issue by ghostrich** [thecodingmachine/workadventure#287]
I would like to use workadventure for an event where there might be more than 100 people who want to join the map at a given time (e.g. closer to 500). 

Would that be possible?

**Comment by moufmouf** [comment]
Hey @ghostrich ,

The current version in production (as of today) will probably have problems at around 50 concurrent users.

We are heavily working on optimizing WorkAdventure and the current "develop" branch of WorkAdventure can sustain ~500 concurrent users. We plan on releasing this new version by the end of October. We will also be working on a "pro" version that comes with dedicated features for event organizers (that should come in November). I'll keep you posted!

**Comment by Robertofon** [comment]
Surely you want that pro version being hardcore'ly tested by a big event in the IT world with maybe even more than 1000 people at the same time. So as a throug load test. If that is a success, you can market your pro version proudly as "sustaining even largest number of simultaneus players".
