### ISSUE TITLE
extended feature "Doors" don't work

### ISSUE THREAD

**Issue by Teufelskomet** [thecodingmachine/workadventure#2873]
Hello Community,
I would like to establish a door with a code lock in my escape room. For this I followed the instructions from the WA documentation: https://workadventu.re/map-building-extra/doors.md

1. Door variable created on the object layer with the following properties:
![Door_Variable](https://user-images.githubusercontent.com/39899660/205923839-7cee535c-6ab1-4624-ac89-ad797eed3698.png)
2.  2 layers created with door open and door closed images
3.  2 door step layer created with the following properties:
![Door_Step_Code](https://user-images.githubusercontent.com/39899660/205924086-3dad5f76-f0bc-4fd5-aefc-1ebf66d4fdd1.png)

![Door_Step_Entry](https://user-images.githubusercontent.com/39899660/205924188-a4ecc3c2-3773-4031-b35f-9a3c8ea4e1d1.png)

But the door doesn't work. Neither the message appears nor does the status of the door change. When leaving the room, neither the code lock nor the message appears.

I integrated the o Scripting API Extra in early 2022. The "Configure the room" function in the menu is no longer available.

Where is my mistake?
Link to my room: https://workadventu.re/map-building-extra/doors.md

**Comment by moufmouf** [comment]
Hey @Teufelskomet ,

If the "Configure the room" function in the menu is no longer available, despite the fact that you have a "configuration" layer with variables in it, then the most likely issue is that the scripting-api-extra library is not correctly loaded or bootstrapped.

Check this document: https://workadventu.re/map-building-extra/about.md
There are several way of installing scripting-api-extra library depending on your use case.

**Comment by Teufelskomet** [comment]
Hey Moufmouf,
thanks for the quick answer.
I startet with the "WorkAdventure Map Starter Kit" and import the "Scripting API Extra" library as a "dependency" .  This ist more than 1 year ago.
Maybe something went wrong.
So I will import the  "Scripting API Extra" again.  Is it necessary to uninstall / delete something beforehand or something similar?

**Comment by Teufelskomet** [comment]
Hello,
now I importl the Scripting API Extra v. 146 sucessfully. But can't use "import { bootstrapExtra } from "@workadventure/scripting-api-extra" . I'm not a coder! I only follow the discription in the documentation. So I use the command prompt and try to import. But I get: unknown command.

Please help.
