### ISSUE TITLE
Screen sharing issue

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#2903]
Errors:
 - Loader is displaying during screen sharing,
 - Error in displaying video in the shadow part.

<img width="320" alt="Screenshot 2022-12-21 at 10 49 25" src="https://user-images.githubusercontent.com/23724509/208875379-0a0a34a8-6996-4315-a7f3-ae57ac64ea57.png">

**Comment by gparant** [comment]
I reproduce the error:

The user A share a screen and the user B is not on the WorkAdventure tab, the screen sharing has loading error and the display is broken.

Follow the video:

https://user-images.githubusercontent.com/23724509/208912933-c3b4fa67-2b38-478e-91cc-6dd33669fb93.mov

**Comment by gparant** [comment]
Typically in this case, Cesar share me a screen and when I change the browser tab, the Cesar's Woka disappear.

<img width="1512" alt="Screenshot 2022-12-26 at 10 20 22" src="https://user-images.githubusercontent.com/23724509/209531034-daef2154-dc62-4373-a839-06041d16f21b.png">

**Comment by cesar-cardinale** [comment]
> Typically in this case, Cesar share me a screen and when I change the browser tab, the Cesar's Woka disappear.

I did not manage to reproduce this bug, can you give me more details? if it has happened since?


The other bug is fixed.
