### ISSUE TITLE
Creating maps with different tilesets

### ISSUE THREAD

**Issue by dravisss** [thecodingmachine/workadventure#291]
Hi! I've been creating maps with  different tilesets and it seems that workadventure will only accept when I use the tilesets of the starterkit.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/49192328/95249822-2b5e5200-0811-11eb-937b-6bbc69fc2eac.png">
<img width="218" alt="image" src="https://user-images.githubusercontent.com/49192328/95249834-30bb9c80-0811-11eb-84a0-09e819b484dc.png">

I've tried with and without different tilesets and noticed that it crashes(blackscreen) when I use any other tileset. 

How could we solve that? :) 

By the way, amazing project you have here! I'm interested in using this with our facilitated card games platform and we will be glad to share efforts to improve this project. Thanks for sharing with the world!

**Comment by dravisss** [comment]
This what I get in my console 

Don't know how to handle tileset  
{…}
​
firstgid: 321
​
lastgid: 356
​
source: "flare.tsx"
​
<prototype>: Object { … }
GameScene.ts:264:24
Don't know how to handle tileset  
Object { firstgid: 357, source: "Aurora Tileset.tsx" }

**Comment by dravisss** [comment]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/49192328/95252832-737f7380-0815-11eb-8fa5-14bdb0396127.png">

**Comment by kamikazebr** [comment]
@dravisss The path of image in the tsx is not defined or cannot be found.

You should copy your **`png`** tiles together to your `.tsx` files.

The warning try look for `tileset.name or tileset.image.`

And none them was found in your `map2.json` in https://github.com/dravisss/collabgame_v1/tree/gh-pages

**Comment by moufmouf** [comment]
Exactly!
In fact, WorkAdventure does not support tilesets stored in `.tsx` files. You should **embed** the tileset in the map.

This can be done by clicking the "embed tileset" button in Tiled.

![image](https://user-images.githubusercontent.com/1290952/95298033-b70cc880-087b-11eb-86bd-158341c8e57f.png)

**Comment by dravisss** [comment]
Thanks, problem solved! 👍
