### ISSUE TITLE
Emojis are broken on the new master branch in the chat

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2956]
![image](https://user-images.githubusercontent.com/1290952/211530548-f1813de3-eb07-45fc-85cd-06a3a3127288.png)

**Comment by kangjianhua** [comment]
This is a cool software, when will this bug be fixed？

**Comment by LindezaGrey** [comment]
you do not need to use the master branch, just change it in the docker-compose file and use the latest stable version (v1.14.13) The emojis work there.
