### ISSUE TITLE
Bug: Changing Woka-Appearance causes connection loss to presence server

### ISSUE THREAD

**Issue by LindezaGrey** [thecodingmachine/workadventure#2977]
I stumbled upon a weird behaviour, that i managed to replicate on your staging server. This issue mainly happens to new people who want to try workadventure, because they are more likely to change the appearance of their wokas.
To reproduce, join a workadventure world (i tried also with a self hosted v.1.14.14). 
As you can see, everything works fine:

![image](https://user-images.githubusercontent.com/39629455/214246120-dba33cb2-cabf-4b4a-bb9b-7dd6a81d80d3.png)

Then, edit your woka (i press randomize):

![image](https://user-images.githubusercontent.com/39629455/214246373-92640136-e21e-484e-b0fd-ec01c425e385.png)

As you can see, the connection to the chat is lost. This can be fixed if i refresh the window. 

Additionally, in the state where the user sees "Connecting to presence server" the player is not shown in the chat or user list - so he is invisible but can interact with the map and players normally:

(here xxx is in the invisible state, yyy is the observer. Also note the green status even though in silent zone)
![image](https://user-images.githubusercontent.com/39629455/214247427-a034ab88-7706-4d7b-9edf-8c44c41d1012.png)
 -> xxx is not in the user list, even though he is obviously on the map

**Comment by gparant** [comment]
It should be deployed soon 🚀

**Comment by LindezaGrey** [comment]
@gparant thanks! i will test it again. I deployed a self-hosted version with the master branch as of 14th february, where the issue persisted but i will check again with the latest changes

**Comment by LindezaGrey** [comment]
this is no longer happening in v15.1.1 thanks a lot!
