### ISSUE TITLE
Weird Bug when I open a Jitsi conference

### ISSUE THREAD

**Issue by dravisss** [thecodingmachine/workadventure#299]
I'm using firefox and MacOS. When I open the jitsi conference and leave it open for 5min I can not use the arrows to navigate the game anymore. I've tried many times and it happens systematically. I'll try with another browser soon.

**Comment by dravisss** [comment]
Just tested in chrome and it was ok. It's happening only in firefox.

**Comment by KingBBQ** [comment]
Same here. Might be related also to the chat - if I use the chat, the bug Happens Right away.

**Comment by gparant** [comment]
relatif to : https://github.com/thecodingmachine/workadventure/issues/388
