### ISSUE TITLE
Map editor: collides is saved on "y+1"

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2997]
In the map editor, I'm putting a table on the map.
Collides are working correctly and as expected.

Now, I press F5 to reload WA.
Now, there is a bug. The collides have moved one tile down (y+1):

![image](https://user-images.githubusercontent.com/1290952/215422679-5fe2a8ea-c28c-4833-b736-9e8f7ca4b274.png)

**Comment by Waclaw-I** [comment]
Was fixed in #3004
