### ISSUE TITLE
Map editor: cursor contains entity on "area" tool

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#2999]
- Enable the map editor
- Enable the "Entity editor tool"
- Click on the "Edit" tab
- Now, click on the "Area editor tool" at the bottom left
- You will see the last selected entity is displayed on the cursor position
![image](https://user-images.githubusercontent.com/1290952/215481883-ed7eb8a2-e596-4bda-9c95-9d6d5caa485f.png)

**Comment by Waclaw-I** [comment]
Probably was fixed in the meantime while working on other issues
