### ISSUE TITLE
Issue reconnecting XMPP server

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#3036]
If the XMPP server is disconnected but the pusher is not, we get errors when trying to reconnect to the XMPP server:

**Comment by cesar-cardinale** [comment]
> If the XMPP server is disconnected but the pusher is not, we get errors when trying to reconnect to the XMPP server:

This case is tested in the E2E tests, I'm launching a browser on play, go to chat, shutting down the container and relaunch it and the chat is reconnecting correctly.
Why can you say that this is the problem and not an another thing ?
