### ISSUE TITLE
Problems with API Extra. How to renew / rebase the API Extra?

### ISSUE THREAD

**Issue by Teufelskomet** [thecodingmachine/workadventure#3047]
Hello
I started my room with the Strater Kit. In the meantime the map has changed a lot. There are rooms with complete connections like a WorldCafe.
Now the extended Feature "Doors" don't work. According to moufmouf there is a problem with the API Extra : he most likely issue is that the scripting-api-extra library is not correctly loaded or bootstrapped. in issue  #2873

How can I reload / renew / rebase the API Extra library without having to completely rebuild my room?

 Since the 6 Dezember I try to geht some Help here. Without success. I'm not a coder! Maybe this is only for me a problem.

**Comment by LindezaGrey** [comment]
lol i just answered you? wasn't it good enough? :D https://github.com/thecodingmachine/workadventure/issues/3034#issuecomment-1429687360

We need more information about your setup - it is pretty vague and we can only guess. We first have to verify if the loading of the api extras is actually an issue. as written in my last comment it seems that it loads correctly
