### ISSUE TITLE
Cannot reopen "highlighted" cowebsite

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#3128]
Open 2 cowebsites.

Both cowebsites are shown as icons in the bottom left corner.

Close the "highlighted" cowebsite (the one on the left)

The icon disappears. Now, to open it again, you need to go out of the zone and back again.

**Comment by nolway** [comment]
Did you have an example on a map ? The cowebsite has been configured with this property : **openWebsiteClosable** ?

**Comment by gparant** [comment]
This issue was fixed 🚀
