### ISSUE TITLE
Freeze while changing room

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#313]
When changing of room, got a freeze (a bit randomly, hard to reproduce), with this error:

![image](https://user-images.githubusercontent.com/1290952/95989698-e77bd600-0e2a-11eb-8157-fb326abb24a7.png)

**Comment by gparant** [comment]
Il me semble que cela a été corrigé, à vérifier @moufmouf

**Comment by moufmouf** [comment]
A lot has changed and I haven't seen the issue lately. Ok for closing!
