### ISSUE TITLE
Axios error. No full HTTP response received. Request to URL: //anonymLogin

### ISSUE THREAD

**Issue by matzegebbe** [thecodingmachine/workadventure#3207]
Using the anonymous login leads to an error for the prod docker-compose file!

https://github.com/thecodingmachine/workadventure/blob/develop/contrib/docker/docker-compose.prod.yaml#L39

the call of the start page tries to generate a token via post. Because the `PUSHER_URL` is "/" the host anonymLogin is called.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/3482021/233811093-13ba2881-29c8-4002-9801-d77713747c13.png">

![image](https://user-images.githubusercontent.com/3482021/233811107-0c800e2b-cc3e-4efb-bdc6-9444950e1c29.png)

**Comment by moufmouf** [comment]
Hey @matzegebbe,

You used the docker-compose.prod.yaml from the develop branch, but unfortunately, the "master" branch (or any tagged version) is not yet on-par with this docker-compose.

You can try to put `VERSION=develop` in your `.env` file (and live on the edge until we merge develop into master... probably in 2 weeks)

**Comment by matzegebbe** [comment]
okay! Then we can close this
