### ISSUE TITLE
LogRocket usage on selfhosted

### ISSUE THREAD

**Issue by lochot** [thecodingmachine/workadventure#3217]
I  saw that issue : #3053 and discover logrocket, 
so i created an account on logrocket, and get an id.
I added it on my .env and add lines to my docker-compose but after reconstruct my image, nothing appear in logrocket. 

In developer console, i do not see the logrocket init.
Seems that is here play/src/pusher/controllers/FrontController.ts
```typescript
if (req.query.logrocket === "true" && LOGROCKET_ID != undefined){
                option = {
                    ...option,
                    /* TODO change it to push data from admin */
                    logRocketId: LOGROCKET_ID,
                    userId: uuid(),
                };
            }
```
it define logRocketId that is used in play/index.html
```html
        {{#logRocketId}}
            <!-- LogRocket -->
            <input type="hidden" id="log-rocket-id" value="{{ logRocketId }}">
            <input type="hidden" id="log-rocket-roomurl" value="{{ url }}">
            <script src="https://cdn.lr-in-prod.com/LogRocket.min.js" crossorigin="anonymous"></script>
            <script>
                console.info('Start LogRocket script!');
                window.addEventListener('DOMContentLoaded', (event) => {
                    const logRocketId = document.getElementById('log-rocket-id').value;
                    const roomUrl = document.getElementById('log-rocket-roomurl').value;
                    window.LogRocket && window.LogRocket.init(logRocketId);

                    // This is an example script - don't forget to change it!
                    window.LogRocket.identify("{{ userId }}", {
                        name: "{{ userId }}",
                        // Add your own custom user variables here, ie:
                        roomId: roomUrl
                    });
                });
            </script>
        {{/logRocketId}}
```

I wonder if it is req.query.logrocket that i have to use somewhere ?

**Comment by gparant** [comment]
Hello, for the LogRocket with self-hosted instance, you need to use the environment variable `LOGROCKET_ID` and access to your WorkAdventure instance with this parameter `?logrocket=true`

**Comment by lochot** [comment]
As the stupid guy i am, i tried with logrocket=1 and never try with true in full letter, i see now the script in developer console

**Comment by lochot** [comment]
Ok, i can close since it is working (i had to deactivate my surfshark protection to let logrocket activate in wa)
