### ISSUE TITLE
Change CSS Property of Popup Button

### ISSUE THREAD

**Issue by Kaither180** [thecodingmachine/workadventure#3225]
Hi ! 

I would like to know if there is a way to change css property of the button container of popup, or maybe link my own stylesheet with my own style.

**Comment by moufmouf** [comment]
Hi @Kaither180 ,

This is unfortunately not possible right now (PRs are welcome :) )
If you want to have full control over your popup, what you can do instead is to create an "embedded website" on the map. This way, you can put your popup in a separate HTML file and fully control the design of the popup.

**Comment by Kaither180** [comment]
Ok, thanks for the answer !
