### ISSUE TITLE
[MAP EDITOR] integrations buttons

### ISSUE THREAD

**Issue by ValdoTR** [thecodingmachine/workadventure#3242]
If you click several times on "Open a link" integration, it will append the link form several times.
![image](https://github.com/thecodingmachine/workadventure/assets/14997703/7d56013e-0b2a-49c8-8379-07f810ecf03f)

We shouldn't be able to add more than 2 IMO (and the two must have different triggers)

**Comment by Waclaw-I** [comment]
Not really the case. We are now working with properties arrays that are allowing us to open multiple websites at once (even new tabs). Closing this one :)
