### ISSUE TITLE
Allow to 1 website + 1 jitsi when walking in the same layer - with size 50% each

### ISSUE THREAD

**Issue by sergiolucianojr** [thecodingmachine/workadventure#340]
Sometimes I have to open a website to interact with people (like a whiteboard) and the video interface (Jitsi) at the same time.

It would be nice if when I enter a space configured with the website and Jitsi I could open both together, with the window divided 50% for each.

I tried to configure the properties of the layer with the 2 properties, JitsiRoom and openWebsite, but it seems the Work Adventure understand just one of them and ignore the other.

**Comment by moufmouf** [comment]
Indeed! WorkAdventure is not yet capable of doing both a Jitsi and a whiteboard. I'll keep the issue open until I find some time to look at it (don't expect it until at least 1 month as the backlog is growing quite fast right now :) )
In the meantime, you could try to create a simple HTML page with 2 IFrames (one for the whiteboard and one for the Jitsi meet room) and open this HTML page from WorkAdventure.

**Comment by simondueckert** [comment]
I did that for a map I am creating right no by just adding a html file in the repo that includes two iframes (video livestream + chat below) and embed that in the map. Works fine.

**Comment by albancho** [comment]
Actually, it works for whatching a video + writting to a chat, but we can't open a Jitsi meet, because the iframe generated by `openWebsite` does not contain `allow="camera; microphone; display-capture"`... Could there be a workaround ?
Actually, we can put 2 seperate layers (one with jitsi, and one with openWebsite), which generates 2 iframes, but they take both 100% height. So a simple "height" parameter on layers would do the trick... (so jitsy would be 40% and openWebsite 60% for instance)

**Comment by gitalm** [comment]
Dear simondueckert,

could you post the html file. I have the same issues for a break out game, where students should cooperatively solve problems.

Thanks for your help

**Comment by albancho** [comment]
Hey @gitalm, a new parameter is available: `openWebsitePolicy`, and makes it work fine.
So my layer config is:
```
openWebsite: https://xxxxxx.github.io/my-project/pub/my-game.html
openWebsitePolicy: camera; microphone
```

and my html is:
```
<html>

<head>
  <style>
    body {
      background-color: #6800E7;
      margin: 0em;
      padding: 0em;
    }

    .my-game-wrapper {
      position: relative;
      display: block;
      margin: auto;
      height: 60vh;
    }

    iframe {
      border: none;
    }

    .wrapper {
      text-align: center
    }
  </style>
</head>

<body>
  <div class="wrapper">
    <iframe class="my-game-wrapper" src="http://xxxxxxxxxxxxxxx"
      width="100%"
      frameborder="none"
      seamless="seamless"
      allowfullscreen="true"
      scrolling="no"></iframe>
    <iframe src="https://meet.jit.si/MY-JITSI-ROOM-NAME#config.startWithAudioMuted=false&config.startWithVideoMuted=false&config.prejoinPageEnabled=false&interfaceConfig.SHOW_CHROME_EXTENSION_BANNER=false&interfaceConfig.MOBILE_APP_PROMO=false&interfaceConfig.HIDE_INVITE_MORE_HEADER=true&interfaceConfig.SHOW_BRAND_WATERMARK=false&interfaceConfig.SHOW_JITSI_WATERMARK=false&interfaceConfig.SHOW_POWERED_BY=false&interfaceConfig.SHOW_PROMOTIONAL_CLOSE_PAGE=false&interfaceConfig.SHOW_WATERMARK_FOR_GUESTS=false&interfaceConfig.TOOLBAR_BUTTONS=%5B%22microphone%22%2C%22camera%22%2C%22closedcaptions%22%2C%22desktop%22%2C%22fullscreen%22%2C%22fodeviceselection%22%2C%22hangup%22%2C%22profile%22%2C%22chat%22%2C%22recording%22%2C%22livestreaming%22%2C%22etherpad%22%2C%22sharedvideo%22%2C%22settings%22%2C%22raisehand%22%2C%22videoquality%22%2C%22filmstrip%22%2C%22feedback%22%2C%22stats%22%2C%22shortcuts%22%2C%22tileview%22%2C%22videobackgroundblur%22%2C%22download%22%2C%22help%22%2C%22mute-everyone%22%5D"
        name="jitsiConferenceFrame1"
        allow="camera; microphone; display-capture"
        width="100%" height="40%"></iframe>
  </div>
</body>

</html>
```
