### ISSUE TITLE
'#'-notacion seems not to work with 'exitUrl'-property

### ISSUE THREAD

**Issue by namiko** [thecodingmachine/workadventure#341]
I tried to point to a certain entry point by adding the associated layer name to a exitUrl-property. This seems not to work in github-pages (leads to default start layer instead). So i switched to exitSceneUrl-property, also doesn't work with github-pages (black screen, doesn't load the targeted map).

So I tried both in my local docker instance, pulled a few days ago. Using exitSceneUrl-property works as expected, using exitUrl shows same behavior as online (leads to default start layer).

**Comment by moufmouf** [comment]
Hey @namiko ,

I made changes to this code a few days ago so it is possible I broke something.
However, when I'm doing tests in production, it seems to work.

Would you mind sending me a link to the map that is failing and explain to me which exit is not working and where you expect it to go?

**Comment by cbluoss** [comment]
Can confirm this, changed exitUrl to exitSceneUrl and now working as expected.
