### ISSUE TITLE
Jitsi-Meeting hangs in Firefox

### ISSUE THREAD

**Issue by pintman** [thecodingmachine/workadventure#345]
When intering a jitsi meeting area my firefox browser hangs while chrome is working. Restarting firefox dind't solve the issue.

![Bildschirmfoto von 2020-10-20 13-27-06](https://user-images.githubusercontent.com/1793263/96580146-251fa980-12d8-11eb-83f7-666d0c5698ea.png)

**Comment by moufmouf** [comment]
Weird. We did changes to Jitsi roughly 3 days ago. Jitsi seems to be working on Firefox for us. Are you still seeing the issue?
If yes, do you have any plugin installed that might cause issues (like an Adblocker?)

**Comment by pintman** [comment]
Currently the game does not hang but the conference simply does not show up. The only plugin installed ist uBlock Origin. Turning the plugin off does not solve the issue.

**Comment by gparant** [comment]
Relative to https://github.com/thecodingmachine/workadventure/issues/368
