### ISSUE TITLE
[Feedback AFUP] User details

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#372]
By clicking on a user, it would be great to be able to see some details (maybe full name, location, some hashtags or a presentation text...)
That would help users now knowing each others to speak to each other

**Comment by gparant** [comment]
Ajout des fonctionnalité dans la roadmap AFUP. Je ferme ce ticket

**Comment by Kharhamel** [comment]
The feature 'visit card' was implemented in v1.4. It solves most of theses problems but only for logged users
