### ISSUE TITLE
I see the shared screen even if I am not in the circle

### ISSUE THREAD

**Issue by maximehuran** [thecodingmachine/workadventure#382]
![image](https://user-images.githubusercontent.com/11380627/97551123-dd350c80-19d2-11eb-9c5d-a115fb7e29c0.png)

This happened this morning but I don't know why and how.

**Comment by moufmouf** [comment]
Damn! Ok, thanks for the feedback. Do you know if you want in the circle with the screen shared at some moment?

**Comment by maximehuran** [comment]
I don't know I had it on background so I cannot tell you.
After many minutes I displayed the tab with Workadventu.re and saw the screen of my collegue ^^

**Comment by lotfiidir** [comment]
I have the same issue right now 
![WorkAdventure](https://user-images.githubusercontent.com/16717662/97975986-400b1700-1dca-11eb-857f-15c1576d541b.png)

**Comment by maximehuran** [comment]
Are you on the same IP adress ? Maybe it's a clue ?
I had the issue yesterday.
