### ISSUE TITLE
Add Zooming

### ISSUE THREAD

**Issue by normanrz** [thecodingmachine/workadventure#385]
In order to get a better overview of the scene and to find co-workers, it would be nice to be able to zoom out.
Browser zoom works, but also makes all controls tiny. Especially in jitsi that is hard to work with.

**Comment by moufmouf** [comment]
Hey @normanrz ,

Thanks for the suggestion. I'll tag this as an improvement request.

**Comment by tabascoeye** [comment]
note that it might then be neccessary to "mark" the zone where other players are shown compared to the full map (currently 10x10 tiles I believe).
So people do not zoom out and think they will see everyone on the map

**Comment by waldyrious** [comment]
Wasn't this now implemented in release [v1.4.0](https://github.com/thecodingmachine/workadventure/releases/tag/v1.4.0)?

> - Mouse wheel support to zoom in / out
> - Pinch support on mobile to zoom in / out

**Comment by jonnytest1** [comment]
there is a small problem with this implementation - the popup zones are scaled by maptiles so now they either go out of the screen at the right when ur on mobile or at the bottom if you on web (and the popup width is smaller to fit mobile)
