### ISSUE TITLE
Cannot move after joining meeting in Firefox

### ISSUE THREAD

**Issue by daniel-wer** [thecodingmachine/workadventure#388]
Thank you for this great project!

In Firefox, after joining a meeting in one of the meeting zones and clicking into the jitsi call, the focus cannot be brought back to the workadventure. Therefore, users cannot move during the meeting or afterwards even after clicking into the workadventure, for example, next to the character. My quick investigation shows that this seems to be a focus issue. The jitsi iframe remains the focused element even after clicking somewhere else.
Indeed, a `document.activeElement.blur()` in the developer console resolves the issue and I can move again.

I'm using Firefox 82.0 (64-bit) on Ubuntu 18.04. This issue doesn't occur in the latest version of Chrome on my machine.

**Comment by KingBBQ** [comment]
Duplicate to: #299 / #345  ?

**Comment by gparant** [comment]
The problem is when you click on jitsi frame, the canvas lose the focus and you cannot move. 

You must close the frame. So my MR add close button and permit to close frame and move.
