### ISSUE TITLE
Embedding text

### ISSUE THREAD

**Issue by pwab** [thecodingmachine/workadventure#389]
As [Object Layers](https://doc.mapeditor.org/en/stable/manual/layers/#object-layers) aren't supported by workadventure [Text objects](https://doc.mapeditor.org/en/stable/reference/json-map-format/#text) can't be used. Is there a workaround to embed some text into the map?

**Comment by moufmouf** [comment]
Hey Philipp,

Currently, the only way to do this is to draw the text directly in the tileset and embed those tiles in the map.

We usually do this using direction signs like shown in the image below:

![direction signs](https://user-images.githubusercontent.com/1290952/98213849-fa735900-1f45-11eb-93c5-6c24fced4654.png)

We will certainly add support for text objects at some point in the future but don't expect those too soon as we already have a heavy backlog of features to add :)

**Comment by pwab** [comment]
Hey David,
thanks for the quick response and yeah that was the only workaround I could think of. Thanks for the clarification.

> We already have a heavy backlog of features to add :)

As I'm working on a conference map I'm very interested in every new feature I can get 😄. I'm not confident with TypeScript but I could help with the docs and maybe some assets if you need a helping hand.

By the way: Great job so far! Setting a new map up and running was a no-brainer and the idea rocks. 👍
