### ISSUE TITLE
[Feature request] Zone mode

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#397]
We could define on a map a number of "zones". These zones would have a name that would be displayed at the bottom of the screen when we enter them.

For instance:

- Chill Zone
- Boss office
- Team WorkAdventure
- ....

**Comment by CharlesNepote** [comment]
Why? Here are ideas:
* allow speaking to the whole zone
* allow people to be guided towards the zone
* allow particular behaviour of the zone: example: people can chat but can't talk

**Comment by nolway** [comment]
You can do it with the scripting API (zone triggers and ui websites).
