### ISSUE TITLE
Spelling mistake in website (https://workadventu.re)

### ISSUE THREAD

**Issue by WilcoBreedt** [thecodingmachine/workadventure#4176]
When on the website, and when in embedded webview (Discord, Slack etc.), the word "Platform" is misspelled, not sure where else to raise this issue

<img width="598" alt="Screenshot 2024-09-09 at 14 22 39" src="https://github.com/user-attachments/assets/1d4d72c0-125a-40f8-a9e6-7bfa494eb2ce">

**Comment by moufmouf** [comment]
Fixed. Thanks a lot! :heart:
