### ISSUE TITLE
Enable animed tiles

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#423]
Animated Tiles make for way more immersive and fun maps!

Phaser has two plugin which both can make use of tile animations:
https://github.com/colinvella/phaser-tilemap-plus (which has a lot other features as well)
and
https://github.com/nkholski/phaser-animated-tiles (which only implements the animations)

This should be just a matter of adding the plugin, loading it and setting the animations to run.

**Comment by moufmouf** [comment]
Hey @tabascoeye 

I wasn't aware of those plugins. Thanks a lot for pointing them!
We will definitely add support for animated tiles using those plugins!

Do not expect them too soon though, cause we have a quite busy backlog of features to implement (unless you want to contribute a PR of course!)

Thanks again for the tips!

**Comment by tabascoeye** [comment]
I'll try to cook up a pr 😄

**Comment by tabascoeye** [comment]
@moufmouf: I cannot get a development instance of WA to work. Using vagrant and then docker-compose inside.
The website container throws npm errors. Replacing the "npm install" with "yarn install" in the docker-compose file does no longer lead to errors, but I only get a blank 404 page on the localhost websever. Any help?

**Comment by tabascoeye** [comment]
addendum: there is also https://github.com/englercj/phaser-tiled which has a typescript version.

All of them seem to be quite old and I'm not sure they work with phaser 3.x as they should. I couldn't easily get any of them to work because of my lack of knowledge in typescript and phaser itself.

Any help would be greatly appreciated. Animated tiles would be just amazing in workadventure.

**Comment by lovelaced** [comment]
+1 - definitely need this for immersive environments.

**Comment by tabascoeye** [comment]
Good news. I got this to work, but I am not confident enough to create a pull-request because of my lack of understanding of typescript and its strictness.

Essentially these changes in GameScene.ts are enough: 
* all mentions of `Phaser.Tilemaps.StaticTilemapLayer` has to be switched to `Phaser.Tilemaps.DynamicTilemapLayer`
* the create code from `this.addLayer(this.Map.createStaticLayer` to `this.addLayer(this.Map.createDynamicLayer`
* load the Plugin in "preload": `this.load.scenePlugin('AnimatedTiles', 'resources/plugins/AnimatedTiles.js', 'animatedTiles', 'animatedTiles');`
* initialize the plugin in "create": `(this as any).animatedTiles.init(this.Map); // eslint-disable-line @typescript-eslint/no-explicit-any`  this is what bugs me the most. I don't understand how to make this so that it works cleanly with typescript

That's it. Then animated Tiles work. 🥳

**Comment by s3krit** [comment]
@tabascoeye wow awesome! Do you have a forked repo/branch somewhere I could check out myself?

**Comment by moufmouf** [comment]
@tabascoeye Excellent! Do not hesitate to open a PR. We can have a look and help or take over for the Typescript part!
