### ISSUE TITLE
Exits on the far right tiles won't work.

### ISSUE THREAD

**Issue by cbluoss** [thecodingmachine/workadventure#426]
Expectation: Every exitLayer Tile is equal, regardless of its Location.

Reality: Tiles in the far right tile column won't work as exits.

Work around: Expand the map with an addtional tile column on the right side.

**Comment by cbluoss** [comment]
Demo map here: https://play.workadventu.re/_/global/noxymo.com/filespublic/rc3bug/exitbug.json
Blue exits use exitSceneUrl , red exits use exitUrl.

Thanks to trailblazr for creating this demo map.

**Comment by Kharhamel** [comment]
Really cool demo map thank you! Makes the issue much easier to understand.
I am looking into it.
