### ISSUE TITLE
Revoir la page de sélection Vidéo et Micro

### ISSUE THREAD

**Issue by gparant** [thecodingmachine/workadventure#437]
La page de vidéo et micro n'est pas forcément claire et nous devons voir pour améliorer la visibilité notamment de la sélection du micro et vidéo que nous pouvons utiliser dans l'appli.

Information remontée sur le projet Mazars

**Comment by tabascoeye** [comment]
Isn't this fixed with the current Mic/Video settings page? close @gparant ?
