### ISSUE TITLE
[Screen sharing] There is a growing delay during a screen sharing session

### ISSUE THREAD

**Issue by ThibBal** [thecodingmachine/workadventure#441]
During a screen sharing session, i've noticed a growing delay between what the user is sharing and what I see.

![Capture d’écran 2020-11-19 à 15 38 06](https://user-images.githubusercontent.com/6185745/99685879-58925700-2a83-11eb-9852-2166cdda6937.png)

**Comment by gparant** [comment]
I close this issue.

Thanks for your feedbakc @ThibBal 💪
