### ISSUE TITLE
Redirection doesn't work as expected for global URLs without an explicit .json filename

### ISSUE THREAD

**Issue by lovelaced** [thecodingmachine/workadventure#444]
It seems that when parsing a global URL, subdomains hosting a JSON file at the root don't work as expected. I suspect this is something to do with how public roomSlugs are determined(?) after skimming through the code, though I may be completely wrong(!).

**Example:**  

Works as expected:  
https://play.workadventu.re/_/global/station.freeside.network/main.json - loads fine, all assets load normally.

Doesn't work as expected:  
https://play.workadventu.re/_/global/station.freeside.network - assets fail, despite `main.json` being the index of the subdomain.

It *initially* loads fine, but when retrieving the assets, the image paths are loaded in a relative manner resulting in a `404` as soon as an avatar is selected and an attempt to join the map is made.

![2020-11-20-233517_526x300_scrot](https://user-images.githubusercontent.com/8581604/99856805-17d13580-2b8a-11eb-8333-6f267f5b69ce.png)

**Comment by gparant** [comment]
When we load MAP, we must manage url to charge all image embed. So we must to have the real path map assets and not a relative path with hosted files on a sub domain.

I think that the map and files embed are assets. So in my reflection, the assets must alway to be with sub domain .json or other.

**Comment by gparant** [comment]
I close this issue.

Thansk for your feedback 💪
