### ISSUE TITLE
Adding non Tileset Images to an Objectlayer

### ISSUE THREAD

**Issue by Prosti95** [thecodingmachine/workadventure#446]
I would really love to celebrate with my among us group using workadventure. I recreated the skeld-map layer by layer from the original assets and added them to a tiled map using [this](https://www.youtube.com/watch?v=ORhC48773bw) method. 

Actually it seems that the objectlayers that contain the images are ignored as no image shows up without any error message.
Maybe I would need another naming scheme?

Is it possible to add support for this kind of map or should I try another approach (rebuilding the map in a perfect tiled measures)?

**Comment by gparant** [comment]
The object layer is used to have interaction with an object on the map. To add images in your map, you must 
 - Import your image in a Tilesets

![image](https://user-images.githubusercontent.com/23724509/99901734-3c77fb00-2cb9-11eb-966c-19a32701f612.png)

- Create new TileLayer

![image](https://user-images.githubusercontent.com/23724509/99901738-439f0900-2cb9-11eb-915b-d906d7f34bbc.png)

- Select your new Tilse Layer, use your Tileset previously imported on click on part that you went added and depose it on your MAP

![image](https://user-images.githubusercontent.com/23724509/99901785-8d87ef00-2cb9-11eb-9dfd-fc54141ca3c0.png)


Today we don't have an object manager in WorkAdventure but I hope it will arrive soon :D

You could check this page : https://workadventu.re/create-map.html
I think that you could find responses at your issue.

Don't hesitate to back to us if you don't succeed to create your map with this example.

Good luck 😃

**Comment by gparant** [comment]
I close this issue.

Thanks for your feedback 💪
