### ISSUE TITLE
screen sharing whereas connection was over

### ISSUE THREAD

**Issue by gregory-r4** [thecodingmachine/workadventure#454]
j'ai établi une connexion avec X puis suis allé parler à Y après avoir mis fin à l'échange. À cet instant l'écran que X était en train de partager avec Z a aussi été partagé avec moi...

**Comment by gparant** [comment]
Hello @gregory-r4, thanks for your feedback.

This issue is link at : https://github.com/thecodingmachine/workadventure/issues/382
