### ISSUE TITLE
Cannot move on map when I am on a Jitsi room in Firefox

### ISSUE THREAD

**Issue by maximehuran** [thecodingmachine/workadventure#461]
I am on Firefox (Mac).
When I am on a Jitsi room, I click on the map and I cannot move my character.

**Comment by totti95** [comment]
I have the same problem, for example when I cut my microphone on jitsi and then want to move to WA, this is impossible for me.

**Comment by Kharhamel** [comment]
The jitsi is runned inside an iframe which somehow hold focus even if you click outside of it. You need to manually close the iframe by clicking on the cross on the top-right side

**Comment by maximehuran** [comment]
I didn't see the cross before ! It works when I close the iframe thank you
