### ISSUE TITLE
Robot and lag voice

### ISSUE THREAD

**Issue by totti95** [thecodingmachine/workadventure#462]
The voice of all the people in a circle is transformed into a robot and lag at any given moment. When this happens, it lasts.

**Comment by maximehuran** [comment]
I have the same on Firefox too

**Comment by maximehuran** [comment]
Actually I have to use Chrome just to be able to use Workadventure correctly

**Comment by gparant** [comment]
Thanks for your feedback @totti95. We have project to change the circle and use JISTI or other meet application in a circle to have better stability.

I close your feedback and I hope we could develop soon the update circle meet 🤞

**Comment by jacquesbh** [comment]
@gparant will it lead to a half screen slide each time? It's also a bit slow to enter a Jitsi room.

It worked well before, are you sure you want to do that? 😅

**Comment by gparant** [comment]
@jacquesbh don't worry, we will stay with a circle and not with half screen slide. 

We have possibilities to use JITSI with an API. So we want to keep circle and we hope to increase the limit of 4 people in a meet circle and increase the size circle when one player enter into a circle 💪 🚀
