### ISSUE TITLE
Integration of BigBlueButton

### ISSUE THREAD

**Issue by datenreisen** [thecodingmachine/workadventure#465]
Thank you very much for this great project.

I would like to suggest to integrate the video conferencing platform BigBlueButton as Jitsi Meet. Jitsi Meet is very easy to use for smaller meetings. BigBlueButton has advantages for larger events, seminars etc..

The API calls are described [here](https://docs.bigbluebutton.org/dev/api.html). For the "create" API call at least custom properties for BBBmeetingID, BBBattendeePW and BBBmoderatorPW are needed. This "create" API call follows a "join" API call together with the fullName and the desired password (selectable joining as moderator or attendee). Best would be, all create parameters could be optional provided as custom properties (BBB[nameofparameter]).

In addition a secret and a baseURL has to be defined on the server itself, which are needed for the checksum calculation and the API call.

Thanks in advance!

**Comment by lunar-debian** [comment]
The code in #602 is rough but kinda working. Feel free to have a look and advice on how to improve the code.
