### ISSUE TITLE
Jitsi room name must not contain spaces

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#469]
If a Jitsi room name contains spaces, the Jitsi room will fail to open.

We should either:

- document the limitation
- or "slugify" the room name

**Comment by chrisaga** [comment]
Hi ! 
workadventure looks like it doesn't like character such as "é", "è" etc.  either.
I had those in a Jitsi room name and when my avatar enter the room, the Iframe comes, Jitsi tries to start and almost immediately displays "Sorry, you are not allowed here". I edited the map to remove them and everything works as expected.

**Comment by moufmouf** [comment]
Thanks @chrisaga for the feedback.
We will take that into account too when fixing the issue!
