### ISSUE TITLE
Camera doesn't turn off correctly #bug

### ISSUE THREAD

**Issue by ThibBal** [thecodingmachine/workadventure#470]
Sometimes, my camera is turned off on the Work Adventure interface but my computer still tell me that the camera is still being used by the website (my camera light is turned on)

**Comment by gparant** [comment]
Unfortunately, we can't interact with your computer light or other. I reassure you, on WorkAdventure if your cam is turned off, you don't have flux opened.

There is a difference between navigator, for example in Firefox, my light switch off when my cam is turning off and on chrome is not.
