### ISSUE TITLE
Feature Request: Background Sound Zone

### ISSUE THREAD

**Issue by oxzi** [thecodingmachine/workadventure#474]
First, thanks a lot for this awesome project!

A feature I would like to see in the Work Adventure would be zones with background noises or music. Currently there are silent zones, which are nice. However, sometimes you want quite the opposite of silence to highlight the setting, e.g., fire sounds near the virtual bonfire or the sound of our servers.

Technically one could supply either a static mp3/flac/… file to be played on repeat or a music stream.

What do you think? Thanks!

**Comment by netalex** [comment]
i think jitsi conversation will stop music?

**Comment by oxzi** [comment]
I thought about an additional layer property which initiates the front end/browser to play some music stream in the background. This should only collide with Jitsi if this also uses the frame thingy. And this is currently already possible, but "blocks" half of the screen.

**Comment by moufmouf** [comment]
Hey @oxzi ,

This is an excellent idea! We have quite a lot on our plate right now, so don't expect this to be developed to soon (unless you can provide a PR), but we will add this feature to the backlog :+1:

Thanks for your suggestion

**Comment by oxzi** [comment]
@moufmouf: Thanks for appreciating this suggestion.

Starting from the end of next week I might find some time to work on it myself. However, since I'm not much of a TypeScript developer, this might not be the most feasible solution.

**Comment by Moini** [comment]
This appears to be implemented in the version the CCC is using for this year's online congress: https://howto.rc3.world/maps.html#sound - don't know where they keep their code, though.

**Comment by Xyz00777** [comment]
as far as i know after the rc3 the code will (when it will work) get merged back, i think this is one of the feature that will get merged back ;)

**Comment by fkohrt** [comment]
See #541

**Comment by oxzi** [comment]
Closed with #541, thanks a lot!
