### ISSUE TITLE
Overlay for buttons is too big in Firefox

### ISSUE THREAD

**Issue by rugk** [thecodingmachine/workadventure#493]
## STR

1. Go to https://play.workadventu.re/_/krz-fxx-tej/npeguin.github.io/skapa-map/map.json
2. Go through all screens so you get to the world. (Do not use/activate microphone etc.)
3. I can hover over the buttons and they slide into the view.

### What happens

Regardless of whether you hover or not, you have this big semi-transparent grey area in the background that does not move:

![grafik](https://user-images.githubusercontent.com/11966684/102268658-e004a600-3f1b-11eb-8e90-35349e15715e.png)

### What should happen

I guess the semi-transparent grey area should move together with the buttons when I hover? So it should move with the buttons, too, should not it?

If not, then I don't see the value in the big empty space that is there. 

## System

There is no version information at https://play.workadventu.re/, so the current version that is/was running on https://play.workadventu.re/ at this time.

Firefox 83
Linux/GNOME

**Comment by moufmouf** [comment]
@rugk you are right, this semi transparent area is the div that is supposed to contain the webcam feedback video.
When the webcam is not activated we should either.

1- totally hide this semi transparent area
2- or put an icon at the center of it (or the name of the user) to show the webcam is off

**Comment by rugk** [comment]
If you want to do that (in contrast to what I originally suggested, but I also did not test out the webcam feature yet), then I would argue in favor of the first solution, i.e. hide the area.

**Comment by rugk** [comment]
So was this solved? If so, in which commit/PR/release or so?

**Comment by moufmouf** [comment]
Indeed, issue was closed a bit roughly.
Yes, it has been solved a long tie ago. The semi transparent area (that is a placeholder for the webcam) no longer shows when webcam is not enabled
