### ISSUE TITLE
Set playUrl from environment variable

### ISSUE THREAD

**Issue by H4kor** [thecodingmachine/workadventure#494]
The current construction of the `playUrl` only works for the default setup. The domain (and the default map) should be configurable in the docker-compose.yaml

https://github.com/thecodingmachine/workadventure/blob/16f7c3d2044c6ad3f2a8b74dcf60cf7070eabf31/website/dist/index.html#L62

I could implement this, if this feature is wanted.

**Comment by moufmouf** [comment]
This could actually be solved by #489 .
Don't bother doing a PR on the "/website" part. It is likely that we will move the WorkAdventure website out of this repository soon. It does not make sense to keep the "workadventu.re" website (which is the website of the default "online" WorkAdventure") in the same repository as the game itself (that can be deployed anywhere). @gparant @Kharhamel does it make sense?

**Comment by gparant** [comment]
Merge request merged #571

Thanks for your feedback 💪
