### ISSUE TITLE
Find / design a tileset

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#5]
Find or design a tileset for the office.

Useful can be found online here: https://opengameart.org/

We can also design sprites with Piskel: https://www.piskelapp.com/

**Comment by moufmouf** [comment]
Found this resource https://pipoya.itch.io/pipoya-rpg-tileset-32x32

More resources here: https://itch.io/game-assets

**Comment by ArnaudPrigent** [comment]
> Found this resource https://pipoya.itch.io/pipoya-rpg-tileset-32x32
> 
> More resources here: https://itch.io/game-assets

Moufmouf would you have the resource you used to design the office map ?

**Comment by moufmouf** [comment]
I'm not sure where the tileset comes from. We should ask @npeguin who found it.

Anyway, if you are just looking for the tileset, it is available in the code, here:

https://github.com/thecodingmachine/workadventure/tree/master/back/src/Assets/Maps/Floor0
