### ISSUE TITLE
Feature request: Multiple levels of chat/discussion

### ISSUE THREAD

**Issue by arthurlogilab** [thecodingmachine/workadventure#508]
First of all : congrats on workadventure, it's a very promising alternative to a number of proprietary tools that can be used for this type of interaction. 

On an another platform which is similar, there is a nice feature of having a chat / discussions on multiple levels of "distance", it's quite useful when sharing links for either all people present, or just the people nearby, or just one person.

**Comment by gparant** [comment]
Thanks for you feedback @arthurlogilab 

Today we have a chat feature in a circle to share any information and we have made the choice of do not implement chat outside the circle. We want that the user meets people before to start a discussion. But we are not closed at ideas to improve chat feature. 😄

**Comment by gparant** [comment]
I close this issue.

Thanks for your feedbakc 💪
