### ISSUE TITLE
Feature request: podium functionnality - speak to all users in map

### ISSUE THREAD

**Issue by arthurlogilab** [thecodingmachine/workadventure#509]
As mentioned before, congrats for a great project ! 

In a similar tool we use, there is a feature which we use quite a lot : a podium zone where the users that go there they can speak and be visible to all other users present on the map (without having to enter a jitsi zone). 

This feature is helpful for work sessions where everyone gather together at the beginning then splits up in smaller groups, then someone can talk to everyone to remind them to come back to the central part of the map for telling everyone what they worked on.

**Comment by moufmouf** [comment]
Hey @arthurlogilab ,

This is an excellent idea and is actually on our roadmap.
We are still in design phase though. Not sure what solution to use to stream from the podium.
We could use Youtube Live + its Jitsi integration (but Youtube Live adds some latency). Or trying a Jitsi with "octo" deployment to stream to many people at once... Or a completely different tool. We are still in design phase so it might take a while before we get a proper solution.

**Comment by arthurlogilab** [comment]
To stay with a free software stack, I've read that jitsi says "stream to Youtube live" but it can actually stream to systems that have  rtmp as input (eg  `rtmp://foo.bar.baz:1935/live/123KEY-TOKEN456`). Apparently it works with peertube's live functionnality (new in v3 which is in beta) https://joinpeertube.org/ (bonus points for p2p streaming !) 

I'm not familiar with what jitsi with "octo" is... I guess https://github.com/jitsi/jitsi-videobridge/blob/master/doc/octo.md is related, but I'm not sure I understand the specifics. 

This feature is not urgent, but as we use proprietary solutions as a workaround we want to make sure the free software solutions have similar features or at least have them on the roadmap so we can switch as soon as possible. Thanks for taking the time to respond to this issue !

**Comment by gparant** [comment]
Hi @arthurlogilab 

We have deployed feature live stream YouTube with Jitsi on WorkAdventure. If you want more information, you can see our documentation : [https://workadventu.re/admin-guide/streaming-conferences](https://workadventu.re/admin-guide/streaming-conferences).

Thanks for your feedback 💪

**Comment by arthurlogilab** [comment]
Hey @gparant thanks a lot for the documentation for using workadventure for conférences, this is super exiting. We'll be sure to test that out in the next weeks (probably with peertube or owncast). 

In my opinion this does not really answer the use case exposed above, in particular the "splitting into smaller groups", maybe the ticket should be renamed and mention the "tool for users to speak to all participants on a map" with an analogy of a venue speaker system (or school general announcement ). Should I open a new ticket or should we reopen this one ?

**Comment by moufmouf** [comment]
Hey @arthurlogilab 

Sending a message to all users on a map is actually already available in the "pro" version.
You can see the documentation here: https://workadventu.re/admin-guide/global-messages

You can send either a text message, or an audio message.
