### ISSUE TITLE
Add a prettier autoformatting support

### ISSUE THREAD

**Issue by Palid** [thecodingmachine/workadventure#515]
Currently the coding style for the project is vaguely different in places, it would be amazing if the project had a standardized code styling enfored on CI and on commit hook.
It's as simple as running: `npx mrm prettier && npx mrm lint-staged` in all the directories, as it'll automatically setup proper `prettier` and add precommit hooks for autoformatting properly.

That would especially help with mergins forks with your upstream and pushing changes to this one too!

**Comment by moufmouf** [comment]
Absolutely :+1: with this!
@gparant maybe we can plan this at the end of next sprint, when the number of PRs opened is low? (to avoid having problems merging code between pretty and non-pretty version)

**Comment by Informatic** [comment]
Bump? This would greatly help with federation work we are starting.

**Comment by Palid** [comment]
@moufmouf bump!
