### ISSUE TITLE
command keys asdw are interpreted in chat

### ISSUE THREAD

**Issue by blaueente** [thecodingmachine/workadventure#520]
If you are in a chat and type one of the direction keys asdw, your avatar moves.
Expected: does not move.

**Comment by moufmouf** [comment]
Weird. I think this bug was fixed a few weeks ago.
Are you seeing this on https://play.workadventu.re or are you using a private deployment?

**Comment by gparant** [comment]
We have deployed fix.

Thanks for your feedback 💪
