### ISSUE TITLE
unnecessary re-setup on re-load

### ISSUE THREAD

**Issue by blaueente** [thecodingmachine/workadventure#521]
If I get stuck somewhere and re-load using browser reload, I have to do the avatar setup again, even if my custom avatar settings are saved, I have to klick on "custom", Enter, Enter. Enter...
Expected: if settings cookie is found, map is just reloaded and directly displayed without any further input necessary

**Comment by moufmouf** [comment]
Hey!

Good news, this is already fixed in the develop branch that will be deployed in 2 weeks.

**Comment by moufmouf** [comment]
The new version is online. There is now no need to re-setup everything on reload.
