### ISSUE TITLE
Press ENTER to start - enter key does nothing

### ISSUE THREAD

**Issue by jooray** [thecodingmachine/workadventure#525]
I am on macOS Big Sur 11.1 (20C69). I can enter the name, but then if I press ENTER, nothing happens on Firefox, Chrome and Chromium. I also clicked into the window to make sure it's on focus.

I can enter on Safari.

Could there be another key to enter? Or what could be an issue?

**Comment by Kharhamel** [comment]
Do you have an error in your javascript console? (CTRL+SHIFT+K on firefox) ? Without more details, It is quite difficult to think of a solution

**Comment by jooray** [comment]
There's nothing in the console. It works in incognito window, so probably some extension.
