### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by CptLeeChuck** [thecodingmachine/workadventure#526]
Hello,

I tried to install it from the master branch and the lates develop brach. In both cases I expierience the same problem after installation.

Opening this URL (https or http)
`https://play.workadventure.mydomain.com/_/global/npeguin.github.io/office-map/map.json`

results in this 404 - File not found "INVALID URL" error message:
<img width="769" alt="grafik" src="https://user-images.githubusercontent.com/11474337/103316322-6d6ded00-4a28-11eb-8dae-8a04fd1888ef.png">

Comparing this to the workadventu.re by providing a map that does not exist, I see in my instance the URL seems to be invalid because it misses the http:// respectively https:// in front and starts with the /_/ part.

<img width="871" alt="grafik" src="https://user-images.githubusercontent.com/11474337/103316538-28968600-4a29-11eb-938f-9aed7b3269a5.png">

Is there any configuration I need to do? Or what could be wrong on my installtion, and how to fix it?

**Comment by moufmouf** [comment]
Could you simply try to access "https://play.workadventure.mydomain.com" and let me know what you are seeing?

**Comment by CptLeeChuck** [comment]
This shows just "/" as invalid URL:
 
<img width="1606" alt="grafik" src="https://user-images.githubusercontent.com/11474337/103436351-c8673600-4c1a-11eb-944e-2563e724b5b1.png">

However I noticed that all this might be related to certificate problems as it blocks loading the resources from the other sub-domain pusher.workadventure.mydomain.com in both cases (with map path or just opening root of the domain).

(Strangely I'm very certain yesterday it blocked not from pusher but from api.workadventure.mydomain.com
 
However I accepted the sub-domain certificates by manually opening the sub-domains in advance. However it still shows CORS error from different sub-domain.

So therefore I do not know if this is maybe the same issue as described in this issue [https://github.com/thecodingmachine/workadventure/issues/452](url), or another issue on top. However I was not able to set up the docker containers with letsencrypt or certs from my own CA.

**Comment by djmaze** [comment]
@CptLeeChuck I get the CORS error with `/info` as well, but that only seems to affect the hot code-reloading. Does the app itself work for you now?

**Comment by CptLeeChuck** [comment]
I was now able to get it to work by following these steps

1. Fresh installed Ubuntu 20.04 and create DNS record for own domain/subdomains
2. docker and docker-compose installed
3. Copied the V1.0.0.0 (https://github.com/thecodingmachine/workadventure/releases/tag/v1.0.0) to ~
4. unziped it and go into the directory
5. copied .env.template to .env
6. replaced all .localhost domains in docker-compose.yaml with my own domains
7. run docker-compose up
8. Get fresh installed versin of Firefox, I prefered Firefox as it has it's own cryto-engine and cert store
9. Go in Firefox to Settings > Security > Crpyto Settings and certificates > Server > Add >> And add permanently trust for each domain/sub-domain
10. now all works as expected on my computer in this browser.

In my case I guess step 8+9 blocked my previous success.

Still open for me: How can I assign either my own certificates or get it to create on it's own letsencrypt certificates?

**Comment by morellenfeuer** [comment]
@moufmouf  I have exact the same problem with the CORS error. I also failed in setting up the certs. The workaround with browser exceptions doesnt work and still shows the CORS error 

![image](https://user-images.githubusercontent.com/59543742/103469849-9a910700-4d6a-11eb-8125-f6da9ec825be.png)

**Comment by benlooning** [comment]
@morellenfeuer
Make sure you have the permanent trust for each domain/sub-domain in place:
**pusher**.example.com **api**.example.com **play**.example.com **maps**.example.com **uploader**.example.com 
You can double check in the firefox console which subdomain causes the issue.

@CptLeeChuck
You can add your own certificates by utilizing the dynamic configuration of traefik.

1. create config.yml
$ nano /var/docker/traefik/config.yml
tls:
  certificates:
    - certFile: "/certificates/cert.pem"
      keyFile: "/certificates/privkey.pem" 

2. add the path to the certificates and the config.yml to the docker-compose.yaml file. It should look something like this:
version: "3"
services:
  reverse-proxy:
    image: traefik:v2.0
    command:
      - --api.insecure=true
      - --providers.docker
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --providers.docker=true
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    depends_on:
      - back
      - front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      **- /var/docker/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro**
      **- /var/docker/ssl:/certificates:ro**
...
In my case the keys/certificates (letsencrypt) are located in /var/docker/ssl. Make also sure to change the access rights:
chmod 644 cert.pem
chmod 600 privkey.pem

**Comment by benlooning** [comment]
@CptLeeChuck you can find a working docker-compose.yaml example on how to dynamically create letsencrypt certificates here https://github.com/thecodingmachine/workadventure/issues/452#issuecomment-753563863. Also have a look at [Docker-compose with let's encrypt : HTTP Challenge](https://doc.traefik.io/traefik/user-guides/docker-compose/acme-http/)

**Comment by CptLeeChuck** [comment]
@benlooning Perfect, thanks a lot, I tried both ways (my own certificates and letsencryprt) both are working!

The only thing to mention for others is the config.yml has to have at least one more line, without the first line it is not working:

```
tls:
  certificates:
    - certFile: "/certificates/cert.pem"
      keyFile: "/certificates/privkey.pem"

```

**Comment by benlooning** [comment]
@CptLeeChuck thanks for the hint, I updated my post.
