### ISSUE TITLE
Jitsi room doesn't work

### ISSUE THREAD

**Issue by taxmeifyoucan** [thecodingmachine/workadventure#528]
Trying different room names, layer positions, stepping on jitsi tile never works. Url works well, audio doesn't play for example. Here is source https://github.com/Bordel/workadvanture-bordel

![image](https://user-images.githubusercontent.com/61149543/103322692-58e91f00-4a3f-11eb-9f8f-4ea3afd5502e.png)

**Comment by taxmeifyoucan** [comment]
Added jitsiTrigger solved this

**Comment by puresick** [comment]
Did you add "jitsiTrigger" as the value for `jitsiRoom` or as a seperate property?
If latter, which value did you assign to it?

**Comment by taxmeifyoucan** [comment]
@puresick Added as separate property with `onaction` value. See below: 
![image](https://user-images.githubusercontent.com/61149543/104003779-2cea3e00-51a3-11eb-925b-f0cf15edcaf5.png)
