### ISSUE TITLE
Tiles animation

### ISSUE THREAD

**Issue by taxmeifyoucan** [thecodingmachine/workadventure#529]
I animate tiles in Tiled but after running it online - on github pages from starter kit template, animated tiles don't move. I see #443 not merged, is this the blocker?

**Comment by moufmouf** [comment]
Hey Mario!
Yes, you probably tested animated tiles on the rC3 instance which is slightly modified.
They contributed back #443 and it will work when this is merged.
We took some time to verify that #443 had no impact on performance. It seems it has none, so #443 will be merged shortly. You can expect to see this online by the end of next week.

**Comment by taxmeifyoucan** [comment]
Thanks for clarifying @moufmouf! Looking forward to it, closing issue for now.
