### ISSUE TITLE
Improving Getting Started Documentation

### ISSUE THREAD

**Issue by bboortz** [thecodingmachine/workadventure#530]
Hi,

we have just tried this software and have struggled a bit with the setup.
From my perspective these steps need a bit more documentation like:

1. Getting started, esspecially how to access the game after the docker-compose up
2. How to add own maps and access the map

I will create a PR.

Benni

**Comment by Jacques-Olivier-Farcy** [comment]
Totally agree with these points.

I can work on improving creating and using maps.

**Comment by moufmouf** [comment]
Hey @bboortz and @Jacques-Olivier-Farcy !

Please don't bother. We rewrote all this documentation from scratch and are preparing a release (probably next week). I'll gladly accept some help on the new documentation, but until we release the new documentation, it would be useless to work on the old one!

**Comment by Weranders** [comment]
@moufmouf 

I actually wanted to create a new user, but i'm glad i found your comment and i don't have to create more work for you guys. You are already doing a great job here.

The documentation is really unclear to me in regard of how to set the exitUrl correctly. If you didn't already, please take this also into consideration in reworking the docs:

I've spent way too much to figure out that the exitUrl should be

exitUrl: <url>

and NOT

exitUrl: https://workadventure.re/_/<instanceToken>/<url>

Nevertheless, still, great Job! This is fantastic

**Comment by Corps-git** [comment]
Talking about exitUrl: The documentation still uses a screenshot with the old form exitSceneUrl.

That can really give you a hard time when trying to implement an exit and looking at the screenshot to see where to add the property ...

**Comment by beccon4** [comment]
I offer help in writing a proper howto in exchange for support setting up my server :-)

**Comment by gparant** [comment]
Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create a new issue 😍
