### ISSUE TITLE
Audio not playing

### ISSUE THREAD

**Issue by taxmeifyoucan** [thecodingmachine/workadventure#531]
Added layer with `playAudio` property, string `/audioname.mp3. File exist in root of directory, tried also different directory. Tiles on this layer are in place, other like Url or Jitsi work. You can test https://github.com/Bordel/workadvanture-bordel

**Comment by moufmouf** [comment]
The `playAudio` is a special tag that was added for the rC3.
It is not implemented (yet) in this repository. Hopefully, the CCC team said they would open PRs to pull there changes upstream.

I'm waiting for these PR and when they are merged, you cill be able to use "playAudio" on the "play.workadventu.re" website.

**Comment by ganti** [comment]
I'd add that it would be neat having a special layer to stop all sounds when walking over a tile. with this stop-layer background sounds can be stopped/muted when leaving an area.

**Comment by moufmouf** [comment]
@ganti you can actually leave "holes" in the layer marked with "playAudio".
The sounds will not play on the empty tiles of the layer.

And there is also a "silence" property you can put on a layer to define a zone where noone is allowed to speak.

**Comment by ganti** [comment]
this approach works as well :)

**Comment by moufmouf** [comment]
Fixed by #541. This is not yet deployed on production server so be patient :D

**Comment by taxmeifyoucan** [comment]
Update works great!
