### ISSUE TITLE
_

### ISSUE THREAD

**Issue by facinick** [thecodingmachine/workadventure#534]

**Comment by tbnobody** [comment]
It looks like that IP and hostname is swapped?

**Comment by darachm** [comment]
@tbnobody do you mean the line
`workadventure.localhost 127.0.0.1` ?
Because that's from the README.md. But it does go IP first then hostname, right?

**Comment by tbnobody** [comment]
Yes thats right. (I can only speak for Linux, not OSX), but the other Hosts in the description looked like on a Linux system (first IP, second hostname)
