### ISSUE TITLE
Feature Request: Adding attributes to iframes via tile properties

### ISSUE THREAD

**Issue by tickelton** [thecodingmachine/workadventure#537]
I would like to open a website in an iframe that needs access to a camera and microphone.
For that to work the attribute allow="camera;microphone" needs to be set for the iframe.

Since this attribute currently is not set and also should not be set by default it would be nice if attributes could be added via tile properties.

e.g.: 

> openWebsite  https://example.com
> iframeAttributes   allow="camera;microphone"

**Comment by tbnobody** [comment]
I think thats already a pull request: https://github.com/thecodingmachine/workadventure/pull/527

**Comment by tickelton** [comment]
Yes, you're absolutely right.
I somehow missed that one, but that's exactly what I was looking for.
Thank you.
