### ISSUE TITLE
Collision for users in the map ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#543]
Hi there,

I am using Tiled to create my won map, and it is working good.

But i can't find how to tell which part of the map the user cannot walk.
Is there a block option somewhere ?

**Comment by freetim** [comment]
I think you need a layer 'collides' where you put 'BLOCK' tile.

**Comment by Jacques-Olivier-Farcy** [comment]
I tried, it is not working…

**Comment by freetim** [comment]
Is the layer the last one?

**Comment by Jacques-Olivier-Farcy** [comment]
It is strange, in the example given, when i open map.json i don't see any collide layer

I only see :
![image](https://user-images.githubusercontent.com/19731340/103556075-83106600-4eb1-11eb-8948-d863685932fa.png)

**Comment by freetim** [comment]
I'm not so into it. maybe the block tiles are enough.

**Comment by Jacques-Olivier-Farcy** [comment]
I guess there should be another way, will wait.

**Comment by moufmouf** [comment]
This is now properly documented here : https://workadventu.re/create-map.html
Check the section "Building walls and "collidable" areas"

(note: the URL might change in a few weeks as we are completely reworking this part of the documentation)
