### ISSUE TITLE
Smartphone and workadventure ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#547]
Hi,

I was wondering, do you plan to make it working on smartphone ?

**Comment by fkohrt** [comment]
[lernOS on Air - Spacial Chat with Workadventure](https://media.ccc.de/v/rc3-404041-lernos_on_air_spacial_chat_with_workadventure#t=2373), 39′ 33″

**Comment by gparant** [comment]
Hi @Jacques-Olivier-Farcy 

Yes, we have planned a phone development in our roadmap 🚀
