### ISSUE TITLE
Map on Gitlab ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#551]
Hi there,

I am trying to use gitlab instead of github for my project.
My gitlab repository is here :
https://gitlab.com/Jacquesolivier/hart/

I have tried a few tests but i can't find the correct syntax of the link for the map3.json file.

Any ideas ?

**Comment by tbnobody** [comment]
Just try this url: https://gitlab.com/Jacquesolivier/hart/-/raw/master/map3.json

**Comment by moufmouf** [comment]
@tbnobody I'm not sure this will work, as you need CORS enabled on the webserver that serves the page (and I don't think CORS is enabled in Gitlab).

I think the way to go is to generate a website from your Gitlab repository using Gitlab Pages (https://docs.gitlab.com/ee/user/project/pages/)

**Comment by Jacques-Olivier-Farcy** [comment]
I will try that, thanks

**Comment by Jacques-Olivier-Farcy** [comment]
Well, too complicated for me ... I will stay ion Github
