### ISSUE TITLE
Firefox does not show webcam permission dialog

### ISSUE THREAD

**Issue by tbnobody** [thecodingmachine/workadventure#555]
When showing the webcam selection site, my firefox 84.0.1 (64-Bit) does not show the dialog for the webcam permissions. It's only asking for microphone permissions. I figured out, that the problem is in the file front/src/WebRtc/MediaManager.ts:
```
let videoConstraint: boolean|MediaTrackConstraints = {
    width: { min: 640, ideal: 1280, max: 1920 },
    height: { min: 400, ideal: 720 },
    frameRate: {exact: valueVideo, ideal: valueVideo},
    facingMode: "user",
    resizeMode: 'crop-and-scale',
    aspectRatio: 1.777777778
};
```
If I remove the exact part from the frameRate constraint, everything works without any problems. This only occours with my firefox, chrome works without any problems.

**Comment by Informatic** [comment]
Ah, yeah. Just noticed that fix in rC3 fork - framerate request replaced with a direct requrest (`frameRate: valueVideo`). I can file a PR for that.

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

Same problem here, with :
Firefox 84.02 64bit on Windows 10 up to date.
The screen is black, the microphone is working.

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

As i need to use firefox, did you test this PR ?

**Comment by Informatic** [comment]
Yeah, it's pending as you can see: #581

**Comment by lunar-debian** [comment]
I confirm #581 to fix the problem: Firefox asks permission for the webcam and the microphone after this change.

**Comment by cweiske** [comment]
Works fine now.
