### ISSUE TITLE
Allow exitUrl to contain *any* URL

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#556]
Currently, *exitUrl* can only contain a relative or absolute **path** for a URL.
This is confusing for users. See #530.

From an end-user perspective, it makes sense that `exitUrl` can be any URL (and not necessarily a URL to a WorkAdventure room).

We should probably make sure that **any** URL can be put in exitUrl.
Proposal: if the URL is "out" of the WorkAdventure domain, we should simply do a "window.location = exitUrl" to redirect the user to a new website.

For instance: `exitUrl: https://google.com` should redirect to Google.

**Comment by LancelotBompard** [comment]
I too have encountered a situation where this feature would be usefull.
Any update about this ?

**Comment by gparant** [comment]
Hi @LancelotBompard today we are not developing this feature, but it stays in our backlog of improvement.

**Comment by moufmouf** [comment]
@LancelotBompard currently, you can use the scripting API to completely redirect someone to another page. It requires a bit more work than simply putting an property on a map layer, but it is possible!
