### ISSUE TITLE
Properties of TileLayers in Groups are ignored

### ISSUE THREAD

**Issue by tbnobody** [thecodingmachine/workadventure#564]
When adding a TileLayer with properties (e..g. playAudio) into a Group, no sound will be played. 
I think thats because of front/src/Phaser/Game/GameMaps.ts Line 56:
```
            if (layer.type !== 'tilelayer') {
                continue;
            }
```

It would be nice to group all e.g. sounds or websites of one map into a folder to have a more clear overview of the layer window.

**Comment by moufmouf** [comment]
Indeed! This is directly related to #421 .
We need to add support for layer groups. It's in the backlog!

Note: to anyone looking to contribute, this is an easy first contribution :)

**Comment by GRL78** [comment]
Group Layer are now supported : https://workadventu.re/map-building/api-room.md
