### ISSUE TITLE
Fallback to map loading in HTTPS

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#569]
When working in development mode, we are usually using HTTP instead of HTTPS.

So we are trying to load the maps on the HTTP protocol.
For distant maps (hosted in Github pages), this fails.

See:

https://github.com/thecodingmachine/workadventure/issues/536#issuecomment-753682769

I believe this is because the HTTP url must send a 301 or 302 HTTP response and I suspect CORS headers are not part of this 301/302 response. As a result, map loading fails.

We should probably try to detect errors while loading a map file, and if the map file was loaded using HTTP, try to load the same map file using HTTPS. That would allow easy debugging of remote maps from a local environment.

**Comment by moufmouf** [comment]
Note: we cannot simply use HTTPS always, otherwise, the local maps in "http://maps.workadventure.localhost" will not load anymore.

**Comment by CodeFreezr** [comment]
> 
> 
> Note: we cannot simply use HTTPS always, otherwise, the local maps in "http://maps.workadventure.localhost" will not load anymore.

I found a FF Setting for this: 
Options / Privacy & Security / HTTPS-Only Mode / Enable HTTPS-Only Mode in all windows

**Comment by Kharhamel** [comment]
This was done in #854
