### ISSUE TITLE
Feature : change the favicon when you are in a meeting

### ISSUE THREAD

**Issue by ThibBal** [thecodingmachine/workadventure#570]
It's not easy to detect the sound when someone leave your "bubble". It's also annoying to not be able to know if someone is still there (especially when people are running everywhere... and "biping" you)

It could be a good idea to "change" the favicon on purpose when a canal is still open:
- Change the color of the favicon (yellow to red)
- Add a little indicator (blue/red bubble in the bottom right corner of the favicon for example)

Thanks :)

**Comment by gparant** [comment]
#839

**Comment by ValdoTR** [comment]
> #839

@gparant the issue is not related to #839.

**Comment by gparant** [comment]
I keep this idea, but today many solutions can indicate that you are in discussion:
- The browser implements visual indicator when you are in discussion with a camera or microphone,
- There are sound and notification when someone tries to talk with you,
- There are sound when a person leaves the discussion.

<img width="328" alt="Screenshot 2023-01-06 at 13 58 24" src="https://user-images.githubusercontent.com/23724509/211017403-17d9b4d4-f4ec-4c36-9256-2bc9e732e1f2.png">
