### ISSUE TITLE
Feature: Touch Support 

### ISSUE THREAD

**Issue by hendrixfan** [thecodingmachine/workadventure#575]
First of all: Awesome Project! 
Tablet or Mobile Phone Users have a difficult time using the Game. Might it be possible to support touch input?

**Comment by Informatic** [comment]
There has been some initial work on touch input support for WorkAdventure for rC3, however I have no idea of its final state. (I've dropped the code [in a `feature/touch-support` branch](https://github.com/Informatic/workadventure/commits/feature/touch-support)) Maybe @Palid can follow up on this one?

**Comment by Palid** [comment]
Yeah, the touch support is super duper WIP and requires scaling changes to some font sizes, smarter way to define joystick etc.

**Comment by tabascoeye** [comment]
duplicates #402

**Comment by gparant** [comment]
#873
