### ISSUE TITLE
Update github-slug-action version

### ISSUE THREAD

**Issue by rlespinasse** [thecodingmachine/workadventure#58]
Hi, 

This project use the GitHub action [rlespinasse/github-slug-action](https://github.com/rlespinasse/github-slug-action) on the [master](https://github.com/rlespinasse/github-slug-action/tree/master) branch.  

Due to changes into the branches management, the `master` branch is not longer supported and will be removed in few months (_EOL: 2020-10-25_).

  The current latest version is `2.0.0` from the [v2.x](https://github.com/rlespinasse/github-slug-action/tree/v2.x) branch.

```yaml
- uses: rlespinasse/github-slug-action@2.0.0
- uses: rlespinasse/github-slug-action@v2.x
```

 If you want to avoid breaking changes, you can use the `1.1.0` version or the [v1.1.x](https://github.com/rlespinasse/github-slug-action/tree/v1.1.x) branch.

```yaml
- uses: rlespinasse/github-slug-action@1.1.0
- uses: rlespinasse/github-slug-action@v1.1.x
```

**Comment by moufmouf** [comment]
Thanks for notifying us! We will fix this!

**Comment by moufmouf** [comment]
Note for me: migrate to 2.0.0 and use GITHUB_REF_SLUG_URL instead of GITHUB_REF_SLUG
