### ISSUE TITLE
Firefox not showing video

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#580]
Hi there,

I am on Windows 10 up to date.

When using chrome, the video of my webcam is shown at the begining when i have to choose my input device.
Chrome Version 87.0.4280.141 (Build officiel) (64 bits)

But with Firefox 84.02 64bit i have a black screen.
Only the microphone is working good.

**Comment by cweiske** [comment]
See #555.
