### ISSUE TITLE
Absolute map exit URLs broken

### ISSUE THREAD

**Issue by Informatic** [thecodingmachine/workadventure#582]
6caa0e5b62dda41c2d9ba0e969c7cc35fd498379 seems to have broken support for absolute exit URLs, present eg. in: https://github.com/thecodingmachine/workadventure/blob/6caa0e5b62dda41c2d9ba0e969c7cc35fd498379/maps/Floor0/floor0.json#L317

Part of an unhandled exception on current `develop` (c2d0cda441dde6f4fed79aa742b11122b0bffd68):
```
Uncaught (in promise) Error: Invalid room ID
    Room Room.ts:20
    loadNextGame GameScene.ts:819
    __awaiter main.73a4142f950eaa8aaa91.js:263134
    __awaiter main.73a4142f950eaa8aaa91.js:263130
    loadNextGame main.73a4142f950eaa8aaa91.js:263770
    create GameScene.ts:370
    create phaser.js:98647
    loadComplete phaser.js:98559
    emit phaser.js:1929
    loadComplete phaser.js:193046
```

**Comment by quazgar** [comment]
Any news for this?

**Comment by gparant** [comment]
@quazgar we work on ti 🚀

**Comment by jonnytest1** [comment]
jsut type this for bsolute url as exitUrl  "/_/global/npeguin.github.io/coders-map/map.json"

**Comment by gparant** [comment]
Yes, this is the solution for this issue, add `/_/<roomid>/<url map without "https://">`.

Thanks for your feedback 💪 
Don't hesitate to a create new issue if you have any other requirement 🚀
