### ISSUE TITLE
Is there a cache system ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#584]
Hi,

I am doing some tests with maps these days to create a place for artists.

I noticed that when i update my files (the json map), there may be a delay of several minutes before the change is seen in real.
Is the server https://play.workadventu.re/ have a cache or maybe it is the web system on my github ?

And if it is in your web server, is there a way to disable this cache during test phase ?

**Comment by moufmouf** [comment]
There is no cache in WorkAdventure. You are editing your map using Github pages I guess. Github is taking a few minutes to update the pages.
If you want to be able to test in close to real time, you will need your own webserver (maybe a shared hosted web server with a HTTPS certificate and FTP uploads will do the trick)

**Comment by Jacques-Olivier-Farcy** [comment]
Great, it worked, adding this to my .htaccess file of my web server:

Header set Access-Control-Allow-Origin "https://play.workadventu.re"
