### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Nanane** [thecodingmachine/workadventure#587]
Hello,

Since the latest release (it seems there has been one), I can't seem to get workadventure to work anymore, whatever the map is.

I found the following logs in the console :
```
Started the game
--
phaser.js:104408 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
--
createAudioContext @ phaser.js:104408
--
phaser.js:87064      WorkAdventure / Phaser v3.51.0 (Canvas | Web Audio)  https://phaser.io
--
index.ts:78 Uncaught TypeError: Cannot read property 'add' of undefined
    at initialize.postBoot (index.ts:78)
    at initialize.start (phaser.js:159273)
    at initialize.texturesReady (phaser.js:159257)
    at initialize.h.emit (phaser.js:1926)
    at initialize.updatePending (phaser.js:100333)
    at initialize.h.emit (phaser.js:1907)
    at Image.r.onload (phaser.js:100463)
--
2phaser.js:104574 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
--
i @ phaser.js:104574
DevTools failed to load SourceMap: Could not parse content for https://coremeet.workadventu.re/external_api.min.map: Unexpected token < in JSON at position 0
```

Anyone ?

I'm on MacOS Catalina 10.15.7 and using Google Chrome Version 87.0.4280.88

**Comment by phonzon** [comment]
Hello! 
We have the same issue since yesterday. It seems that it have a problem to work with the map files. Can anyone help?
Thank you!

**Comment by moufmouf** [comment]
Hi @Nanane , Hi @phonzon ,

Indeed, there has been a release at 00.05 am today.
And there was one release at the end of last week.

I wonder if this is related to the map you are using (maybe with sounds?) or if this is related to the new "Phaser" game engine we are using.

Maybe you can help me to find out:

- What URL are you trying to access?
- Does it work if you access this URL: "https://play.workadventu.re" ?
- Does it work if you open WorkAdventure is private navigation?
- Does it also fail in Firefox?

**Comment by phonzon** [comment]
Hi moufmouf, 
are soundfiles not supported? 
I have the issue in chrome and firefox. Accessing "https://play.workadventu.re" works fine.

**Comment by moufmouf** [comment]
@phonzon Ok, we might have a clue here. Soundfiles are supported in maps since https://github.com/thecodingmachine/workadventure/pull/541.
This might be a regression due to the migration to Phaser 3.50 in https://github.com/thecodingmachine/workadventure/pull/562
Ping @Kharhamel 

@phonzon can you share your map URL so we can test on the same map?

**Comment by phonzon** [comment]
@moufmouf https://play.world.jg-stadtmitte.de/_/global/maps.world.jg-stadtmitte.de/jg/Hof.json

**Comment by moufmouf** [comment]
@phonzon in the map you shared, there seems to be resources loaded via TSX files rather than embedded in the JSON map and my guess it that this is the cause of your problems:

![image](https://user-images.githubusercontent.com/1290952/104333900-05bca500-54f2-11eb-9766-8ddc2dbcca63.png)

Could you check this and embed any tileset?

**Comment by phonzon** [comment]
This was a mistake in the beginning. Every tileset is now embedded, i just cant remove the tsx files from Tiled. or maybe not yet figured out how to.

**Comment by phonzon** [comment]
@moufmouf yesterday the map worked.

**Comment by moufmouf** [comment]
Ok. It does not seem to be related to sounds. Here is a map with sounds that work: https://play.workadventu.re/_/global/rc3-data.hackerspace.pl/main.json

So this is definitely related to upgrading to Phaser 3.50.
Maybe Phaser 3.50 is more picky about the JSON format and does not accept .tsx files anymore?
I'm not sure how to help you here. Could you try to remove the tsx reference in the JSON file (maybe by editing the file manually?)

**Comment by phonzon** [comment]
I'll try. Thanks for your support.

**Comment by Nanane** [comment]
Hi @moufmouf 

Sorry for the late reply, here is what I get : 

* What URL are you trying to access?
** I actually tried multiple maps, all with the same error : 
*** https://play.workadventu.re/_/randomId/yousign.github.io/Youniverse/map.json
*** https://play.workadventu.re/_/anything/nanane.github.io/workadventure_matters/map.json
* Does it work if you access this URL: "https://play.workadventu.re" ?
** Nope, same error
* Does it work if you open WorkAdventure is private navigation?
** Nope, same error
* Does it also fail in Firefox?
** Although it does not fail on firefox, I seem to get random black tiles on the map. I've reported it to other users and they don't have that problem either

Checked the maps I linked and there doesn't seem to be any sound or TSX file in them.

**Comment by Nanane** [comment]
So I dug a little bit, the error seems to be triggered by the `.add` in those lines in the `index.ts` file, at initialization :

```js
            // FIXME: we should fore WebGL in the config.
            const renderer = game.renderer as WebGLRenderer;
            renderer.pipelines.add(OutlinePipeline.KEY, new OutlinePipeline(game));
```

According to phaser3 documentation, the renderer can be either Phaser.Renderer.Canvas.CanvasRenderer or Phaser.Renderer.WebGL.WebGLRenderer depending on the type given in the configuration object.
When i look up each class, I found that only the WEBGL renderer has a `pipelines` prop from which we can use `.add`.
So I'm guessing I'm using the wrong renderer.

And to add to this theory, the configuration object provides the type `type: Phaser.AUTO` instead of using `Phaser.WEBGL` which would set it to always be a WEBGL renderer.

I think that's what's causing a problem here.

**Comment by moufmouf** [comment]
@Nanane it makes a lot of sense! The problem is definitely here.
Thanks for digging into this, I'll issue a fix.

**Comment by moufmouf** [comment]
@Nanane, out of curiosity, what kind of hardware are you using? (since Phaser chooses WebGL by default, I suppose you don't have a graphics card supporting OpenGL/3D)

**Comment by Nanane** [comment]
It seems a bit weird to me because I'm using a pretty recent macbook (bought last year). the graphic card is an "Intel UHD Graphics 630 1536 Mo"

**Comment by Fabrizioso** [comment]
It's still happening to me (Chrome on Macbook Pro 2017). Reproducible when I e.g. open the office map, exit to the street and enter the pub. It seems to happen not always, sometimes a simple reload solves it, mostly not.

**Comment by Nanane** [comment]
@Fabrizioso Even though it's been merged, I don't think the fix is part of the current production release.
We may have to wait a little before it is.

Also, if reloading fixes your issue, then I think there's a chance this fix might not resolve it.

**Comment by Nanane** [comment]
Thank you @moufmouf for your support !

**Comment by moufmouf** [comment]
@Fabrizioso :+1: it is indeed not in production yet. The fix will be released in the next release (in the coming days)

**Comment by Nanane** [comment]
Just so you know, I just tried today on Chrome again, and it's working now.
Haven't encountered any problem whatsoever on Chrome.

Thank you !

**Comment by Fabrizioso** [comment]
Also confirmed on my side, works great now! Thanks @moufmouf ! :-)
