### ISSUE TITLE
Map freeze with more than one user

### ISSUE THREAD

**Issue by t10r** [thecodingmachine/workadventure#591]
Hi,

I just pull the newest develop commit and updated my docker via `docker-compose up -d --force-recreate`. Now the map is frozen after some seconds. WebRTC Audio works, Video gets black a little later.

**Comment by t10r** [comment]
Hm, okay, looks already fixed in a even newer one. thx

**Comment by t10r** [comment]
the problem again occurs. That is what I can see in the log

´´´
workadventure-pusher      | 2021-01-13T20:24:35.321Z zone Opening connection to zone 2, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.325Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:35.321Z zone Opening connection to zone 3, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.325Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:35.321Z zone Opening connection to zone 4, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.326Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:35.321Z zone Opening connection to zone 5, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.326Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:44.266Z zone Closing connection to zone 2, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.326Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:44.266Z zone Closing connection to zone 3, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.327Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:44.266Z zone Closing connection to zone 4, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.327Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:44.266Z zone Closing connection to zone 5, 5 on back server
workadventure-back        | 2021-01-13T20:24:35.327Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:45.553Z zone Opening connection to zone 3, 2 on back server
workadventure-back        | 2021-01-13T20:24:35.327Z roommanager listenZone called
workadventure-back        | 2021-01-13T20:24:35.327Z roommanager listenZone called
workadventure-back        | 2021-01-13T20:24:44.266Z roommanager listenZone cancelled
workadventure-back        | 2021-01-13T20:24:44.266Z roommanager listenZone cancelled
workadventure-pusher      | 2021-01-13T20:24:45.553Z zone Opening connection to zone 4, 2 on back server
workadventure-pusher      | 2021-01-13T20:24:45.554Z zone Opening connection to zone 5, 2 on back server
workadventure-pusher      | 2021-01-13T20:24:46.599Z zone Closing connection to zone 5, 3 on back server
workadventure-back        | 2021-01-13T20:24:44.266Z roommanager listenZone cancelled
workadventure-pusher      | 2021-01-13T20:24:46.599Z zone Closing connection to zone 2, 4 on back server
workadventure-back        | 2021-01-13T20:24:44.266Z roommanager listenZone cancelled
workadventure-pusher      | 2021-01-13T20:24:46.600Z zone Closing connection to zone 3, 4 on back server
workadventure-back        | 2021-01-13T20:24:45.559Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:46.600Z zone Closing connection to zone 4, 4 on back server
workadventure-back        | 2021-01-13T20:24:45.560Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:46.600Z zone Closing connection to zone 5, 4 on back server
workadventure-back        | 2021-01-13T20:24:45.560Z roommanager listenZone called
workadventure-pusher      | 2021-01-13T20:24:46.600Z zone Closing connection to zone 5, 2 on back server
workadventure-back        | 2021-01-13T20:24:46.602Z roommanager listenZone cancelled
workadventure-back        | 2021-01-13T20:24:46.602Z roommanager listenZone cancelled
workadventure-back        | 2021-01-13T20:24:46.602Z roommanager listenZone cancelled
workadventure-back        | 2021-01-13T20:24:46.603Z roommanager listenZone cancelled
workadventure-back        | 2021-01-13T20:24:46.603Z roommanager listenZone cancelled
´´´

Can I find somewher more informations?

On this picture I freezed and don't push any key. The browser is Chromium.
![image](https://user-images.githubusercontent.com/10079842/104506852-d84d2580-55dd-11eb-8fd3-015975f4edc6.png)

**Comment by t10r** [comment]
In this case I'm frozen right away and my avatar isn't loaded

![image](https://user-images.githubusercontent.com/10079842/104507638-fe26fa00-55de-11eb-9802-4e781b1300c9.png)

**Comment by t10r** [comment]
Okay, I realized that this always happen when I'm not alone. So, if I alone I can move as long as I want but in the moment I enter with a second avatar it freezes.

**Comment by moufmouf** [comment]
Ok, could you look in the logs of your browser? (in the console pane of the development tool).
Anything meaningful here?

**Comment by moufmouf** [comment]
Ok, I can reproduce the issue.
Here is what I can see:

![image](https://user-images.githubusercontent.com/1290952/104508537-ac836d00-55e8-11eb-90b1-8b021babd770.png)

This is probably related to #588 or to #573 .

Ping @Kharhamel

**Comment by t10r** [comment]
Yes, this I found now too.

**Comment by t10r** [comment]
Is this connected with the problem?

![image](https://user-images.githubusercontent.com/10079842/104516536-69c39400-55ec-11eb-9e34-b43ec5c530f3.png)

**Comment by kabitk** [comment]
I'm seeing this in the browser:

`net::ERR_CONNECTION_REFUSED
PlayerTexturesLoadingManager.ts:37 Loading Female5
phaser.js:4671 Uncaught TypeError: this.src.indexOf is not a function
    at SpriteSheetFile.load (phaser.js:4671)
    at LoaderPlugin.<anonymous> (phaser.js:192900)
    at Set.each (phaser.js:39075)
    at LoaderPlugin.checkLoadQueue (phaser.js:192886)
    at LoaderPlugin.start (phaser.js:192836)
    at Object../src/Phaser/Entity/PlayerTexturesLoadingManager.ts.exports.lazyLoadPlayerCharacterTextures (PlayerTexturesLoadingManager.ts:44)
    at GameScene.doAddPlayer (GameScene.ts:1058)
    at GameScene.update (GameScene.ts:985)
    at Systems.step (phaser.js:47524)
    at SceneManager.update (phaser.js:98598)
ConsoleGlobalMessageManager.ts:191 Uncaught (in promise) TypeError: Quill is not a constructor
    at ConsoleGlobalMessageManager.<anonymous> (ConsoleGlobalMessageManager.ts:191)
    at Generator.next (<anonymous>)
    at fulfilled (log.js:59)`

**Comment by Kharhamel** [comment]
The condition I used to know where to find the textures' url was false in some case. I will push this fix on master as soon as possible.

**Comment by t10r** [comment]
@Kharhamel with your fix a get this now
![image](https://user-images.githubusercontent.com/10079842/104581633-be9bf480-5656-11eb-8123-69cc3bae4eab.png)

**Comment by t10r** [comment]
Thx very much. Now it works

**Comment by Kharhamel** [comment]
Sorry the issue was auto closed by github. Can you confirm to me you don't have the bug anymore?

**Comment by t10r** [comment]
Yes, it works.
