### ISSUE TITLE
Multiple website ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#604]
I am trying to have several tiles that show different website.

I use two layers web1 and web2 with the property openWebsite with two different url.
But only one seems to work.

**Comment by wolskey** [comment]
in my case i have duplicate website even though i have 2 different links on different layers

**Comment by Jacques-Olivier-Farcy** [comment]
I also had this issue @wolskey

**Comment by k33la1n0** [comment]
hi there, maybe the problem can be, that the layer's (when they are duplicated with tileset's) overlapping other layer with openWebsite. so in my case, i duplicate my first openWebsite-layer (web1, web2, web3, web4, ...) and than i place my web-tileset's step for step for each web-layer (web1 than web2 than web3 than web4 ...).

that is my solution for this.

**Comment by gparant** [comment]
Hi 

To day it's no possible to show two website or one website and one Jitsi in same time. We work on it and propose you a design solution soon 🚀

**Comment by gparant** [comment]
This feature is in progress and @nolway could be proposing a first beta version soon 🚀
