### ISSUE TITLE
Raspberry PI HQ cam not working

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#605]
Hi,

I tried to use a raspberry pi with a HQ cam.
And workadventure seems to not recognize it even if when i use a simple Jitsi instance, it is working fine.

I have a raspbian up to date with Chomium Version 86.0.4240.197 (Build officiel) Built on Raspbian , running on Raspbian 10 (32 bits)

**Comment by gparant** [comment]
I close this issue and we still available if you have any other question.

Thanks for your feedback 💪
