### ISSUE TITLE
Self-Hosted instances are tracked with Google Analytics by default

### ISSUE THREAD

**Issue by loelkes** [thecodingmachine/workadventure#606]
Why was #161 merged? It enables tracking for self hosted instances as well.

**Comment by BenBE** [comment]
The question is even: Why should there be any tracking at all. This makes the software non-GDPO-compliant by default, which is probably not the route you should go.

**Comment by moufmouf** [comment]
Hey @loelkes @BenBE ,

You are completely right, this is a mistake.

When #161 was merged, WorkAdventure was about 2 months old, it was deployed absolutely nowhere besides our main instante and I'm not even sure it had a license at all :)
In a short few months, WorkAdventure gained a lot of traction and we need to fix this (which means making Google Analytics tracking on option in the deployment and not hard coded, and ensuring GDPR compliance if Google Analytics is enabled).

We will fix this :+1:

**Comment by moufmouf** [comment]
Closed by #623 and #628
