### ISSUE TITLE
Circle Video chat not working for few users

### ISSUE THREAD

**Issue by navlisilvan** [thecodingmachine/workadventure#607]
Hello,

since about one week we have the issue, that the video chat in a circle isn´t starting for some users. Jitsi rooms are working but not in the circle.
One user was from spanish LTE internet, was working after going through commercial VPN to germany. One User from Germany was via vodafone LTE but not working after going to university wifi. 
Does someone have an idea, how to solve this (everytime Chrome/Chromium).

Thanks!

**Comment by mritzmann** [comment]
@TheCodingMachine Maybe you can add "GitHub Discussions" for things like this? :) https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

**Comment by silversmarty** [comment]
Hello, 
I've got the same issue : when two users meet (user A and user B) the video call starts when user A meets user B, but not when user B meets user A (connection is loading endlessly). 
I've noticed this problem several times, without being able to explain where it comes from.
Seen on Chrome.

Thanks

**Comment by cweiske** [comment]
This could be fixed with #250.

**Comment by gparant** [comment]
Hi,

We have updated configuration of our TURN and STUN. Many problems of connection was fixed. Some VPN or Wifi configuration or proxy dosen't permit to authorize access and connection. Please open a new issue if you have any other problem.

I close this issue and we still available if you have any question.

Thanks for your feedback 💪

**Comment by tabascoeye** [comment]
@gparant can you be a bit more verbose for those self-hosters out there?
I host my own TURN server as well and would love some hints
