### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by t10r** [thecodingmachine/workadventure#608]
May anybody help me with this problem. Today I have a small event and me video keep vanishing after some time

![image](https://user-images.githubusercontent.com/10079842/104813637-aa98f400-580a-11eb-95e3-fb9055c555aa.png)

**Comment by loelkes** [comment]
Seems related to #574

**Comment by t10r** [comment]
@loelkes Maybe.

It looks like the video only went black on the camera selection during entrance.

**Comment by gparant** [comment]
https://github.com/thecodingmachine/workadventure/issues/574#issuecomment-779712155
