### ISSUE TITLE
how can others enter my world on my own server? 

### ISSUE THREAD

**Issue by DEtrees95** [thecodingmachine/workadventure#609]
how can I make my own server accessible to others? I myself come along with: http://workadventure.localhost/

http://workadventure.myip/ didn't work=( pls help =)

sorry for my bad english

**Comment by spezi** [comment]
you have to learn some about docker, docker-compose etc. to host yourself ;)

**Comment by 4clu** [comment]
@DEtrees95 do you find something out? :)

**Comment by gparant** [comment]
Hi,

I close this issue, we still available if you have any other question.

Thanks for your feedback 💪
