### ISSUE TITLE
Trigger to display layer

### ISSUE THREAD

**Issue by eazyliving** [thecodingmachine/workadventure#610]
I'd love to have the possibility to trigger showing/hide a layer.

That could work this way: create a trigger layer (like exitUrl or openWebsite) with a property named "switchLayer". That layer would switch visibility on stepping on a tile of this trigger layer.

I'd like to display text (in a bubble of course ;)) while standing in front of a display or smth like that.

Or maybe I missed something in the documentation and that is already possible?

**Comment by quicksketch** [comment]
I would also find this helpful to open and close doors. Walk into the door and it would hide the layer. Walk past it and it and layer could show again.

**Comment by moufmouf** [comment]
@quicksketch We are currently thinking on how to do this properly.

What we really want to do is to be able to have a switch to be able to lock a door.

- So we need to be able to enable/disable a "door" layer when the switch is triggered.
- BUT, we also need to be able to automatically unlock the door if people locked in a meeting are disconnecting without opening the door again. And this part is really tricky.

**Comment by GRL78** [comment]
Now possible with the scripting Api : https://workadventu.re/map-building/api-room.md#show--hide-a-layer
