### ISSUE TITLE
Enabled/disabled state for mic/video should be kept between rooms

### ISSUE THREAD

**Issue by BenBE** [thecodingmachine/workadventure#611]
When jumping between rooms the state for microphone/camera is always reset to active. On a large map, consisting of many rooms this can become quite annoying as disabling the camera in one place seems to arbitrarily re-activate it when switching/teleporting to another room.

Noticed on the rC3 deployment recently.

**Comment by gparant** [comment]
We have deployed feature that permit to save your configuration.

I close this issue and we still available if you have any question.
Thanks for your feedback 💪
