### ISSUE TITLE
websites refuse to be opened in workadventure

### ISSUE THREAD

**Issue by TV-Plagwitz** [thecodingmachine/workadventure#612]
Most websites like youtube.com or other dont allow to be openend in workadventure with openWebsite property. Is there any option to automaticly open links in an new browsertab instead of in the workadventure?

**Comment by evrardjp** [comment]
I have the same issue. Firefox complaints about security, because links I try to open are not from the same base domain. Is there anything we could do for that?

**Comment by Jacques-Olivier-Farcy** [comment]
For youtube videos, you need to take the "embed" link, like in this example :
https://www.youtube.com/embed/ytPsiuXqcNY

And to open your own map, you need to have CORS enable in your webserver options

**Comment by evrardjp** [comment]
The map itself opens, it's just external links inside the map. Is that the same thing?

**Comment by Jacques-Olivier-Farcy** [comment]
Can you write here the link of this website that is'nt showing right please ?

**Comment by evrardjp** [comment]
I tried with github: https://github.com/thecodingmachine/workadventure

**Comment by cweiske** [comment]
Some websites prevent being displayed in frames - and workadventu.re uses an `<iframe>` to display the website.

Github does this for example:
```
$ curl -I https://github.com/thecodingmachine/workadventure
...
x-frame-options: deny
```

**Comment by gparant** [comment]
Thanks for your feedback 💪 

I close this issue and we still available if you have any question.

**Comment by jonnytest1** [comment]
PS sometimes it helps to make a small html file next your map that includes the 3rd party iframe in the HTML with src tag 

Especially if the third party has an amber link available somewhere this always worked for me

Because workadventure doesn't instantiate iframes with an origin I assume
