### ISSUE TITLE
Internationalization (i18n) support

### ISSUE THREAD

**Issue by lunar-debian** [thecodingmachine/workadventure#615]
While there is not that much text in the frontend, it’s still in English. Users might prefer to use WorkAdventure in an interface supporting their native language.

There is currently no support for internationalization (i18n) in the current front-end, so it would be a first step before localization (l10n).

**Comment by lunar-debian** [comment]
See #616 for a quick hack to get the interface in broken French (no accents in several places).

**Comment by nolway** [comment]
[wip ](https://github.com/thecodingmachine/workadventure/pull/1629)
