### ISSUE TITLE
Put some clothes on the “default” custom avatar

### ISSUE THREAD

**Issue by lunar-debian** [thecodingmachine/workadventure#617]
If one selects “Customize your own avatar”, then press go on to press Enter, they will get an almost naked avatar. The current interface to design the avatar is a bit clumsy, especially if you expect to use a mouse instead of a keyboard. So it’s easy to make a mistake, press Enter, and be thrown in a pool of strangers feeling almost naked. While this is *just* an avatar, it’s still not a good feeling to get while discovering new software.

I believe the fix would be to preselect a more neutral avatar instead of the leftmost element of each customization rows. While a random selection could do the trick, it might also result in surprising (and maybe unpleasant) setup, so I believe manual selection would be better.

**Comment by gparant** [comment]
We deploy a new version of custom avatar #918 

I close this issue. We still available if you have any question.
Thanks for your feedback 💪
