### ISSUE TITLE
Website is shown a blank page

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#624]
Hi,

I am trying to show this website :
[](https://interstices.ouvaton.org/chamane2)

But it is not working, any ideas ? Maybe some scripts (in that case javascript) are not allowed even if they are on the same domain ?

![image](https://user-images.githubusercontent.com/19731340/105047356-820f3500-5a6a-11eb-9a5c-584a56fc8e6a.png)

**Comment by cweiske** [comment]
Do you see errors on your browser console?

The black rectangle on the right could be a Jitsi meeting room popup that is loaded from another server.

**Comment by cweiske** [comment]
Do you see errors in the browser console?

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

the website is : [Chamane2](https://interstices.ouvaton.org/chamane2/)

**Comment by cweiske** [comment]
What does the browser console show?
I also notice that this page is running very very slow if the window is large.

**Comment by Jacques-Olivier-Farcy** [comment]
The console in firefox :

Le « Content-Type » HTTP « text/html » n’est pas géré. Le chargement de la ressource média https://play.workadventu.re/ a échoué. map1.json
Blocage du chargement du contenu mixte actif (mixed active content) « http://interstices.ouvaton.org/chamane2/ »

And there is a link to have details :
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by Jacques-Olivier-Farcy** [comment]
And in Chrome :

Mixed Content: The page at 'https://play.workadventu.re/_/global/hart.ouvaton.org/MAP-FANTASY/map1.json' was loaded over HTTPS, but requested an insecure frame 'http://interstices.ouvaton.org/chamane2/'. This request has been blocked; the content must be served over HTTPS.

**Comment by Jacques-Olivier-Farcy** [comment]
Strange, because it is https in the map, not http

**Comment by cweiske** [comment]
Ha. The URL above that you gave me in https://github.com/thecodingmachine/workadventure/issues/624#issuecomment-768952488 is wrong.

The URL in your map is `https://interstices.ouvaton.org/chamane2` without the slash.

When adding the website to the map with the slash, all is fine.
But the URL without the slash *redirects to http*:
```
$ curl -I https://interstices.ouvaton.org/chamane2
HTTP/1.1 301 Moved Permanently
Date: Fri, 29 Jan 2021 05:51:28 GMT
Server: Apache/2.4.25 (Debian)
Location: http://interstices.ouvaton.org/chamane2/
```

**Comment by Jacques-Olivier-Farcy** [comment]
This was a tricky one.
I am now using the whole path in the property :
https://interstices.ouvaton.org/chamane2/index.html

And it is working good.

Thanks a lot for your efforts

**Comment by Jacques-Olivier-Farcy** [comment]
Solved
