### ISSUE TITLE
Camera not working in WebRTC

### ISSUE THREAD

**Issue by gmoirod** [thecodingmachine/workadventure#627]
I use Firefox 78.6.1esr (64-bit) on Debian 10.
I allowed the use of my camera. Firefox indicates it.

![image](https://user-images.githubusercontent.com/12263385/105167116-96aa0680-5b18-11eb-9e80-feadb29e8dfd.png)

At start, when i have to choose mic and camera, cameras are listed but no one is captured.
I got : 
`Error get camera, trying with video option at null MediaManager.ts:398:20`

Then in the map, my camera works with Jitsi calls in WorkAdventure but not in 1-to-1 in WebRTC :
```
Error: Video track is empty, please check camera permission of your navigator
    enableCamera MediaManager.ts:218
MediaManager.ts:223:20
    enableCamera MediaManager.ts:223
```

**Comment by cweiske** [comment]
I also have the problem that the public play.workadventu.re worlds do have a camera problem right now - I never see my camera stream.

**Comment by cweiske** [comment]
Maybe this is a duplicate of #555.

**Comment by gmoirod** [comment]
Good catch @cweiske !!
This PR did the trick : https://github.com/thecodingmachine/workadventure/pull/581
I tested it live in Firefox. This should be merged quickly :-)

**Comment by gmoirod** [comment]
Closed by https://github.com/thecodingmachine/workadventure/issues/555
