### ISSUE TITLE
dist/index.html not found on boot

### ISSUE THREAD

**Issue by atomheartother** [thecodingmachine/workadventure#630]
Hello!

I'm trying to run a self-hosted instance, I just pulled the `develop` branch, and I'm running into a bug in the `front` service:

```
front_1          | Child HtmlWebpackCompiler:
front_1          |     
front_1          |     ERROR in Entry module not found: Error: Can't resolve '/usr/src/app/dist/index.html' in '/usr/src/app'
front_1          | ℹ ｢wdm｣: Compiling...
front_1          | ✖ ｢wdm｣: Hash: 7b5121ac3d682851f48f
front_1          | Version: webpack 4.44.2
front_1          | Time: 68ms
front_1          | Built at: 01/20/2021 6:27:57 PM
front_1          | ℹ ｢wdm｣: Failed to compile.
front_1          |  1 asset
front_1          | Entrypoint main = main.6939f21f071ae090e11e.js
```

I went into the container and checked, `index.html` indeed was never compiled from the template... Did I miss a step? As far as the README says I should be able to just `docker-compose up` and it works.

```
workadventure|develop ⇒ docker --version
Docker version 20.10.2, build 2291f610ae
workadventure|develop ⇒ docker-compose --version
docker-compose version 1.28.0, build unknown
```

**Comment by l4b4r4b4b4** [comment]
Same issue here on first startup. 
Both on local machine (ubuntu 20.04) and on a dedicated server running Debian.

**Comment by tbnobody** [comment]
in docker-compose.yaml in the front service change the line
`STARTUP_COMMAND_1: yarn install`
to
```
STARTUP_COMMAND_0: ./templater.sh
STARTUP_COMMAND_1: yarn install
```

**Comment by moufmouf** [comment]
Indeed, this is directly related to #623 .
I'll fix this right now!
