### ISSUE TITLE
Edit Skin / Name while in Jitsi

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/workadventure#633]
Editing name or skin while in Jitsii room duplicates user in Jitsi

* edit Name or my Skin while I'm in a Jitsi room, 
* save name of skin

You are redirected to the start point of the map, but you remain in the jitsi discussion. So, if you re-enter the jitsi room, you are there twice. Going out and in again fixes the duplicate issue.

**Comment by tabascoeye** [comment]
reproduced on my fork and fixed. Will provide a PR
