### ISSUE TITLE
Comment crée t'on un nouveau calque ? How do you create a new layer ?

### ISSUE THREAD

**Issue by MHR13-93** [thecodingmachine/workadventure#636]
Bonjour, 
Je ne parviens pas à créer un nouveau calque pour ajouter une réunion jitsi a un espace. Vous avez bien abordé ce sujet dans votre guide, mais bien trop succinctement pour une super débutante comme moi..
Vous dites qu'il faut créer un calque spécifique -> d'accord mais de quel type : objet ? tuile ? 
Pour l'étape d'après je bloque aussi en partie. Je me suis inspirée de ce que j'ai pu trouver dans ce forum mais ça n'a pas l'air de fonctionner.. Je suppose qu'il faut sélectionner des tuiles/objets pour "déclencher" cette réunion mais je n'ai aucune idée de comment faire. 
Je vous remercie par avance pour votre aide !

Hi, 
I can't create a new layer to add a jitsi meeting to a space. Despite the fact that you've covered this topic in your guide, it's far too short for a super beginner like me...
You say that we need to create a specific layer -> ok but, which type : object ? tiles ? 
I'm stuck at the next step as well. I took inspiration from what I could find in this forum, but it seems that it doesn't work for me... I guess you have to select tiles/objects to "trigger" this meeting but I have no idea how to do it. 
Thank you in advance for your help!

**Comment by MHR13-93** [comment]
Bonjour @Jacques-Olivier-Farcy et merci pour ton retour ! 

Ce qu'il me manquait comme information c'était le type de calque qu'il fallait mettre (objet, tuile etc). Après les avoir tous essayés j'ai vu que c'était celui "tuile" qu'il fallait mettre (ça tombe sous le sens après-coup) + pour que la réunion se déclenche on peut par exemple poser une tuile appartenant à ce calque.
Merci beaucoup pour ton guide, il m'a beaucoup aidé. Par contre à ce propos : 
- Est ce normal que la fonction "jitsi-office" m'ouvre une réunion jitsi déjà utilisé par d'autres personne ?
- La fonctionnalité "ondemand" ne marche pas pour moi. Ce n'est pas grave car j'ai trouvé une alternative. Je voulais juste te le faire remarquer au cas où tu rencontrerai le même problème.

Merci encore

**Comment by Jacques-Olivier-Farcy** [comment]
J'avais constaté le démarrage d'une réunion où il y avait d'autres personnes avec jitsi-office, je croyais à un bug, c'est embêtant.

Pour moi non plus la fonction ondemand n'est pas fonctionnelle.

Tu peux décrire l'alternative dont tu parles ?

Et je suis preneur pour des retours d'expérience, à l'occasion on peut se retrouver sur une carte ? :)

**Comment by gparant** [comment]
Je ferme cette issue. Nous restons disponible si vous avez des questions.

Merci pour votre feedback 💪
