### ISSUE TITLE
wrong link to test-maps on website 

### ISSUE THREAD

**Issue by dimdle** [thecodingmachine/workadventure#637]
Hi,
Some of the test-maps on your websites does not work, because there is the https:// in the link which leads to double it in the game.
![grafik](https://user-images.githubusercontent.com/12907384/105455319-967a4a00-5c83-11eb-8308-37a3b3ae97d9.png)

**Comment by moufmouf** [comment]
Indeed!
We introduced a bug in the latest version of the website. This is fixed now.

Thanks a lot for reporting the issue!
