### ISSUE TITLE
Not sure where to start, what am I missing ?

### ISSUE THREAD

**Issue by ybizeul** [thecodingmachine/workadventure#640]
It seems like people are being successful doing stuff with that project...

I just can't get anywhere, I get 404 when I try to access, just following the doc.

Fumbling with the github issues I kinda found out some people are using play.workadventure.localhost, which kind of started to show some stuff but Network error pops up on a black screen.

Really confused about the whole thing, the doc almost looks like you're supposed to run that local, and I'm installing it on a remote VM, which is the only installation context that makes sense to me, what's the point of a local install ?

Thanks for your lights and pardon my confusion...

**Comment by tabascoeye** [comment]
there are pending PRs which will make everything a lot easier #576 #577 #578 for example.
Either you have to jumble something together or be patient for the docker-compose and deployment to get more straight forward.
It's being worked on…

**Comment by ybizeul** [comment]
Thanks I’ll take a look at these PRs and close this for now !
