### ISSUE TITLE
Add the possibility to activate / desactivate a layer ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#643]
Hi,

I would like some areas of the map to be accessible at certain times, but I would also like to be able to close them at other times.
Is there a ways to have a property on a layer like; maybe: on / off , so we can activate or desactivate the zone.

In that case for example, i will be able to make a block layer, and open or close a "door area" (with blocks collides) easely, just by changing a property in the map.

**Comment by tabascoeye** [comment]
I searched for a possibility like that for a long time. But the way the architecture is created, basically everything happens on the client side (i.e. your browser) and after the map is loaded.
So any changes on the map will only be seen after a reload.
==> I don't see this happening without major code rework

**Comment by Jacques-Olivier-Farcy** [comment]
I see.
As i am planning an event, i think i will change the map during the night, to have changes activated the next day 😄 
Or maybe some php scripts that automatticaly edit the json to make changes.

**Comment by moufmouf** [comment]
You can definitely generate the JSON file of the map using PHP, on the fly :)
But as @tabascoeye points out, the users already on the map will not see those changes. So indeed, you'd better do that overnight.

I'm starting thinking about ways to handle these use cases, but indeed, it is difficult without a major code rework.

**Comment by GRL78** [comment]
Now possible with the scripting Api extra : https://workadventu.re/map-building-extra/doors.md
