### ISSUE TITLE
Enforce jitsi viewer / moderator roles

### ISSUE THREAD

**Issue by znerol** [thecodingmachine/workadventure#654]
Whether or not someone joins a jitsi as a viewer or moderator currently depends entirely on client controlled properties (see [handleQueryJitsiJwtMessage](https://github.com/thecodingmachine/workadventure/blob/c466ba8ca5e06e165e5c95387ba6d454ed786da7/back/src/Services/SocketManager.ts#L583-L600):

```javascript
    public handleQueryJitsiJwtMessage(user: User, queryJitsiJwtMessage: QueryJitsiJwtMessage) {
        const room = queryJitsiJwtMessage.getJitsiroom();
        const tag = queryJitsiJwtMessage.getTag(); // FIXME: this is not secure. We should load the JSON for the current room and check rights associated to room instead.
        // [...]
        // Let's see if the current client has
        const isAdmin = user.tags.includes(tag);
        const jwt = Jwt.sign({
            // [...]
            "room": room,
            "moderator": isAdmin
            // [...]
```

The comment suggest that this should be fixed by loading *the JSON for the current room and check rights associated to room instead.*

So there are two problems here:
1. The json is currently not available in `back` and `pusher` components.
2. The json is very likely also controlled by the client.

So even if the json would be available in `back` and `pusher`, we still cannot trust the values contained in there.

**Proposed solution**

I guess the following approach might work instead: Continue to accept properties set in the map / tags on the user but additionally call into the `adminApi` and verify them (if the `adminApi` is available / the world is not anonymous).

**Comment by gparant** [comment]
Deployed with the new release 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create a new issue 😍
