### ISSUE TITLE
Different look from editor

### ISSUE THREAD

**Issue by Corps-git** [thecodingmachine/workadventure#656]
Hello,

I am confused about the usage of tilesets.

Found a tileset (png-file).
Used it in a map - works fine.

Now I try to use the same tileset in a new map - looks completely fine in the Tiled-editor. But if then used via workadventure, the tiles look completely different, as if taken randomly from another part of the png-file.

What can I do?

**Comment by yona-h** [comment]
happened to me once when I pushed the map directly to gh-pages and not to master, could that be the problem?

**Comment by Corps-git** [comment]
Hello yona-h, thanks for your answer.

I am not quite sure if that can be the problem. I've got only rudimentary knowledge of GitHub-functionality.

I cloned the whole repository to my local drive. I edited the first map there (which works fine). I created more maps (which have the problems described).
But all those maps are pushed to GitHub (via the GitHub-desktop) in the same way, I can see them there in the same directory.

So I am not sure it could be possible that one map is in the master and the others in gh-pages. Nor would I know how to direct the other maps to go to the master.

**Comment by yona-h** [comment]
in desktop it says _current repository_ and _current branch_ and _fetch origin_ on top. Current branch should be set to master. If thats not it I dont know what could...

**Comment by Corps-git** [comment]
Thanks again - that is good to know anyway.
But as "current branch" is set to master, the must be a different problem. I keep trying ;-)

**Comment by Corps-git** [comment]
Interesting.

I started fresh, cloning a new repository.
Then copied my map (the one which worked) from the old repository.

And get an error, because a png-file is missing (and those are the tiles causing problems with the other maps).

I don't understand how workadventure handles tilesets.

A new tileset (as png) must be loaded into Tiled. 
There it is converted into a tsx-file which is used by Tiled. And that's what is no used in the editor, for example for setting tile properties.

For workadventure I need to imbed the tileset. In my understanding all necessary information should then be stored in the json-mapfile. png and tsx should no more be necessary.

Is that idea correct?

**Comment by tabascoeye** [comment]
no it's not. The JSON only contains metadata about the tileset, not the actual pixels. Those are and always will be in the png

**Comment by Corps-git** [comment]
Thank you
