### ISSUE TITLE
Update of map information

### ISSUE THREAD

**Issue by Corps-git** [thecodingmachine/workadventure#657]
Hello,

the behaviour of the workadventure-run-time is strange.

If I alter something on my map, save the changes, push the updated map to GitHub, then start workadventure again - it very often still uses the old map. Seems to be randomly at which time the new map is recognized.
Even if I close my browser, delete all cookies and start fresh the old map still seems to linger somewhere in the background of the workadventure-environment and will be used.

Which makes all sorts of error-testing and repairing very annoying - as I never can be sure my repairs are really used.

**Comment by djmaze** [comment]
The map is loaded by your browser, not by the backend app. Looks like some sort of build / caching problem at Github? I don't experience this problem. (Not using Github, but selfhosting the map.)

**Comment by Corps-git** [comment]
Thanks for your answer - seems plausible.
Honestly a repository like Github was not really meant for so many small iteration tests I need for workadventure ...

I would prefer selfhosting anyway. But the workadventure documentation is sparse, especially on this topic.

Is it sufficient to copy the necessary stuff to a webspace of some provider? 
And what would the necessary stuff comprise?

**Comment by djmaze** [comment]
Almost. You need the webspace, but every response needs to include the `Access-Control-Allow-Origin: *` header (or the workadventure domain instead of `*`) so the map can be loaded from within workadventure. You can set that within your webserver (e.g. nginx) or reverse proxy (e.g. traefik) config.

**Comment by Jacques-Olivier-Farcy** [comment]
I had the same problem using a map via github.
There is a delay between the modification of the file and the actual update on the Github web server.

**Comment by cweiske** [comment]
Github pages has 10 Minutes caching time. So depending on the browser, you'll need to wait 10 minutes.
Alternatively open a new private window and open the map there.

**Comment by Corps-git** [comment]
That was my guess - I did try with deleting the workadventure-cookie and that worked too.

**Comment by moufmouf** [comment]
We added a special page in the documentation regarding self-hosting: https://workadventu.re/map-building/hosting

If you have any comments on how we can improve this page, please tell me :)

**Comment by gparant** [comment]
I close this issue and we still available if you have any question.

Thanks for your feedback 💪
