### ISSUE TITLE
Youtube sharing not working

### ISSUE THREAD

**Issue by mapapuche** [thecodingmachine/workadventure#661]
Hello,

when i try to share video youtube with my mate, the youtube video is launching correctly for me, but not for my collegue. They see the youtube player, but the video did not launch, and they can't click to launch it. 

I'm using workadventure on chrome last version. I can explain/show the problem directly on workadventure if that can help.

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

Please have a look at #612

**Comment by mapapuche** [comment]
Hello,

I'm talking about the button you have on the bottom right to share youtube video.

![image](https://user-images.githubusercontent.com/64193148/105967514-3837d780-6086-11eb-8d5f-a6c67061ec76.png)

And also, i once i the video is shared, i can't remove it or close it :x

**Comment by tabascoeye** [comment]
That is all a configuration problem of the Jitsi server used, not the workadventure per se.
Bascially anything happening on that right frame is the Jitsi servers job.

**Comment by gparant** [comment]
We have deployed the feature to share video live straeming on YouTube or video YouTube on our Jitsi. If you want more information, you can see our documentation : [https://workadventu.re/admin-guide/streaming-conferences](https://workadventu.re/admin-guide/streaming-conferences).

I close this issue and stay available if you have any question.

Thanks for your feedback 💪
