### ISSUE TITLE
Idea : Share note with a board or take controle option

### ISSUE THREAD

**Issue by mapapuche** [thecodingmachine/workadventure#662]
Hello,

First of all, sorry if it's not here where i can put my ideas. Correct me if i'm wrong :)

We are trying this new adventure with my dev team.
Here an idea that can help us a lot, add the possibility to share computer controle (like team viewer or other). Or maybe a workaround that could be cool, to be able to use something like a board to share some notes between us. For example that could be very nice if one dev could draw something on a board and share it with the team.

**Comment by djmaze** [comment]
Whiteboard sharing can already be done today by using an `openWebsite` layer with a tool like [WBO](https://wbo.ophir.dev/) so it opens as an iframe on the side.
