### ISSUE TITLE
Using jitsi-office property

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#671]
Hi,

I have noticed that creating a layer zone with the jitsi-office property seems to open the same Jitsi conference with people from other maps.
Is this a property dedicated to a conference for all the maps ?

**Comment by shug0** [comment]
Hello, each jitsi meeting room is created based on the id you set into the custom property `jitsiRoom`, if 2 maps have the same meeting it means that you are using a already defined id.
![image](https://user-images.githubusercontent.com/2612496/106117043-ead56c00-6152-11eb-9b2e-dcbd9889eabf.png)

**Comment by Jacques-Olivier-Farcy** [comment]
I see, thanks !
