### ISSUE TITLE
Animation not playing

### ISSUE THREAD

**Issue by TV-Plagwitz** [thecodingmachine/workadventure#674]
I added an amination in tiled editor where its playing in preview as intented. After pushing the map to github it ist not animated at all. What could be the problem with this?

**Comment by shug0** [comment]
Hello, this is related to this feature https://github.com/thecodingmachine/workadventure/issues?q=is%3Aissue+is%3Aopen+animated wich is not merged yet : https://github.com/thecodingmachine/workadventure/issues/423

**Comment by TV-Plagwitz** [comment]
But why it is already explained in the map building tutorial, when it is still not implemented?

https://workadventu.re/map-building/animations

**Comment by tabascoeye** [comment]
probably over-enthusiasm ;)
We had the animated tiles already running for our event (rc3), so maybe people assume that it's already working on the main branch. But it will take a merge or two to get running…

**Comment by GRL78** [comment]
Animated tiles are now supported : https://workadventu.re/map-building/animations
