### ISSUE TITLE
Getting the browser console in MacOS

### ISSUE THREAD

**Issue by Corps-git** [thecodingmachine/workadventure#675]
In the troubleshooting section of the documentation it says:
"If your map is not displaying correcly (most notably if you are getting a black screen), open your browser console. This is usually done by pressing the F12 key and selecting the "console" tab."
I really would like to use this console information - but F12 on a mac just turns the speaker louder.
What is the F12-equivalent key on the Mac to get the browser console?

**Comment by tabascoeye** [comment]
On a Mac it is "Fn+F12" because the F-Keys are all function mapped on Mac, so pressing the "Fn" key along with them triggers the "real" F-Key.

**Comment by Corps-git** [comment]
Thank you.

Actually Fn triggers a function key, but (at least on my macbook) is used to toggle the dashboard.

But I found another solution:

https://appuals.com/open-browser-console/
