### ISSUE TITLE
404 jitsiRoom not found

### ISSUE THREAD

**Issue by bioMK** [thecodingmachine/workadventure#676]
Hello ! 

I am having trouble while launching a jitsi room. 
![image](https://user-images.githubusercontent.com/77967146/106144660-cc806800-6174-11eb-87b4-9230df35a743.png)

If I click on "create a new conversation here", I am still not able to create the room ... (it doesn't recognize me as the host of the meeting)

Can you help me ? 

Here are the properties I have put.
![image](https://user-images.githubusercontent.com/77967146/106144739-e8840980-6174-11eb-94a6-8ce130705710.png)

**Comment by moufmouf** [comment]
Hey @bioMK,

Are you running on https://play.workadventu.re or is this a self-hosted instance?

**Comment by bioMK** [comment]
Hello @moufmouf,

Yes, I am running it on https://play.workadventu.re/

Should I created a self hosted instance instead?
If yes, how can I do it please ?

**Comment by moufmouf** [comment]
@bioMK Sorry for the delay. I've never seen this issue before.
Could you send me a link to your map (the URL that starts with https://play.workadventu.re/) and also a link to your map on Github (assuming the map is hosted on Github pages?)

**Comment by gparant** [comment]
I close this issue. Thanks for your feedback 💪
