### ISSUE TITLE
Jitsi room not working

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#695]
Hi,

so i am trying to make a Jitsi room on a silent zone.
When i arrived to the zone, the Jitsi windows opened.
But after asking for microphone and camera, it is said :

![image](https://user-images.githubusercontent.com/19731340/106509703-3f1f7980-64ce-11eb-9cdd-f0b5984485e1.png)

**Comment by spezi** [comment]
Hi .. 
sitent zone means that no jitsi is allowed there. If there a jitsi room, everybody joining that jitsi room, so no silent zone needed. You have to delete the silent tiles.

**Comment by Jacques-Olivier-Farcy** [comment]
Thanks @spezi

**Comment by Jacques-Olivier-Farcy** [comment]
solved…
