### ISSUE TITLE
Screen Share with 3 other people not fully functional

### ISSUE THREAD

**Issue by superseby2** [thecodingmachine/workadventure#705]
Hello, 

I tried today to share my screen with 3 other people that were in my Bubble. 

- first attempt : out of the 3 1 could see it
- I came back from the buble and came back : the 2 that could not see it, saw it but not the one who was seeing it previously
- I ask that person to leave and re-enter the bubble with no success.

Thx!

**Comment by tabascoeye** [comment]
@superseby2 there have been a few bugfixes regarding that. Can you re-try with the current deploy and give feedback if this issue can be closed?

**Comment by gparant** [comment]
We solve this issue with previous release 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create new issue 😍
