### ISSUE TITLE
Self hosting JSON files returns in error

### ISSUE THREAD

**Issue by davidhuberff** [thecodingmachine/workadventure#706]
Hello everyone, I want to host my maps on my own web server (Apache2).

https://play.meet.n2n.io/_/global/c0c0bird.github.io/chaos-world/main.json

If I change the c0bird.github.io .... part to the JSON URL I get a 404 error, although the file exists.

**Comment by moufmouf** [comment]
Do you have CORS headers enabled on your webserver?

See https://workadventu.re/map-building/hosting for the exact settings you need to put.

**Comment by davidhuberff** [comment]
Now it works. CORS wasnt enabled on Port 443.  My bad. Thank you.
