### ISSUE TITLE
Add the possibility to have sound files in a directory

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#707]
Hi,

Could it be possible to store the sound and music files in a specific sub-directory ?

**Comment by MacGyverBeta** [comment]
This works for me:
I have a map.json and in a subfolder "sounds" different mp3 files.
The sound layer has the property "playAudio" with value "sounds/bar.mp3"

**Comment by Jacques-Olivier-Farcy** [comment]
I have tested another time and yes it worked.
thanks
