### ISSUE TITLE
Text in Tiled created map not displayed in Work Adventure Map

### ISSUE THREAD

**Issue by dranol2021** [thecodingmachine/workadventure#719]
I created my own map based on a given map and tried to insert some text via Tiled. In Tiled the text is shown but not in the Work Adventure map after the json map is actualized. What's wrong?

**Comment by moufmouf** [comment]
Hi Andreas!

This is normal. All the features available in Tiled are not supported in WorkAdventure.
In particular, anything you put in a "object" layer will not be displayed.

If you want to display some text, so far, you need to write the text in a PNG file and put this text as "tiles".

You can have a look at all the supported features in the documentation here: https://workadventu.re/map-building

**Comment by dranol2021** [comment]
Thanks!
