### ISSUE TITLE
"Docker-compose up" not working

### ISSUE THREAD

**Issue by dhg-schule** [thecodingmachine/workadventure#724]
I want to host workadventure on my own server with Ubuntu 20.04 and Apache2 (Cors are activated in the config-file) (docker and docker-compose are installed (sudo apt install docker docker-compose), but if I run docker-compose up there are many errors. I want to use my own Jitsi-Server (hosted on an other Server)
What have I to do?

**Comment by dhg-schule** [comment]
I get the message "Creating workadventuer_reverse-proxy_1 error
Error starting userland proxy: listen: tcp 0.0.0.0.:443: bind: adress already in use

**Comment by moufmouf** [comment]
This means there is already a server installed on your machine and listening on port 443.
Are you having a webserver like Apache or Nginx installed on the same machine?

**Comment by dhg-schule** [comment]
Yes, I have installed an Apache2 Server on the same machine. And I`ve got a letsencrypt certifikate for the server. Do you have an idea, what I can do?

**Comment by MacGyverBeta** [comment]
@dhg-schule did you find a solution to your problem?

**Comment by dhg-schule** [comment]
Yes, I got a solution! I stopped the Apache-Server and then I started the Dockers. This was my solution, that worked.
