### ISSUE TITLE
Screen black when trying to start/load

### ISSUE THREAD

**Issue by dranol2021** [thecodingmachine/workadventure#740]
Frequently I get the error that after deploying with github and trying to view the deployment I get a black screen only. The activation of the camera and sound works. For a very short time I can see "Loading ..." but then the screen becoms black. Nothing can resolve that issue but starting the project from the very beginning. Does anybody know why this happens?

**Comment by NullPointer313** [comment]
HI,
I had the same problem, before I realised there was an answer in the manual: https://workadventu.re/map-building/wa-maps
I had to embed the Tilesets (there is a button) - and viola it worked!

regards

**Comment by GRL78** [comment]
@dranol2021 Have you still this issue ?

**Comment by gparant** [comment]
WorkAdventure core was improved and it seems to solve in previous release 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create new issue 😍
