### ISSUE TITLE
Improved Silent Zone

### ISSUE THREAD

**Issue by seblemarec** [thecodingmachine/workadventure#745]
Hi,

Your job is amazing guys! We love this app in Montreal.
I have an improvement suggestion: it would be great if video and sound would automaticaly stop/start when you get in/out of a silent Zone. Impact on performance and bandwith will be good (let's be green when we can )and UX will be improved. 

Have a nice day.

**Comment by Lukas1818** [comment]
A indicator at the display corner that you are in a silent zone would also be nice.

**Comment by jonnytest1** [comment]
partially going into the same direction (though not sure if its widely wanted since it has some down sides )

i made myself a custom little script that stops updating the camera when you go to a different tab 🤔

**Comment by GRL78** [comment]
Silent zone now automatically stop/start camera and microphone when you get in/out. The camera is replace by a text 'Silent Zone' when you are in a silent zone.
