### ISSUE TITLE
Use of admin features

### ISSUE THREAD

**Issue by Danyc0** [thecodingmachine/workadventure#750]
I've managed to get a setup working on my server using the very helpful comments in #738, and am now trying to get access to the admin features which are referenced throughout the repo.
Ideally I'm looking for things like: whitelisting/blacklisting, kicking/banning users, general log outputs/usage statistics, etc.

There seem to be references to an admin console/admin page/admin API in the repo, but I can't find any documentation on how to actually get access to any of these.
Is someone able to shed some light on this? Thanks!

**Comment by t10r** [comment]
That is something I would also like to know and search for a long time. Thanks for that question.

**Comment by Jorval** [comment]
refering to their pricing page this is a paid feature.
https://workadventu.re/pricing

Unfortunately, because i think some kind of access control is a mandatory thing in 2021. but i'am not sure, just guessing. when there is a admin page we selfhoster can access i would be interrested too.

**Comment by gparant** [comment]
Hi,

The premium feature is available on our [Website]( https://workadventu.re). You must create an account and subscribe an event or virtual office. If you want more information or have any question, send us an email at workadventure@thecodingmachine.com.

I close this issue and still available if you have any question,
thanks for your feedback 💪
