### ISSUE TITLE
Improve Jitsi config override

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#755]
See https://github.com/thecodingmachine/workadventure/pull/753

We should modify this PR so that:

- When a map developer says the webcam or microphone is silent, it is always silent (even if the user has enabled webcam / microphone) => So if `startWithAudioMuted` or `startWithVideoMuted` is set to false in the map, it is always enforced
- Otherwise, we take the current state of the user in WA and put it in Jitsi

**Comment by moufmouf** [comment]
The fix at #757 is completely breaking the new config feature.

You can test is with this test map: http://play.workadventure.localhost/_/global/maps.workadventure.localhost/tests/jitsi_config.json

The new fix is only merging 3 properties (startWithAudioMuted, startWithVideoMuted and prejoinPageEnabled).
But there are dozens of properties that can be added in the Jitsi config in the map (like setting the background color, etc...)

For the record, this feature was developed by the 3 of us (@moufmouf @Kharhamel @gparant ), in 3 different PRs that were all  merged without a review. Each PR introduced a bug :exploding_head: 
Maybe we need to take code review more seriously :D

**Comment by gparant** [comment]
I think that dozens of properties that can be added in the Jitsi config will be defined in jitsiInterfaceConfig? And it's not this change, but if tomorrow we will add new config, I permit to override jitsiConfig.

**Comment by gparant** [comment]
Test success full 

![image](https://user-images.githubusercontent.com/23724509/108333920-b7c24d80-71d1-11eb-982c-71500c290ea5.png)
