### ISSUE TITLE
Le dernier participant (à partir de 3) n'entend pas les autres participants si l'un d'eux coupe et remet son micro

### ISSUE THREAD

**Issue by ThibBal** [thecodingmachine/workadventure#761]
Nous avons remarqué, après plusieurs tentatives, que lors d'une discussion à 3 (en mode "cercle"), le dernier participant (C) "perd" la communication (sonore au minimum) avec l'un des deux autres participants (A et B) si l'un des deux (A ou B) désactive puis réactive son micro.

Si A coupe et remet son micro : 
- A et B s'entendent
- B et C s'entendent
- A entend C
- C n'entend pas A

Bonus : si le dernier participant (C) désactive et remet son micro, c'est B qui ne l'entend désormais plus. 

Reproductible à 100%.
![Capture d’écran 2021-02-18 à 16 06 40](https://user-images.githubusercontent.com/6185745/108377263-25876d00-7204-11eb-9d0f-ec3a56987817.png)

**Comment by GRL78** [comment]
Now fix by this PR : https://github.com/thecodingmachine/workadventure/pull/1402
