### ISSUE TITLE
start tag #entrypoint ist not working anymore

### ISSUE THREAD

**Issue by nivadis** [thecodingmachine/workadventure#767]
hey
as mentioned here
https://workadventu.re/map-building/entry-exit
entering a map with ``map.json#startlayer`` seems not to work .. or only work sometimes on latest version, worked in the past. did something changed and is not documented jet?

on https://gparant.github.io/tcm-client/TCM/corridor-map/map.json when used with @ it seem to work all the time

thanks.

**Comment by gparant** [comment]
The previous release of WorkAdventure solved this issue 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create new issue 😍
