### ISSUE TITLE
weird drawing differences in Firefox

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#768]
I'm on the same instance on the same map with 3 browsers.
Firefox has some weird drawing difference with these animated tiles below the sun.
Safari and Chrome do not have such problems. Is this a Phaser issue?!

<img width="1471" alt="Screenshot 2021-02-22 at 13 58 29" src="https://user-images.githubusercontent.com/111893/108712225-bf0d9200-7516-11eb-9a71-b32f00611402.png">

Left is Firefox, Middle is Safari, right is Chrome

**Comment by moufmouf** [comment]
Weird!
I'm not 100% sure.
Having Chrome and Safari displaying the same thing is logical since they use the same Chromium engine.
Why Firefox is displaying this? I don't know. Do you have any kind of transparency set on one of the layers?

**Comment by moufmouf** [comment]
By the way, beautiful map!

**Comment by tabascoeye** [comment]
you should see the full thing ;)
No it doesn't seem to matter about layers or anything.
Tried placing the anim part on the highest layer and deleting any content in the tiles in layers below.
Still persists in firefox.

**Comment by tabascoeye** [comment]
I thought Safari used WebKit

**Comment by tabascoeye** [comment]
WTF. With my current Firefox version this no longer happens?!?
=> closed

**Comment by tabascoeye** [comment]
Addendum: I can still reproduce this but apparently only on my external monitor?! This is getting weirder and weirder

**Comment by moufmouf** [comment]
Could it be related to a specific "color profile"?
See https://www.color-management-guide.com/web-browser-color-management.html (and especially the part about Firefox)

**Comment by tabascoeye** [comment]
yes. gfx.color_management.mode=1 seems to fix it \o/
But that also means I apparently have a different color space saved in the animation pngs vs my background png (one comes from PhotoShop, one from Aseprite....)
