### ISSUE TITLE
[admin] White screen when removing all worlds

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#769]
The admin console let's you remove a world. But there is no way to add a new one. As a result, it is possible to have... no worlds at all.

It looks like this:

![image](https://user-images.githubusercontent.com/1290952/108740832-60581080-7536-11eb-9754-62fb6c255f6b.png)

Database state:

![image](https://user-images.githubusercontent.com/1290952/108740887-6c43d280-7536-11eb-9070-f81cf8adddb8.png)

We should prevent deleting worlds until we allow to adding worlds

**Comment by GRL78** [comment]
Now possible : 
![Screenshot from 2021-09-15 15-32-38](https://user-images.githubusercontent.com/80678534/133442966-0cc2bad4-64dd-4b07-aa4f-c663d42832ce.png)
