### ISSUE TITLE
[Feature request] Add possibility to express emotions through emojis

### ISSUE THREAD

**Issue by plan5** [thecodingmachine/workadventure#795]
It would be great to have an option to show emotions by (temporarily) displaying emojis above the player name.
This would be similar to how it is done in "The Sims".

Maybe this could become something of a bundle on functions about letting the player express emotions? 
There are also #567 and #788 that look for ways of expression.

Further options could be dancing animation, for example.

**Comment by xFragger** [comment]
+ <3 for custom give expressions, but only allowed per server, for sure

**Comment by tabascoeye** [comment]
fixed by #863 ?

**Comment by moufmouf** [comment]
Definitely fixed by #863! Thanks @tabascoeye  \o/
