### ISSUE TITLE
Unable to run on a Raspberry Pi 4

### ISSUE THREAD

**Issue by manthis** [thecodingmachine/workadventure#800]
I am trying to run WorkAdventure on a Raspberry Pi 4. I have git cloned the repository and launched a docker-compose up in order to start all the containers. Unfortunately, I get the following errors:

I suspect it is caused by a difference of platform since Raspberry Pis are ARM based. Can someone confirm?

Does someone have a workaround? Should I build all the images and in this case how to do such a thing?

Thanks for the help

**Comment by Jacques-Olivier-Farcy** [comment]
Hi,

I am also intersted to have workadventure on a Raspberry PI 4.
I hope they wil deliver a docker ARM compatible version.

(I don't have enaugh skills to make my own docker build).

**Comment by Felix-Franz** [comment]
I am also interested to use this on a raspberry pi!

Currently, Docker images are only built for arm64.
Maybe it makes sense to build the Docker images for `armhf` and `arm64` as well.
You can use [`docker buildx`](https://docs.docker.com/buildx/working-with-buildx/) command to build images for multiple architectures.

@manthis @Jacques-Olivier-Farcy Did you tried to use [this docker-compose configuration](https://github.com/thecodingmachine/workadventure/blob/master/contrib/docker/docker-compose.prod.yaml)?
This configuration should build workadventure images locally and uses [traefik:v2.3](https://hub.docker.com/layers/traefik/library/traefik/v2.3/images/sha256-a514d1067beb769fd25480cba0ffc0bd2aa5f44a004f9d33dc0465c3db9f5c3c?context=explore) which is available for `arm` & `arm64`.

**Comment by Kharhamel** [comment]
I don't know much about raspberries. Don't they use a regular linux distribution? I am not sure what we can do to help you.

**Comment by Jacques-Olivier-Farcy** [comment]
It is a debian based system on ARM called raspbian

**Comment by sur5r** [comment]
There are 3 ways to get a 64 bit OS onto the RPi4:
- 64 bit RaspiOS: https://downloads.raspberrypi.org/raspios_arm64/images/
- Ubuntu Server for ARM: https://ubuntu.com/download/raspberry-pi
- Vanilla Debian for Raspberry Pi: https://raspi.debian.net/tested-images/

**Comment by jonnytest1** [comment]
ah shoot all my node images have too much stuff added to them on the side

this should be a good start for the raspbberry pi docker node image (its sort of crudely ripped out of a nodemon setup so im not sure its 100% diretly working)
```node.sh
#!/bin/bash
cd /var/node
npm run start
```
```
FROM balenalib/rpi-raspbian:stretch

RUN apt-get update --fix-missing
RUN apt-get install curl software-properties-common
RUN apt-get install python2.7 make
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -

RUN apt-get install nodejs
RUN apt-get install build-essential
RUN mkdir -p /var/node/node_modules
VOLUME /var/node/node_modules

ADD node.sh /node.sh
RUN chmod 777 /node.sh

ENTRYPOINT /node.sh
```

**Comment by lukashass** [comment]
I will have a look at this in the next few days. Basic plan:

- base `front` on official nginx image
- use [docker/build-push-action@v2](https://github.com/docker/build-push-action) to build multi-platform images

**Comment by lukashass** [comment]
Preliminary arm64 images are now available tagged as [multi-platform-images](https://hub.docker.com/layers/thecodingmachine/workadventure-front/multi-platform-images/images/sha256-6fe3110c597c6f218122ca9a531659e85627e54fbe1fbc4c37935a9e6c8aa50a?context=explore).

Maybe someone wants to try those.

32bit Arm support will be more difficult (see https://github.com/thecodingmachine/workadventure/pull/1924#issuecomment-1049011180). As arm64 is now officially supported by Raspberry Pi OS it should be sufficient though.

**Comment by spreequalle** [comment]
great stuff! i can confirm that frontend, backend & pusher service are running already.
uploader & maps are'nt multi platform images yet.

> $ uname -m
aarch64
$ kubectl -n workadventure get pods
NAME                                     READY   STATUS             RESTARTS      AGE
workadventure-pusher-5ffc5cf7fc-dqkmx    1/1     Running            0             2m54s
workadventure-front-ddc55bbf6-mzdkc      1/1     Running            0             2m54s
workadventure-back-684d9cbc5d-25zzt      1/1     Running            0             2m54s
workadventure-uploader-5d99f9c68-xt2tn   0/1     CrashLoopBackOff   4 (87s ago)   2m54s
workadventure-maps-5f786446c9-6cfx9      0/1     CrashLoopBackOff   4 (76s ago)   2m54s

**Comment by lukashass** [comment]
@spreequalle Thanks for the feedback.
I was going off of the [production docker-compose file](https://github.com/thecodingmachine/workadventure/blob/develop/contrib/docker/docker-compose.prod.yaml). Since it does not include `uploader` and `maps`, I don't think those need to be multi-platform images.
`uploader` would be easy to build multi-platform, but `maps` depends on a base image that is not multi-platform (yet).

What is your use-case for `uploader` and `maps`?

**Comment by spreequalle** [comment]
> @spreequalle Thanks for the feedback. I was going off of the [production docker-compose file](https://github.com/thecodingmachine/workadventure/blob/develop/contrib/docker/docker-compose.prod.yaml). Since it does not include `uploader` and `maps`, I don't think those need to be multi-platform images. `uploader` would be easy to build multi-platform, but `maps` depends on a base image that is not multi-platform (yet).
> 
> What is your use-case for `uploader` and `maps`?

never mind i was under the impression that it's needed since changing START_ROOM_URL to the URL mentioned in the contrib folder does nothing for me, figured out it's a local caching issue https://github.com/thecodingmachine/workadventure/issues/1929

got it one step further with START_ROOM_URL="/_/global/maps.workadventu.re/starter/map.json"

In general i try to revive the helm chart here using an arm64 based server running a k3s cluster
https://github.com/gmoirod/helm-workadventure
