### ISSUE TITLE
Add some cats and dogs sprites ?

### ISSUE THREAD

**Issue by Jacques-Olivier-Farcy** [thecodingmachine/workadventure#802]
Hi,

If the licence allowed you to use it.
Can you add these sprites ?
https://opengameart.org/content/lpc-cats-and-dogs

I would really enjoy to walk in workadventure as a cat !

**Comment by pizkaz** [comment]
Hmm, what about the [sprites from rC3](https://github.com/workadventure-xce/workadventure-xce/commit/12e202bc48c8966a743819b4f14a103a09f3ad22)? Is there a reason not to include those?
@tabascoeye do you know who created those?

**Comment by tabascoeye** [comment]
pretty sure this is all Pipoya assets.
Apart from the totally specific CCC stuff. (talk/no-talk sign, Wheelchair, mask, tinfoil hat,...)

**Comment by moufmouf** [comment]
See #870

**Comment by Jacques-Olivier-Farcy** [comment]
Amazing !

**Comment by Jacques-Olivier-Farcy** [comment]
meow meow meow

**Comment by pizkaz** [comment]
> I would really enjoy to walk in workadventure as a cat !

Well with linked PR you are not really able to walk *as* a cat but rather *with* a cat. ;-)
