### ISSUE TITLE
Weird restarting behaviour

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#804]
On a production instance with several pushers, when I restart all docker, in a given room, I can be split across 2 "parallel universes".

If I restart all the pushers (and only the pushers), everything goes back to normal.

It is like if the pushers manage to start before the API, the users are connecting to the pushers and they are not getting the position of the other users (since they come from the API) We should investigate this.

**Comment by gparant** [comment]
Keep going?
