### ISSUE TITLE
"muted" icon not visible on very bright video/backgrounds

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#822]
a few versions back, the style of the "muted" icon was mutilated because the new "local block" icon also uses the class `active` in the style.css.

But now hen you have very bright video or background in view, you will **not** see the icon:

### Proof
<img width="444" alt="Screenshot 2021-03-18 at 20 34 29" src="https://user-images.githubusercontent.com/111893/111687497-a00ad300-882a-11eb-884f-eaf7876e5ee6.png">

View of "Muted" on total black video

<img width="435" alt="Screenshot 2021-03-18 at 20 35 38" src="https://user-images.githubusercontent.com/111893/111687499-a0a36980-882a-11eb-9405-39adbec9f033.png">

view of "muted" when a very bright spot is in the peer video

<img width="425" alt="Screenshot 2021-03-18 at 20 39 49" src="https://user-images.githubusercontent.com/111893/111687501-a0a36980-882a-11eb-818d-8274d7089ce1.png">

proposed new CSS style for the icon

I propose to add
````
    border-radius: 50px;
    width: 30px;
    height: 30px;
    background-color: red;
    bottom: 20px;
````

to the `.video-container img.active` part of the CSS.

**Comment by gparant** [comment]
Thanks for your proposition. Today we would stay homogeneous with Jitsi that stay our only application of meeting.

<img width="159" alt="Capture d’écran 2021-04-24 à 15 39 12" src="https://user-images.githubusercontent.com/23724509/115960727-568d6200-a513-11eb-8048-f6bcc81ab182.png">

I close this issue, but keep your proposal. Thanks a lot 💪

**Comment by tabascoeye** [comment]
@gparant : well they have a pending issue open for the same reason ;)
https://github.com/jitsi/jitsi-meet/issues/8325

**Comment by tabascoeye** [comment]
the suggestion there is maybe even nicer (transparent/alpha black background and red muted icon)
