### ISSUE TITLE
Error404 while loading private maps

### ISSUE THREAD

**Issue by Meliqqe** [thecodingmachine/workadventure#829]
After the visual docker set up I get an error 404 while choosing a private map to test the application. I tried it with all private maps and none of them worked.

**Comment by jonnytest1** [comment]
sorry i dont hink we can help you with your network problems especially with this little information - make sure your paths are setup correctly and the server serves the json and corresponding files

**Comment by gparant** [comment]
I close this issue, we still available if you have any questions.

Thanks for your feedback 💪
