### ISSUE TITLE
Error occured while loading resource

### ISSUE THREAD

**Issue by Gnougio** [thecodingmachine/workadventure#843]
Hello,

I have a problem when i try to charge my map on workadventure. A message appears telling me : "An error occured while loading resource : https://gnougio.github.io/my-map/../Documents/GitHub/my-map/Interiors_32x32.png

This file is however present in my github folder... can you help me??

**Comment by Razielruss** [comment]
You probably used a tiled set that was saved in your path Documents/GitHub/my-map. So your json file tries to find your image or your tilset that u have used in the same directoy. But your repository hasn't got the direcory  Documents/GitHub/my-mapand you get the error. So you have to edit your json file and set the Directory in the property image of your tilset that is saved in your repository. Save and wait maybe 5minutes and it should work.

**Comment by moufmouf** [comment]
Thanks @Razielruss for the detailed answer. This should fix the issue. I'll close it for now. @Gnougio , feel free to open it again if you are still facing the problem.
