### ISSUE TITLE
Bug: starting on tile which is a block (collide) and marked as startLayer, movements are not blocked

### ISSUE THREAD

**Issue by Wikinaut** [thecodingmachine/workadventure#855]
By mistake, I placed a "start" onto a tile which is part of a wall and therefore also marked as collide block.

When landing there (from another room), I could walk on all blocked tiles (= bug) of the wall until I left the blocked area. Then, re-entering those tiles is block (as expected).

**Comment by tabascoeye** [comment]
thats the way the collision calculation works in "arcade" mode of Phaser. Workadventure does not do its own collision calc.

**Comment by Wikinaut** [comment]
@tabascoeye So, we should regard this to be a ```feature``` rather than a ```bug```, well, ok.


Should be perhaps documented because it can be used as a one-way path function (to land - exiting from another room Alice - in room Bob on tile X1, this tile having a block, then either leave the block tile X (no way coming back there) or as a kind of switch because arriviing on blocked X you can walk along adjacent blocked tiles X2, X3, … to another location or another room Carol).

**Comment by tabascoeye** [comment]
I'm just saying that this is inherent in Phaser. So there can't be an easy fix in WA code.

**Comment by Wikinaut** [comment]
Shall I reopen this issue?
