### ISSUE TITLE
Transition between two co-website fails

### ISSUE THREAD

**Issue by GRL78** [thecodingmachine/workadventure#857]
When you change from a layer with  openWebsite property to another layer with openWebsite property, the transition between iframes fails.

**Comment by gparant** [comment]
Thanks for your feedback, we work on it with @Kharhamel  and we propose you a fix soon 🚀

**Comment by jonnytest1** [comment]
in the meantime you cna probably handle this case manually with a script in the map properties and utilizing the API methods openCoWebsite and closeCoWebsite (and making sure the first one is closed before triggering the new)

**Comment by nolway** [comment]
The CoWebsite has been reworked !
