### ISSUE TITLE
feature proposal: dynamic tiles reload

### ISSUE THREAD

**Issue by oliverlorenz** [thecodingmachine/workadventure#869]
I have been carrying around an idea for a few days that I would like to discuss.

I would like to reload a single tile while the game is running. The goal is to have some kind of visual indicator for whatever. An example would be to turn a PC monitor on or off to indicate that a colleague is available or not.

For this I have the following thoughts, with the mentioned example in mind:

1. you need a picture renderer that is reachable via http(s). If the colleague is available, the computer monitor is rendered green, if he is not there black. The renderer could look at his Slack status in the background to decide that. (That doesn't matter at the moment and is not part of this implementation. But I think the idea is clear)

2. new properties have to be maintained on the tile itself.
```
[...]
{
         "columns":3,
         "firstgid":6407,
         "image": "workadventure-tiles\/custom\/functional.png",
         "imageheight":128,
         "imagewidth":96,
         "margin":0,
         }, "name": "functional",
         "properties":[
                {
                 "name": "httpImageSource",
                 "type": "string",
                 "value": "https:\/\/example.com\/pc-monitor-of-bob.php"
                }, 
                {
                 }, "name": "reloadMs",
                 "type": "string",
                 "value": "10000"
                }],
         "spacing":0,
         "tilecount":12,
         "tileheight":32,
         "tiles":[
                {
                 "id":0,
                 "properties":[
                        {
                         "name": "collides",
                         "type": "bool",
                         "value":true
                        }]
                }],
         "tilewidth":32
        }
[...]
```

Here I added the `httpImageSource` and `reloadMs` values to the properties of the tile. These could be read at [this location](https://github.com/thecodingmachine/workadventure/blob/8529037493442edffd8c524a33660896e3946648/front/src/Phaser/Game/GameScene.ts#L243) and periodically reload a tile. Theoretically you could also simply store a URL in the `image` property. However, as far as I know, the tiled editor cannot handle this. So the properties are a better idea.

So it should be easy to add a `setInterval` here, which calls the load-command periodically. Unfortunately I am not sure how Phaser reacts at this point. Does it then reload the tileset, or is there more to do here?

**Other random ideas that could be implemented with this**:
* Closed / Open signed based on time
* Include images from "any" other source (with restrictions)
* Message of the Day
* Event-based decoration
* Cycling sponsor logos

**Problems I see**:
* This is of course a client feature. With this, the interval runs independently for each player and there can be time delays among the players. Maybe the websocket could also send out some kind of "tick" event and instead of `reloadMs` you make a `reloadTickModulo` so you could synchronize the experience. Maybe this feature would be useful in general. This could also be an additional feature, which can be considered independently of it.

**Other ideas (more distant ideas):**
* A similar concept would be possible with the collision layer by modifying the data array. By setting values in the layer to 0 you could e.g. turn collisions on and off. Perfect to implement opening hours, or time-controlled display of different iFrame contents. 

---

I hope I could outline my idea a bit. I would be happy to implement them if they are desired. But before that we should discuss what is the best way to do it.

**Comment by moufmouf** [comment]
Hi @oliverlorenz ,

The idea is great, but it might cause a lot of strain on the servers, as you are reloading the same resource over and over, every X seconds times the number of connected users.

So if you are refreshing every 5 seconds and have 100 connected users, that is already 20 requests/second on the target server.

To develop this kind of features, the brand new scripting API might be better suited. See: https://workadventu.re/map-building/scripting (note: as I write those lines, the scripting API is only available from the "develop" branch)

It is not possible "yet" to interact with the map from the scripting API, but that might come in the near future. I don't think it would be tremendously difficult to add a small JS script next to a map that opens a websocket to whatever server we imagine, to track the slack status of someone, and modify the map accordingly.

Does it make sense?

**Comment by DirkHeinke** [comment]
Could this also allow adding/removing the collision property? That would allow you to open/close doors based on some API calls, which would allow for example a cool escape game.

**Comment by oliverlorenz** [comment]
> @DirkHeinke Could this also allow adding/removing the collision property?

This is what I tried to describe in the `Other ideas (more distant ideas):` block

@moufmouf 

I was not aware that there is already a similar feature is in progress. Nice!

I read a little bit into that new API. What I'm missing there is some kind of state on the server side to create a shared interactive experience. Or did I missed something? Is there already a concept for that?

Some kind of generic publish/subscribe concept to the map-state you distribute over the players would be a amazing feature. 

This would change my feature proposal in that way, that instead of loading a complete new tile, it just could switch the tile index to view a colleagues status or something. This would also make the feature possible @DirkHeinke asking for. To achieve this we would need:

* Server-Side Key-Value-Store
* new SkriptingAPI functions
  * `WA.setMapStateValue(key, value)`
  * `WA.onMapStateChanged((key, value) => { ... })`
  * `WA.setTile(index, value)`
  * `WA.onTiledChanged((index, value) => { ... })`

@moufmouf could you give feedback this could be the way to go?

**Comment by moufmouf** [comment]
@oliverlorenz Indeed, currently, you cannot share any state with the server. This will come, but is not there yet as I'm not 100% sure how to do this.

Your proposal would be awesome, but I fear this is giving too much power to the client side.
An attacker could enter a map, modify the script (or use the browser console) and use `WA.setTile` to modify the map of all players in the way he wants.

However,

```
WA.setMapStateValue(key, value)
WA.onMapStateChanged((key, value) => { ... })
```

could be a good starting point.

I'm not sure how to handle map changes yet. We could handle this by a third party server connecting to WorkAdventure (in which anyone could store code that is supposed to be executed server-side rather than client side)

**Comment by jonnytest1** [comment]
could we start with a client side state as a first step ?

**Comment by jonnytest1** [comment]
just mentioning this pull request here as it goes somewhat in the direction

**Comment by moufmouf** [comment]
@jonnytest1 I agree doing this client side only first is a first step in the right direction.
I'm currently adding a bunch of optimizations regarding energy efficiency that have a direct impact on how we can edit a map, so I postponed this is bit. But this is definitely the way to go.

**Comment by jonnytest1** [comment]
its actually quite easy :
```
 const layer = this.Layers.find(layer => layer.layer.name == event.layer)
            if (layer) {
                const tile = layer.getTileAt(event.x, event.y)
                tile.index = event.tile
                this.scene.scene.sys.game.events.emit("contextrestored")
            }
```

context restored marks the layers as dirty and redraws

it mgiht be helpful to add amethod to allow named tiles (maybe we can use the "Type" property idk if its used for seomthing else) beacuse i doubt peopel know which index belongs to which tile easily

**Comment by jonnytest1** [comment]
https://github.com/jonnytest1/workadventure/tree/update-game-tiles implemented version forked from develop

**Comment by jonnytest1** [comment]
i just realised that it only works if the tile previously existed - ie not 0

**Comment by GRL78** [comment]
You can use WA.room.setTile(...) to change a tile and create variables in the map to save and share the  change.
https://staging.workadventu.re/map-building/api-room.md#changing-tiles
https://staging.workadventu.re/map-building/api-state.md
