### ISSUE TITLE
Multiple maps

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#87]
We need to add a feature to move from one map to the other. There are several ways to do this, so I'm opening an issue here to discuss what strategy we should take.

First, the obvious part: on each map, we will put special tiles (with special properties) that can be used to "teleport" into another map (so when we go up the stairs, we are teleported to floor 2 for instance)

It is also clear to me that each map is a new room (on the server side) and a new GameScene (on the client side). Note: adding dynamically a scene to Phaser seems possible: https://phaser.discourse.group/t/loading-dynamically-named-scene/1634

Now, the question: do we put in place some kind of a "router" using the URL of the page?

My idea:

URLs like:

- https://workadventure.com/tcm/floor1
- https://workadventure.com/tcm/floor2
- or https://tcm.workadventure.com/floor1

What I like in this:

- you can start on any map by passing the correct URL (so it's cool because we can start having many companies on one server)

What I don't like in this:

- you can start on any map by passing the correct URL (so it feels less like a video game because you can teleport using the address bar)

Also, in this scenario, the server has a router map associating a URL to a Tiled map.

We could even go further and change the URL to something like:

- https://workadventure.com/?map=https://foo.com/mymap.json

This would allow absolutely anyone to provide its own map (we don't control the maps distributed anymore) which could be cool if we want to make it very wildly used. Alternatively, we could also provide a screen where anyone could upload a map.

What do you think? Where should we be going?

**Comment by storyofyours** [comment]
What about adding on the log in page the differents maps as buttons ?

**Comment by moufmouf** [comment]
@storyofyours  It makes sense for a company. But it does not make too much sense of we start having plenty of companies / people designing their own map (in the future).

Or maybe we could split by domain name (thecodingmachine.workadventure.com, sncf.workadventure.com and choose a map within this domain?) => that would be in the far future in all cases but that could be an idea. Would do you guys and gals think?

**Comment by gparant** [comment]
I think that it's a good strategy to have multi map and manage it. But I think that we must have more flexibility. For each switching map, you must get the map Json file and reload the map... I think that it's not very best strategy for the performance.

I propose you to introduce a universe. A universe has many maps and when the gamer enters into the universe (TheCodingMachien universe in our case), get all maps of this universe and preload it in the front. Like this when the gamer wants switch between map in the universe it's very fast.

For the back, no changing, one room = one scene (so one map). All users on a map will have all information of all others gamers on this map.

**Comment by moufmouf** [comment]
> Like this when the gamer wants switch between map in the universe it's very fast.

@gparant Thinking about your comment, I think I came with an even better idea: we can load only one game scene at the start of the game (so the game loads fast) but then, as soon as the scene starts rendering (as soon as we hit the `create` method), we can scan all the tiles that contain "exits" and load dynamically all the scenes that can be accessed from the current scene.

This way, we have a great initial load time (even if the universe contains 100's of maps), and absolutely no delay when switching scenes (while keeping memory consumption low).
