### ISSUE TITLE
How many people can chat in proximity chat?

### ISSUE THREAD

**Issue by Niondir** [thecodingmachine/workadventure#871]
I did not found a configuration option to define how many people can chart at the same time when beeing close to each other.

I found a server where it was limited to 2 people. On my server (default setup) it seems to be limited to 3 users.

Is the value configurable or how is the limit defined?

**Comment by Wikinaut** [comment]
At least in the fork, you can set it up in the ```.env```:
https://github.com/workadventure-xce/workadventure-xce/blob/xce/contrib/docker/.env.prod.singledomain.template#L29

**Comment by tabascoeye** [comment]
In vanilla WorkAdventure this is hardcoded to "4" (i.e. 3 persons in a gorup with you):

https://github.com/thecodingmachine/workadventure/blob/575c1a9f23228da5c9b33e3a1e61e21230c26054/back/src/Model/Group.ts#L9
https://github.com/thecodingmachine/workadventure/blob/575c1a9f23228da5c9b33e3a1e61e21230c26054/front/src/Phaser/Game/GameScene.ts#L1281

in our xce fork, we made this configurable as mentioned above

**Comment by Niondir** [comment]
Any plans to integrate this into the main project?

Else I will check out if I switch to the xce version. I'm missing an overview what's different there.

**Comment by tabascoeye** [comment]
I'm not part of TCM, so I can't say.
And yes, we need documentation on the differences between forks... any help appreciated

**Comment by Kharhamel** [comment]
Why not, i'll add it. @tabascoeye What is the name of the env variable in the xce project? Might as well use the same name

**Comment by tabascoeye** [comment]
@Kharhamel I called it `MAX_PER_GROUP` 
see also here: https://github.com/workadventure-xce/workadventure-xce/commit/2c935c6be65560ebc6a75975373aa486100d7d18
