### ISSUE TITLE
Hack into GHOST mode

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/workadventure#875]
It's actually possible to "hack" the localstorage to become invisible. By setting an empty name, and editing the character's layers, it may result in a ghost.

People would only be noticed by the circle and the sound but they might think it's a bug. Therefore someone could spy some jitsi or peer2peer conversations.

Steps to reproduce set empty values in `playerName` & `characterLayers` properties of the local storage : 
![image](https://user-images.githubusercontent.com/2227554/113743944-814e7c80-9704-11eb-94fa-f036fb671ff9.png)

**Comment by tabascoeye** [comment]
needs to be fixed either in `localUserStore.ts` module:

https://github.com/thecodingmachine/workadventure/blob/575c1a9f23228da5c9b33e3a1e61e21230c26054/front/src/Connexion/LocalUserStore.ts#L46
https://github.com/thecodingmachine/workadventure/blob/575c1a9f23228da5c9b33e3a1e61e21230c26054/front/src/Connexion/LocalUserStore.ts#L26

or in the `GameManager.ts` module:
https://github.com/thecodingmachine/workadventure/blob/575c1a9f23228da5c9b33e3a1e61e21230c26054/front/src/Phaser/Game/GameManager.ts#L27
