### ISSUE TITLE
docker-compose.prod.yaml does not provide PUHSER_URL 

### ISSUE THREAD

**Issue by jwacalex** [thecodingmachine/workadventure#903]
In the current build, the frontend  ``EnvironmentVariable.ts`` reads the URL of the pusher service from ``PUSHER_URL``, but the  ``docker-compose.prod.yaml`` in ``/contrib/docker`` provides only a ``PUSHER_DOMAIN`` to the frontend environment.

**Comment by moufmouf** [comment]
This seems fixed to me: https://github.com/thecodingmachine/workadventure/blob/develop/contrib/docker/docker-compose.prod.yaml#L40

Closing now. Don't hesitate to reopen if you have an issue.
