### ISSUE TITLE
Keyboard does not open automatically when loggin in on mobile devices

### ISSUE THREAD

**Issue by pizkaz** [thecodingmachine/workadventure#905]
Users have to tap on "Enter your name" to be able to actually type it. That seems non-intuitive to me. It would be better if the virtual keyboard opened automatically or at least after tapping anywhere.

**Comment by Wikinaut** [comment]
On my phone, it does not open the keyboard at all when tapping onto that area.

**Comment by tabascoeye** [comment]
might get closed by #900
