### ISSUE TITLE
My tiles were loading without any problem, then I started adding more tile layers and other tiles suddenly not anymore even my avatar on workadventure doesn't appear anymore. 

### ISSUE THREAD

**Issue by khjoanna** [thecodingmachine/workadventure#910]
My tilesets are not so large(1024) and I tried adding - ?phaserMode=canvas - didn't change anything. 

Here access to my repositories:

https://github.com/khjoanna/PRESENTATION/blob/main/BLA_1.json
https://github.com/khjoanna/PRESENTATION/blob/main/BLA_2.json

Would be grateful for advice, potential solutions (I am no programmer).

Thank you,
J

**Comment by tabascoeye** [comment]
your map format is "base64" instead of "CSV".
see here:
<img width="407" alt="Screenshot 2021-04-19 at 13 54 26" src="https://user-images.githubusercontent.com/111893/115232329-dfbd2700-a116-11eb-932f-76cf094e13f0.png">

**Comment by khjoanna** [comment]
@tabascoeye Thanks for getting back. Thanks for the tip, however, I adjusted it and still doesn't show the map.

**Comment by tabascoeye** [comment]
oh. And you don't have a layer called "start" with at least one tile set where the start point shall be

**Comment by GRL78** [comment]
@khjoanna Have you still an issue ?

**Comment by khjoanna** [comment]
Thanks! forgot to write. Resolved problem was indeed: your map format is "base64" instead of "CSV".
