### ISSUE TITLE
typing in chat still causes character to move

### ISSUE THREAD

**Issue by jonnytest1** [thecodingmachine/workadventure#927]
on https://play.workadventu.re/@/tcm/workadventure/demo the character doesnt move ✅ 
but on https://play.staging.workadventu.re/@/tcm/workadventure/demo and my local branch which ive checked is up to date with the develop branch typing in chat causes the character to move as well

now ive only tested it if the chat was opened by 
``` WA.sendChatMessage(text,author)```

**Comment by jonnytest1** [comment]
mediaManager.setUserInputManager(this.userInputManager);
  this.userInputManager = new UserInputManager(this);
  
  am i the only one to whom this sees wrong ? :3

**Comment by pizkaz** [comment]
Sorry, seems I messed this one up while trying to resolve a merge conflict.

**Comment by jonnytest1** [comment]
so um anyone gonna merge this https://github.com/thecodingmachine/workadventure/pull/965 ? ^^

**Comment by pizkaz** [comment]
I included your commit in the [community fork](https://github.com/workadventure-xce/workadventure-xce).

**Comment by jonnytest1** [comment]
> I included your commit in the [community fork](https://github.com/workadventure-xce/workadventure-xce).

Oh didn't know that existed 😅

**Comment by jonnytest1** [comment]
closing since merged
