### ISSUE TITLE
Rectangle for popup needs to be on floorLayer

### ISSUE THREAD

**Issue by moufmouf** [thecodingmachine/workadventure#929]
It seems that the rectangle on the popup (from the scripting API) needs to be placed on the floorLayer (and cannot be in any object layer).
We should fix that.

**Comment by Kharhamel** [comment]
What not just create a Zone instead of a rectangle for the interaction zone?

**Comment by jonnytest1** [comment]
i think its not about the interactin zone but the place where the popup will be displayed at the end 🤔

**Comment by assel** [comment]
Aaaah! Now it works for me, too - I should have had a look at the issues here first ...
By the way, there is also a typo in the first code example on popups on https://workadventu.re/map-building/scripting - the brackets right after popup.close() are in the wrong order.
