### ISSUE TITLE
SelectCharacterScene missing buttons, weird borders + scrollbars

### ISSUE THREAD

**Issue by Lurkars** [thecodingmachine/workadventure#941]
As already described in https://github.com/thecodingmachine/workadventure/pull/918#issuecomment-826901483 these changes broke some stuff and is now tagged into v1.3.0
I am not able to go to custom character selection, Co-Site controls are visible on Character Selection and some borders are weird and force a scrollbar on login screen.

**Comment by max-wittig** [comment]
It's actually completely broken in `v1.3.0`

### How to reproduce

1. Wipe all browser data (storage)
1. Try reloading

**Comment by gparant** [comment]
@Lurkars we have fix the problem on v1.3.4

Thanks for your feedback.

**Comment by gparant** [comment]
I close this issue. Thanks 🚀
