### ISSUE TITLE
oauth2 / keycloak support

### ISSUE THREAD

**Issue by ottes** [thecodingmachine/workadventure#961]
https://github.com/synax/oauth2-proxy

would be cool. if keycloak is able to accept this cookie.... if this is cool,i could invetigate tomorrow

**Comment by moufmouf** [comment]
Hey @xFragger ,

Thanks for the suggestion. Actually, I was not aware at all that oauth2-proxy existed. Cool project.

We are already planning to add some support for "login" inside WA.
The thing is that we would like to add the ability for:

- some users to be anonymous
- some users to optionaly login (using OAuth), with several identity providers

I don't think oauth2-proxy can answer to that need and we will probably need to implement that directly in WorkAdventure code.
But we will certainly plan OAuth2 support in the coming weeks so if this is interesting to you, you are welcome to help :D

**Comment by xFragger** [comment]
i guess, if you "standardize" the cookie/token/header/jwt as it is in the proxy, this could we a win/win

**Comment by Lurkars** [comment]
Would love OAuth2 (OpenID connect) support. I am currently using OIDC proxy to protect instance with dirty code for getting username from headers. I would appreciate a native support for it to only allow authorized users to access. So disabling anonymous login should be an option ones it implemented. I am deep into OIDC protocol, so happy to support if you have a public branch for this.

**Comment by moufmouf** [comment]
@Lurkars @xFragger  we are currently looking at Keycloak. A possible idea would be to integrate WorkAdventure with Keycloak and let anyone configure Keycloak as they want.
The fact is: we have 0 experience with Keycloak so far and just discovered it a few days ago.

Do you have any experience with it? Does the idea sound good to you or do you think we should avoid?
How would you guys add authentication to WorkAdventure? (remember, we would like ideally to be able to login from within the game, even if it is by opening a login iFrame)

**Comment by jonnytest1** [comment]
oh keycloak is nice - you can generally work with cookies so opening an iframe for login should work , in the keycloak realm options is a security tab that i tihnk has ifrmae options 
you can redirect to a page that triggers a postMessage after the keycloak redirects to the success page as well

**Comment by Lurkars** [comment]
Of course I would prefer generic OpenID (from personal interest) which is supported by Keycloak, so Keycloak would be supported anyways. OpenID is completely based on OAuth2, so authentication flow in general works with redirects. IFrame support is more a security config of server. So hard constrain with login directly from game, because I think most/some server won't allowing changing IFrame Options.

**Comment by jonnytest1** [comment]
> Of course I would prefer generic OpenID (from personal interest) which is supported by Keycloak, so Keycloak would be supported anyways. OpenID is completely based on OAuth2, so authentication flow in general works with redirects. IFrame support is more a security config of server. So hard constrain with login directly from game, because I think most/some server won't allowing changing IFrame Options.

well i assume there would be a setup guide containing some sort of warning that the iframe options have to be set a certain way or it wont work

**Comment by Lurkars** [comment]
@gparant I think this can be closed, since OIDC login is already available for a while.

**Comment by moufmouf** [comment]
:+1:
