### ISSUE TITLE
Error when trying to edit companion

### ISSUE THREAD

**Issue by WillyReyno** [thecodingmachine/workadventure#964]
Hello 🙂

I'm getting a black screen and the following error when clicking on "Edit companion" menu : 

![Capture d’écran 2021-04-29 à 15 03 44](https://user-images.githubusercontent.com/5576482/116555187-5f5baa80-a8fc-11eb-8055-19d5b552c475.png)

I'm wondering if it can be due to the custom skin that I have?

Thanks!

**Comment by gparant** [comment]
The previous release of WorkAdventure solved this issue 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create new issue 😍
