### ISSUE TITLE
Video not working 

### ISSUE THREAD

**Issue by suuchan** [thecodingmachine/workadventure#966]
I have an otherwise working installation. Jitsi works I can see myself in the lower right, but if two characters approach each other, the peer video fails (spinning arrows around name).

Both browsers use Chrome 90.0.4430.72 and WA is the latest master as of today. In the debugger I do get this, when two characters get close:

Removing video for userID 1.
LayoutManager.ts:167 Cannot remove userID 1. Already removed?
VideoPeer.ts:204 pushVideoToRemoteUser => 1 TypeError: Cannot read property 'addTrack' of undefined
    at t.VideoPeer.addTrack (index.js:292)
    at t.VideoPeer.pushVideoToRemoteUser (VideoPeer.ts:201)
    at new t.VideoPeer (VideoPeer.ts:108)
    at t.SimplePeer.createPeerConnection (SimplePeer.ts:150)
    at t.SimplePeer.receiveWebrtcStart (SimplePeer.ts:112)
    at SimplePeer.ts:89
    at RoomConnection.ts:434
    at p.dispatch (RoomConnection.ts:209)
    at WebSocket.socket.onmessage (RoomConnection.ts:177)

Any idea what goes wrong here?

**Comment by jonnytest1** [comment]
🤔 i dont think that error is the actual issue

**Comment by tabascoeye** [comment]
do you have STUN and TURN servers set up and configured?

**Comment by suuchan** [comment]
I have not figured out what exactly went wrong but after discarding all images and containers end rebuilding everything it works.

**Comment by gparant** [comment]
Thanks for your feedback, the new release of WorkAdventure improves video management and peer connexion management 🚀 

If you have any requirement don't hesitate to create new issue 😍
