### ISSUE TITLE
Why numbers are disallow ?

### ISSUE THREAD

**Issue by ke20** [thecodingmachine/workadventure#972]
https://github.com/thecodingmachine/workadventure/blob/16397fe97815ab02aa09788e255203ba00fa1fbb/front/src/Connexion/LocalUser.ts#L13

Before, I could add numbers in my name, but from this morning I can't :( 

Is it possible to add this again ?

And the error message is `[...] only letters and numbers are allowed [...]`, so I suppose that is a bug.

**Comment by tabascoeye** [comment]
I also don't understand why the restrictions on nicknames are this harsh now.
I know the arcade font does not include all special chars, but I would allow all which are contained?!
