### ISSUE TITLE
Auto disable webcam make robot voice on Firefox

### ISSUE THREAD

**Issue by maximehuran** [thecodingmachine/workadventure#975]
Hi !

We had the issue before when this feature were enabled.
This one was disabled and the robot voice issue disappeared. #462

But it seems you enabled agin this feature and the robot voice issue too.
Can we have the choice for this option ?

What is the advantage of auto disable the camera ?

Have a nice day 🚀

**Comment by gparant** [comment]
The previous release of WorkAdventure solved this issue.
We disable the camera for better performance 🚀 

Thanks for your feedback 💪 
If you have any other requirement, don't hesitate to create new issue 😍
