### ISSUE TITLE
New WA.openCoWebSite() function options

### ISSUE THREAD

**Issue by superh2m** [thecodingmachine/workadventure#980]
Hello there :)

I love your Iframe feature! But I think that it's not fully completed for the scripting part.

When we build our map with Tiled, we can set the properties `openWebsite`, `openWebsiteTrigger`, `openWebsitePolicy`

![image](https://user-images.githubusercontent.com/6178360/116784536-ffe4d280-aa94-11eb-8730-475b9013e32f.png)

We can do a lot of things, **but we can not add "conditions" in the map "scripting"**.

With js scripting, we can use conditions and the function `WA.openCoWebSite(url)`, that has almost the same behavior as the map scripting configurations but **without trigger and web policy features**.

So it will be great to have a **new function definition**:
```
WA.openCoWebSite(
    url: string,
    triggerAction: string,
    triggerMessage: string,
    policy: string[]
);

```
In my case, **I want to be able to enable autoplay YouTube video after entering a zone with a condition:**
```
WA.onEnterZone('zone', () => {
    if (true === true) {
        WA.openCoWebSite('https://www.youtube.com/embed/XXXX', null, null, ['autoplay']);
    }
});
```

**Comment by jonnytest1** [comment]
try adding ?autoplay=1 query parameter

**Comment by superh2m** [comment]
@jonnytest1 `?autoplay=1` parameter can't change the embedded video behavior due to YouTube cross origin policy, the autoplay has to be written on the `<iframe allow="autoplay">` attribute

**Comment by jonnytest1** [comment]
oh about that 😅 
make a .html file in your directory like 
youtube.html

```
<iframe src="https://www.youtube.com/embed/xxxx"
        height="100%"
        width="100%">
</iframe>
```
and youll easily get past that ^^

**Comment by superh2m** [comment]
Yes I a good workaround but not for my case :/, since I want to open a YouTube video only when I enter a specific zone with additional conditions, the only way possible is with the JS function, but for now It's not implemented yet

**Comment by jonnytest1** [comment]
you can just as well open your youtube.html with the openCoWebsite method

**Comment by superh2m** [comment]
Thank you for the workaround, but finally YouTube videos has some limitation regarding autoplay feature

![image](https://user-images.githubusercontent.com/6178360/116788412-ab981d80-aaa9-11eb-908e-1b8238b0d73f.png)
![image](https://user-images.githubusercontent.com/6178360/116788447-e4d08d80-aaa9-11eb-8f96-086823c8d253.png)

So I'm stuck! But I was wondering how the map properties `openWebsitePolicy` avoid that :thinking:
