### ISSUE TITLE
"Invalid user name: only letters and numbers are allowed. No spaces." triggered at numbers

### ISSUE THREAD

**Issue by miny1997** [thecodingmachine/workadventure#983]
Hello

By typing in at the demo a name with a number, it complains that only letters and numbers are allowed.

How to recreate:

1. Visit https://play.staging.workadventu.re/@/tcm/workadventure/floor0
2. Type in "3three"

**Comment by jonnytest1** [comment]
https://github.com/thecodingmachine/workadventure/pull/974 duplicate
