### ISSUE TITLE
Feature Request: openTab() as a tile-property

### ISSUE THREAD

**Issue by pheidrias** [thecodingmachine/workadventure#986]
Dear developers of this amazingly cool tool :-),

I spotted the openTab()-functionality in your scripting description.

It would be very useful, to implement this as a tile property so it can be used directly in the game. There are too many sites which don't accept being embedded in an iframe (e.g. office documents, cryptpad, ...) and I would like to have my students work with...

Thanks a lot in advance,
pheidrias

**Comment by tabascoeye** [comment]
fixed by #1405 can be closed

**Comment by gparant** [comment]
The previous release of WorkAdventure solves this issue 🚀 

Thanks for your feedback 💪 
If you have any requirement don't hesitate to create new issue 😍
