### ISSUE TITLE
stop screensharing when leaving a group bubble

### ISSUE THREAD

**Issue by tabascoeye** [thecodingmachine/workadventure#993]
Taken from Discord chat user "Naguelfar":

Hello,
an idea for improvement: cut screen sharing automatically if I'm alone. Sometimes I forget to do it when the person leaves and suddenly the next one sees my screen.

==> this could be a quick and easy fix. Just add the closedown function for screensharing to the exit function of the group (same as removing the layout and chat icons)

**Comment by gparant** [comment]
The previous release of WorkAdventure solves this issue 🚀
